### ISSUE TITLE
XSL stylesheet for XML reports

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#10]
Let's generate XSL stylesheet for all reports and make sure they all have links to it.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#10` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4085](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#10` is already assigned to @yegor256, sorry.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4100](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#10` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4305](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#10`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#10` is not in scope.
