### ISSUE TITLE
Discuss the scope of analyses with regards to a method's visibility

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#101]
Following on from [this](https://github.com/yegor256/jpeek/issues/53#issuecomment-341963890) comment:

> I would say we pay attention only to public methods.

@yegor256 
I am hesitant. I believe this would skew results in favor of an external user's view of a class instead of the actual class' absolute level of cohesion. 

Note: I already agree with the optional exclusion of ctors

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#101](https://github.com/yegor256/jpeek/issues/101) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@llorllale let's make this behavior configurable, just like we configure constructors

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+195](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#101](https://github.com/yegor256/jpeek/issues/101) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7790](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@llorllale can we close this?

**Comment by llorllale** [comment]
@yegor256 I was under the impression that some change was to be done from this ticket. Eg.: update README and Main.java with new command line parameters.

**Comment by yegor256** [comment]
@llorllale in the future keep in mind that each ticket has to be a bug, not a discussion, see: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8830](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#101](https://github.com/yegor256/jpeek/issues/101) is now out of scope
