### ISSUE TITLE
How to represent "invalid" or "no meaning"?

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#102]
Regarding NHD, page 135 of the [paper](https://github.com/yegor256/jpeek/issues/93#issuecomment-358749149) says:

> NHD has no meaning when k = 0 or k = 1

Where `k` is the number of methods of a class.

How should we represent "no meaning" as a value?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#102](https://github.com/yegor256/jpeek/issues/102) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@llorllale let's use `NaN`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+180](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#102](https://github.com/yegor256/jpeek/issues/102) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7785](https://www.0crat.com/u/yegor256)

**Comment by llorllale** [comment]
Thank you @yegor256 . I'll also be using `NaN` when `l` (number of parameter types) is zero.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7915](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#102](https://github.com/yegor256/jpeek/issues/102) is now out of scope
