### ISSUE TITLE
Introduction of 'NaN' is incompatible with MetricsTest

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#103]
Following on from #102, and considering that it seems that we should implement all tests in `MetricsTest` (see #96 and [this comment](https://github.com/yegor256/jpeek/issues/53#issuecomment-341963942)):

The introduction of `NaN` as a value for `class/@value` is incompatible with the current implementation of `MetricsTest`. As far as I am aware, the only way to test for `NaN` in an xpath predicate is by treating it as an `xsd:string`, but `MetricsTest` is expecting the value to be of type `xsd:double`.

Quickly changing `MetricsTest.value` to a String, enclosing the given values for other tests in quotes, and adapting the xpath accordingly leads to other errors, which suggests that a closer look needs to be taken.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#103](https://github.com/yegor256/jpeek/issues/103) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+240](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Job [#103](https://github.com/yegor256/jpeek/issues/103) is already in scope

**Comment by 0crat** [comment]
The job [#103](https://github.com/yegor256/jpeek/issues/103) assigned to @skapral[/z](https://www.0crat.com/u/skapral). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @skapral[/z](https://www.0crat.com/u/skapral) resigned from [#103](https://github.com/yegor256/jpeek/issues/103), please stop working

**Comment by 0crat** [comment]
The job [#103](https://github.com/yegor256/jpeek/issues/103) assigned to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/440213740). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rok-povsic** [comment]
@yegor256 Please check if I should really have been assigned this issue, see [here](https://github.com/yegor256/jpeek/pull/161#issuecomment-365247245).

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/103#issuecomment-365591876))

@yegor256 The user @rok-povsic[/z](https://www.0crat.com/u/rok-povsic) resigned from [#103](https://github.com/yegor256/jpeek/issues/103), please stop working

**Comment by yegor256** [comment]
@0crat assign @skapral

**Comment by yegor256** [comment]
@skapral you technically lost your time here. I'm reassigning you back just as an exception. Please, keep in mind that 10 days means 10 days. The robot has no mercy)

**Comment by 0crat** [comment]
> @0crat assign @skapral  ([here](https://github.com/yegor256/jpeek/issues/103#issuecomment-365598262))

@yegor256 The job [#103](https://github.com/yegor256/jpeek/issues/103) assigned to @skapral[/z](https://www.0crat.com/u/skapral), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/451252162). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).We should be aware that skapral is on vacation! This ticket may be delayed.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9659](https://www.0crat.com/u/yegor256)

**Comment by skapral** [comment]
@yegor256 I know the rules, there is no need for mercy. BTW: once ago I had a proposal on the process just for this case: https://github.com/zerocracy/datum/issues/264.

Anyway - PR is gone to upstream: are there any reason to keep this issue open?

**Comment by yegor256** [comment]
@skapral ask ticket reporter to close it, if you think it's done

**Comment by skapral** [comment]
@llorllale? Could you please close the issue?

**Comment by llorllale** [comment]
thank you @skapral

**Comment by 0crat** [comment]
Job [#103](https://github.com/yegor256/jpeek/issues/103) is already in scope

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) resigned from [#103](https://github.com/yegor256/jpeek/issues/103), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#103](https://github.com/yegor256/jpeek/issues/103) is now out of scope

**Comment by 0pdd** [comment]
@llorllale the only puzzle [#181](https://github.com/yegor256/jpeek/issues/181) is solved here.
