### ISSUE TITLE
Document some guidelines of how to create and maintain the metric in JPeek.

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#105]
IMO it is crucial, because it will be the first thing which newcomers will face in the project, and it looks non-trivial from the first glance. It can be done as a simple `.md` page or as a part of `Skeleton` javadoc.

Things worth to mention there:
1. Which data is used by metrics calculations (skeleton.xml file?)
2. How is this data collected (Skeleton class?)
3. What is the process of calculating metrics (skeleton.xml -[XSD transformations]-> <Metric_name>.xml?)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#105](https://github.com/yegor256/jpeek/issues/105) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @skapral[/z](https://www.0crat.com/u/skapral), total is [+15](https://www.0crat.com/u/skapral)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7960](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@skapral check 9472240

**Comment by skapral** [comment]
Seems ok for me.

**Comment by skapral** [comment]
@yegor256 FYI

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@skapral please, close the ticke

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8695](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#105](https://github.com/yegor256/jpeek/issues/105) is now out of scope
