### ISSUE TITLE
Are there some guidelines or precedent on testing metrics measurements

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#107]
From what I see:

1. There are some tests in `src/main/test`, but as I got it, they are covering a core of JPeek, not the metrics.
2. There is `src/main/it`, which from the name is supposed to be some integration tests, but I haven't got a thing from there. What it is about?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral isn't it a dup of https://github.com/yegor256/jpeek/issues/105?

**Comment by skapral** [comment]
We can merge it if you wish, but in #105 the matter was about documentation, and here I haven't found even a precedent.

**Comment by llorllale** [comment]
@skapral the "guidelines/precedents" can be found in test class `org.jpeek.MetricsTest`

**Comment by llorllale** [comment]
@yegor256 in `MetricsTest`, do we always have to make sure each metric is tested against all existing files? Why do all tests for metrics have to be tested in `MetricsTest`? 

I find this somewhat encumbering when adding tests for new metrics. I think it would be far easier to separate tests of metrics into their own files, eg. `NhdTest.java`. The sample test classes for each metric should be separated too. WDYT?

**Comment by skapral** [comment]
@llorllale You are right, and it's enough right now for me. I am ok with closing this issue, once all open questions asked here are solved or outlined separately. @yegor256?

**Comment by yegor256** [comment]
@skapral I would suggest to close this ticket, since it's not clear what exactly is the problem. Please open a new one (or many), for each specific bug/problem you see.

**Comment by skapral** [comment]
Ok. @llorllale, please create an issue for this part if your question is still actual:
> I find this somewhat encumbering when adding tests for new metrics. I think it would be far easier to separate tests of metrics into their own files, eg. NhdTest.java. The sample test classes for each metric should be separated too. WDYT?

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#107` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#107](https://github.com/yegor256/jpeek/issues/107) was not in scope
