### ISSUE TITLE
XSD Schema for validation

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#11]
Let's create XSD schema for the output XML documents validation.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4100](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#11` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#11` is already assigned to @yegor256, sorry.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4110](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#11` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4215](http://www.0crat.com/u/yegor256).
