### ISSUE TITLE
Need to introduce a way to extract concepts from the source code for conceptual metrics

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#110]
https://github.com/yegor256/jpeek/blob/master/papers/izadkhah17.pdf

> Conceptual metrics use information retrieval methods for class cohesion measurement. Information
retrieval methods are based on the extraction the concepts of source code. In conceptual cohesion if methods of one class are conceptually related, then class is considered cohesive

Need to introduce a way to:
1. Parse source files of classes in JPeek
2. Extract the concepts from it and store them in XML format

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral what is a "concept"?

**Comment by skapral** [comment]
@yegor256 I am not sure I can answer this question, there is lack of info on it. In this bug I outlined the fact I am sure of - conceptual metrics are based on information, extracted from sources (investigation on #17 and the definition of conceptual metrics in the reference are clear on that). Currrently, sources in JPeek are not analysed at all - this issue is for compensating this missing part.

**Comment by yegor256** [comment]
@skapral I don't think we can fix this ticket, since we don't understand what a "concept" is. If you can find a more specific information, let us know. If any particular metric you will see that we need something on top of what we already have in the `skeleton.xml` -- create a new ticket please.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#110` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#110](https://github.com/yegor256/jpeek/issues/110) was not in scope
