### ISSUE TITLE
App.java:59-62: LORM metric has impediments (see puzzles...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#111]
The puzzle `15-9a121b89` from #15 has to be resolved:

https://github.com/yegor256/jpeek/blob/97a80bf82afb2db0d40171038596a305478a6a2e/src/main/java/org/jpeek/App.java#L59-L62

The puzzle was created by Kapralov Sergey on 26-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#111](https://github.com/yegor256/jpeek/issues/111) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#111](https://github.com/yegor256/jpeek/issues/111) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/450853032). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@rok-povsic hi
Can you give a concrete example for what you wrote in #155?
> Another
     definition of `domain` also comes to mind - the programming language being
     used. Concepts could be defined as all reserved Java keywords and "semantic
     processing" recognizes which reserved keywords are used in a particular
     method. Hence, if two methods use same reserved keywords, they have a
     `conceptual-relation`. Using this definition would require no additional
     input by the user of the LORM method.

Do you mean if two methods use the keyword `new` then they could potentially both have a semantic relationship?

**Comment by llorllale** [comment]
Some additional supporting papers:

[Dynamic analysis of Java program concepts for visualization and profiling.pdf](https://github.com/yegor256/jpeek/files/1724654/Dynamic.analysis.of.Java.program.concepts.for.visualization.and.profiling.pdf)
[An Information Retrieval Approach to Concept Location in Source Code.pdf](https://github.com/yegor256/jpeek/files/1724655/An.Information.Retrieval.Approach.to.Concept.Location.in.Source.Code.pdf)

**Comment by llorllale** [comment]
@yegor256 a question: while working on this puzzle, can I also replace another puzzle?

In this case I feel that in the source code both this puzzle and #160 need to be updated. As you know, updating texts on puzzles will close the existing GitHub issues and create new ones based on the updated text.

**Comment by llorllale** [comment]
My notes:

* Fix typo in `<title>` for `LORM.xsl`
* The text I quoted [here](https://github.com/yegor256/jpeek/issues/111#issuecomment-365633224) makes no sense. I would remove it.
* The "Dynamic analysis of Java program concepts for visualization and profiling" paper (see [here](https://github.com/yegor256/jpeek/issues/111#issuecomment-365651455)) presents several strategies for identifying concepts, basically boiling down to "statically defined in source code" (eg. using annotations), and using actual semantic analysis.
* Taking a cue from the "An Information Retrieval Approach to Concept Location in Source Code" paper (see [here](https://github.com/yegor256/jpeek/issues/111#issuecomment-365651455)), we could use *Latent Semantic Indexing* to analyze the class. As usual, wikipedia's article is rather obtuse; I happen to like the simple explanation offered [here](https://www.searchenginejournal.com/what-is-latent-semantic-indexing-seo-defined/21642/) in the context of SEO. Based on that explanation, I would propose using the class name as the "concept", then treat each method as a distinct document to be analyzed based on their contents to determine their "closeness" to the concept.
* Googling for "java latent semantic indexing" yields a few results for libraries that we could potentially use

**Comment by llorllale** [comment]
@0crat waiting on #192

**Comment by 0crat** [comment]
> @0crat waiting on #192 ([here](https://github.com/yegor256/jpeek/issues/111#issuecomment-366449845))

@llorllale The impediment for [#111](https://github.com/yegor256/jpeek/issues/111) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `15-9a121b89` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@llorllale According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your messages by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@llorllale According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide link to corresponding PR in any of your messages.

**Comment by llorllale** [comment]
@yegor256 since you're the `ARC` I'm addressing this to you:

* PR #197 was merged for advancing research and realizing that we should implement Latent Semantic Indexing on the class methods
* Left puzzle #204 to move the project in the aforementioned direction

**Comment by llorllale** [comment]
@ypshenychka fixed messages, added a new message with the relevant PRs

**Comment by ypshenychka** [comment]
@llorllale Thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+330](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+715](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [204](https://github.com/yegor256/jpeek/issues/204)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [204](https://github.com/yegor256/jpeek/issues/204)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [204](https://github.com/yegor256/jpeek/issues/204)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#502](https://github.com/cqfn/jpeek/issues/502) is still not solved.

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/cqfn/jpeek/issues/111#issuecomment-366953127))

@ypshenychka You @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) need to have one of these roles in order to do "Complete `QA` review": `ARC`, `QA`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
> @0crat waiting on #192 ([here](https://github.com/cqfn/jpeek/issues/111#issuecomment-366449845))

@llorllale Job `gh:cqfn/jpeek#111` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#579](https://github.com/cqfn/jpeek/issues/579) is still not solved; solved: [#502](https://github.com/cqfn/jpeek/issues/502).
