### ISSUE TITLE
LORM.xsl:65-73: `conceptual-relations` are pairs of...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#112]
The puzzle `15-c8802e55` from #15 has to be resolved:

https://github.com/yegor256/jpeek/blob/97a80bf82afb2db0d40171038596a305478a6a2e/src/main/resources/org/jpeek/metrics/LORM.xsl#L65-L73

The puzzle was created by Kapralov Sergey on 26-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#112](https://github.com/yegor256/jpeek/issues/112) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#112](https://github.com/yegor256/jpeek/issues/112) assigned to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rok-povsic** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/112#issuecomment-363709452))

@rok-povsic This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#112](https://github.com/yegor256/jpeek/issues/112) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 12days
  * The role is `DEV`
  * The job is assigned to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic) for [1days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @rok-povsic[/z](https://www.0crat.com/u/rok-povsic) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket

**Comment by 0pdd** [comment]
The puzzle `15-c8802e55` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic), total is [+30](https://www.0crat.com/u/rok-povsic)

**Comment by 0crat** [comment]
The job [#112](https://github.com/yegor256/jpeek/issues/112) is now out of scope

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [160](https://github.com/yegor256/jpeek/issues/160)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [160](https://github.com/yegor256/jpeek/issues/160)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [160](https://github.com/yegor256/jpeek/issues/160)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#503](https://github.com/cqfn/jpeek/issues/503) is still not solved.

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/cqfn/jpeek/issues/112#issuecomment-363709452))

@rok-povsic This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#112](https://github.com/cqfn/jpeek/issues/112) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Acqfn%2Fjpeek%23112%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#580](https://github.com/cqfn/jpeek/issues/580) is still not solved; solved: [#503](https://github.com/cqfn/jpeek/issues/503).
