### ISSUE TITLE
Missing <op> in some cases

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#114]
Some `<op>` are not being included in the skeleton.xml. For example, in the case of class `Bar`, notice how `NAME` is not listed in the ops for method `getKey`:
```java
public final class Bar {
    private final Object key;
    private final Object value;
    private static String singleton = "";
    private static final String NAME = "hey";
   ...
    public Object getKey() {
        Bar.singleton = "bye";
        Bar.NAME.length();
        return this.key;
    }
   ...
}
```
```xml
<method abstract="false"
        ctor="false"
        desc="()Ljava/lang/Object;"
        name="getKey"
        public="true"
        static="false">
   <return>Ljava/lang/Object</return>
   <args/>
   <ops>
      <op code="put_static">singleton</op>
      <op code="get">key</op>
   </ops>
</method>
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#114](https://github.com/yegor256/jpeek/issues/114) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+255](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#114](https://github.com/yegor256/jpeek/issues/114) assigned to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@rok-povsic[/z](https://www.0crat.com/u/rok-povsic) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@rok-povsic[/z](https://www.0crat.com/u/rok-povsic) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by rok-povsic** [comment]
@yegor256 Please close the completed issue.

**Comment by llorllale** [comment]
@rok-povsic closed, thank you

**Comment by rok-povsic** [comment]
@llorllale Thank you. A new issue with the next step has been open [here](https://github.com/yegor256/jpeek/issues/180).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic), total is [+90](https://www.0crat.com/u/rok-povsic)

**Comment by llorllale** [comment]
@rok-povsic yes, I saw, thanks

**Comment by 0crat** [comment]
The job [#114](https://github.com/yegor256/jpeek/issues/114) is now out of scope

**Comment by 0pdd** [comment]
@llorllale the puzzle [#508](https://github.com/cqfn/jpeek/issues/508) is still not solved.
