### ISSUE TITLE
Build fails sometimes because of Ant?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/jpeek#116]
Sometimes, the Travis build fails because of some Ant-related execution scripts. For instance, [this one](https://travis-ci.org/yegor256/jpeek/builds/333888388?utm_source=github_status&utm_medium=notification). What are we using Ant for, in this project?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil that's XCOP and it fails for a good cause -- the header is broken

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#116` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#116](https://github.com/yegor256/jpeek/issues/116) was not in scope
