### ISSUE TITLE
App.java:59-62: TCC metric has impediments (see puzzles...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#117]
The puzzle `9-5e913f6c` from #9 has to be resolved:

https://github.com/yegor256/jpeek/blob/b625770426cbfa670c987c135c0b3c98b7a24c8d/src/main/java/org/jpeek/App.java#L59-L62

The puzzle was created by Kapralov Sergey on 26-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#117](https://github.com/yegor256/jpeek/issues/117) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#117](https://github.com/yegor256/jpeek/issues/117) assigned to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rok-povsic** [comment]
@0pdd Waiting

Until #120 is done, this task cannot be completed.

**Comment by rok-povsic** [comment]
@0crat  Waiting until #120 is done, this task cannot be completed right now.

**Comment by 0crat** [comment]
> @0crat Waiting until #120 is done, this task cannot be completed right now. ([here](https://github.com/yegor256/jpeek/issues/117#issuecomment-364362538))

@rok-povsic The impediment for [#117](https://github.com/yegor256/jpeek/issues/117) was registered successfully by @rok-povsic[/z](https://www.0crat.com/u/rok-povsic)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by rok-povsic** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/117#issuecomment-367778514))

@rok-povsic This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#117](https://github.com/yegor256/jpeek/issues/117) is [in scope](http://www.zerocracy.com/policy.html#14) for 25days
  * The role is `DEV`
  * The job is assigned to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic) for [16days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @rok-povsic[/z](https://www.0crat.com/u/rok-povsic) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23117%27%7D) (restricted area)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
The puzzle `9-5e913f6c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@rok-povsic According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide link to corresponding PR in any of your messages.

**Comment by rok-povsic** [comment]
This ticket was fixed in #214 .

@ypshenychka Done.

**Comment by ypshenychka** [comment]
@rok-povsic thanks!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/117#issuecomment-370352437))

@ypshenychka The job [#117](https://github.com/yegor256/jpeek/issues/117) is now out of scope
