### ISSUE TITLE
colors for metrics

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#12]
Let's add colors to all metrics, to indicate their quality (red, green, yellow).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4110](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#12` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#12` is already assigned to @yegor256, sorry.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4125](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#12` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4245](http://www.0crat.com/u/yegor256).
