### ISSUE TITLE
Differentiate ops that access class attributes from the rest

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#123]
Following on from [this](https://github.com/yegor256/jpeek/issues/98#issuecomment-361256847) comment:

We need a way to differentiate `<op>` that access the class' attributes from other ops that don't. LCOM5 (#18) needs this.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale but we have it already. If an `op` accesses an object attribute it has `type` equal to `put` or `get`.

**Comment by llorllale** [comment]
@yegor256 sorry, did not see it documented anywhere (and didn't look at code). Are the plans to add more types that access attributes? Will fixing #114 involve addint a new `type`?

**Comment by yegor256** [comment]
@llorllale maybe, if new metrics will require them.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#123` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#123](https://github.com/yegor256/jpeek/issues/123) was not in scope
