### ISSUE TITLE
MetricsTest.java:38-40: Impediment: #103 must be fixed...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#124]
The puzzle `18-58649db9` from #18 has to be resolved:

https://github.com/yegor256/jpeek/blob/afff84db718691401c1a47914b387fb171db9564/src/test/java/org/jpeek/MetricsTest.java#L38-L40

The puzzle was created by George Aristy on 27-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#124](https://github.com/yegor256/jpeek/issues/124) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#124](https://github.com/yegor256/jpeek/issues/124) assigned to @rexim[/z](https://www.0crat.com/u/rexim), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/460054633). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@rexim[/z](https://www.0crat.com/u/rexim) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by rexim** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/124#issuecomment-366945895))

@rexim The impediment for [#124](https://github.com/yegor256/jpeek/issues/124) was registered successfully by @rexim[/z](https://www.0crat.com/u/rexim)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
The puzzle `18-58649db9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@rexim According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide link to PR in any of your messages.

**Comment by rexim** [comment]
@ypshenychka this issue was fixed in #207

**Comment by ypshenychka** [comment]
@rexim thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+774](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @rexim[/z](https://www.0crat.com/u/rexim), total is [+275](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/124#issuecomment-368594812))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/124#issuecomment-368637808))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#124](https://github.com/yegor256/jpeek/issues/124) is [in scope](http://www.zerocracy.com/policy.html#14) for 28days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23124%27%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#124](https://github.com/yegor256/jpeek/issues/124) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/581643058). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/124#issuecomment-368948104))

@yegor256 The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#124](https://github.com/yegor256/jpeek/issues/124), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/124#issuecomment-368948126))

@yegor256 The job [#124](https://github.com/yegor256/jpeek/issues/124) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/124#issuecomment-368948126))

@yegor256 Job [#124](https://github.com/yegor256/jpeek/issues/124) was not in scope
