### ISSUE TITLE
Need a logarithm math operation for XSL metrics schemas

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#128]
Working on #17, I realized that MWE metric require a logarithm, an operation which is absent in XSL by default (correct me if I wrong). We need to provide it somehow to the metrics.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral I understand the problem, but you should not create tickets like that. The `master` is not broken now, everything works fine. You just can't implement your functionality, because `log()` is absent. You should use PDD.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#128` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#128](https://github.com/yegor256/jpeek/issues/128) was not in scope
