### ISSUE TITLE
MWE: Need to introduce a way to gather information about topics and their probability from sources

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#129]
Original metric: #17.
See also #110.

http://www.cs.wm.edu/~denys/pubs/ICSM09-LDA-cohesion.pdf

> To apply LDA on source code, we consider a software system as a collection of documents (i.e., methods) and each document is associated with a set of concepts (i.e., topics). The mapping between LDA model and source code entities is shown in Table 1. This mapping was used before [35], however, we refine it to account for fine grain source code elements, such as methods and classes. Once we generate a corpus for a software system, we can apply LDA to extract a set of topics and their distributions among different documents (i.e., methods) in the corpus (i.e., software system). The details on specific settings of applying LDA to source code are summarized in section 4.2.2.

Information about the LDA topics and their probability per class methods is used as a basis for MWE metric. We need to collect this information from class sources.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral what is "topic" and "their probability"? I can't understand. Isn't it a duplicate of https://github.com/yegor256/jpeek/issues/110

**Comment by skapral** [comment]
"topic" and its probability is the basis input for MWE metric (and, probably, the other conceptual related metrics). I think that following the precedence of #128, we should close this issue and leave a puzzle in #130 instead.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#129` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#129](https://github.com/yegor256/jpeek/issues/129) was not in scope
