### ISSUE TITLE
Mention installation of xcop in CONTRIBUTION.md?

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#131]
I fixed a bug and checked the fix by building with `-Pqulice` profile, according CONRIBUTION.md. Everything passed correctly.

Then I pushed my changes and created a Pull Request. Travis started complaining on one of my XMLs (a metric descriptor). It took me a while to understand that my build is passed locally because `xcop` tool was not installed on my host. It significantly impacted my timings.

I propose one of two solutions below:
1. Either update CONTRIBUTION.md with information about supplementary tools which should be installed.
2. Or close this issue and create a new one on Qulice: to fail the build if xcop and other dependencies needed for Qulice are not installed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral thanks, I explained it

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#131` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#131](https://github.com/yegor256/jpeek/issues/131) was not in scope
