### ISSUE TITLE
Explain the XLS templates

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/jpeek#132]
I see most of the metrics are implemented in XLS and processed with ``skeletom.xml``? 

Can you pls explain such an XLS template? I see most declare variables (e.g. ``<xsl:variable name="Oi">``, inside `` <xsl:template>``, so I assume all that has to be done in a new metric is declare the variables used by said metric, inside the right template, but I am not sure.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@skapral Maybe you can ask Yegor to assign this to you. I guess this explanation should remain in this ticket for everyone to see. Surely, I am not the only one who is not familiar with XSL :)

**Comment by skapral** [comment]
@amihaiemil @yegor256

Actually, I created something similar once ago (#105) and I don't know what to add besides that. XSL templates are just XSL templates which transition one XML (skeleton.xml) to the other (<metric>.XML). There is completely no sacral meaning in its variable names and templates. However, I have no idea how to make them more readable.

in my pull request (#130) I used the names from the formula, located in the description. The almost similar names were used in the article describing the metric. I could name it differently without impacting the semantics - if you think that my naming is not transparent enough, don't hesitate to give me a remark there (but I would really appreciate a concrete proposal).

However, sacral meaning has the input skeleton.xml and resulting <metric>.xml. For transparency, it would worth creating a schema with documenting annotations for them (#133).

**Comment by amihaiemil** [comment]
@skapral No, this ticket was not about your PRs, they are fine from my point of view. I wanted an explanation so I can understand how to implement metrics with XSL :)

**Comment by yegor256** [comment]
@amihaiemil you need this book: http://amzn.to/2GyG3en

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#132` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#132](https://github.com/yegor256/jpeek/issues/132) was not in scope
