### ISSUE TITLE
Introduce a schemas for skeleton.xml and <metric>.xml's

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#133]
Subj. The proposal is to introduce XML schemas with documentation annotations for the purpose of validation and transparency.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral but we do have them already, see `src/resources/org/jpeek/xsd`

**Comment by skapral** [comment]
@yegor256 I see, but:
1. Shouldn't we reference them in generated XML's?
2. There is no documentation there

**Comment by yegor256** [comment]
@skapral both concerns are valid, but they have to be submitted as separate tickets and we will fix them.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#133` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#133](https://github.com/yegor256/jpeek/issues/133) was not in scope
