### ISSUE TITLE
Schemas in src/resources/org/jpeek/xsd must be documented

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#134]
Subj. First discussed in #133. We need to document the schemas in src/resources/org/jpeek/xsd so that the semantics of the generated XML documents is transparent for maintainers.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#134](https://github.com/yegor256/jpeek/issues/134) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @skapral[/z](https://www.0crat.com/u/skapral), total is [+90](https://www.0crat.com/u/skapral)

**Comment by 0crat** [comment]
The job [#134](https://github.com/yegor256/jpeek/issues/134) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/461926470). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@skapral documentation of `skeleton.xsd` was done in #189 and puzzles left for `metric.xsd`, `matrix.xsd`, and `index.xsd` (#201, #200, and #199 respectively)

can we close this?

**Comment by skapral** [comment]
ok

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+105](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was successfully finished: +35 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+605](https://www.0crat.com/u/llorllale)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/134#issuecomment-366701380))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#134](https://github.com/yegor256/jpeek/issues/134) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23134%27%7D) (restricted area)

**Comment by 0pdd** [comment]
@skapral 3 puzzles [#200](https://github.com/yegor256/jpeek/issues/200), [#201](https://github.com/yegor256/jpeek/issues/201), [#282](https://github.com/yegor256/jpeek/issues/282) are still not solved; solved: [#199](https://github.com/yegor256/jpeek/issues/199).

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#200](https://github.com/yegor256/jpeek/issues/200), [#282](https://github.com/yegor256/jpeek/issues/282) are still not solved; solved: [#199](https://github.com/yegor256/jpeek/issues/199), [#201](https://github.com/yegor256/jpeek/issues/201).

**Comment by 0pdd** [comment]
@skapral the puzzle [#200](https://github.com/yegor256/jpeek/issues/200) is still not solved; solved: [#199](https://github.com/yegor256/jpeek/issues/199), [#201](https://github.com/yegor256/jpeek/issues/201), [#282](https://github.com/yegor256/jpeek/issues/282).

**Comment by 0pdd** [comment]
@skapral the puzzle [#505](https://github.com/cqfn/jpeek/issues/505) is still not solved.

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/cqfn/jpeek/issues/134#issuecomment-366701380))

@yegor256 This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#134](https://github.com/cqfn/jpeek/issues/134) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Acqfn%2Fjpeek%23134%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/cqfn/jpeek/issues/134#issuecomment-366695611))

@ypshenychka You @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) need to have one of these roles in order to do "Complete `QA` review": `ARC`, `QA`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@skapral the only puzzle [#505](https://github.com/cqfn/jpeek/issues/505) is solved here.
