### ISSUE TITLE
Schemas from src/resources/org/jpeek/xsd must be referenced in generated XMLs

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#135]
Subj. First discussed in #133.

We need to make references to the schemas explicit in generated XML documents. This will bring transparency in semantics of the generated XML files and will make their support easier.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#135](https://github.com/yegor256/jpeek/issues/135) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @skapral[/z](https://www.0crat.com/u/skapral), total is [+105](https://www.0crat.com/u/skapral)

**Comment by 0crat** [comment]
The job [#135](https://github.com/yegor256/jpeek/issues/135) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/461952118). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@yegor256 can I take the liberty to define namespaces for these schemas? I was thinking of using this for metric.xsd: `http://www.jpeek.org/2018/schema/metric`

**Comment by llorllale** [comment]
My notes:
* [Importing Schemas with No Namespaces](https://docstore.mik.ua/orelly/xml/schema/ch10_09.htm)

**Comment by yegor256** [comment]
@llorllale let's use the schema without a namespace, it will be easier for everything

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/135#issuecomment-366724531))

@llorllale This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#135](https://github.com/yegor256/jpeek/issues/135) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 19days
  * The role is `DEV`
  * The job is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale) for [4days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @llorllale[/z](https://www.0crat.com/u/llorllale) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @skapral[/z](https://www.0crat.com/u/skapral): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23135%27%7D) (restricted area)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/135#issuecomment-368109284))

@llorllale The impediment for [#135](https://github.com/yegor256/jpeek/issues/135) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@yegor256 can we close this?

* Reference to `metric.xsd` in `metric.xml` was added in PR #196)
* Puzzle #227 left to refactor the above towards a simpler solution
* Puzzles #224, #225, and #226 left for adding references to the rest of the XSDs

**Comment by yegor256** [comment]
@llorllale thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@skapral 3 puzzles [#224](https://github.com/yegor256/jpeek/issues/224), [#226](https://github.com/yegor256/jpeek/issues/226), [#227](https://github.com/yegor256/jpeek/issues/227) are still not solved; solved: [#225](https://github.com/yegor256/jpeek/issues/225).

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#224](https://github.com/yegor256/jpeek/issues/224), [#227](https://github.com/yegor256/jpeek/issues/227) are still not solved; solved: [#225](https://github.com/yegor256/jpeek/issues/225), [#226](https://github.com/yegor256/jpeek/issues/226).

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#224](https://github.com/yegor256/jpeek/issues/224), [#327](https://github.com/yegor256/jpeek/issues/327) are still not solved; solved: [#225](https://github.com/yegor256/jpeek/issues/225), [#226](https://github.com/yegor256/jpeek/issues/226), [#227](https://github.com/yegor256/jpeek/issues/227).

**Comment by 0pdd** [comment]
@skapral the puzzle [#327](https://github.com/yegor256/jpeek/issues/327) is still not solved; solved: [#224](https://github.com/yegor256/jpeek/issues/224), [#225](https://github.com/yegor256/jpeek/issues/225), [#226](https://github.com/yegor256/jpeek/issues/226), [#227](https://github.com/yegor256/jpeek/issues/227).
