### ISSUE TITLE
MMAC

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#14]
Let's add MMAC cohesion metric.

 J. Al Dallal and L. C. Briand, “An object-oriented high-level
design-based class cohesion metric,” Information and software
technology, vol. 52, no. 12, pp. 1346–1361, 2010.

PDF is not available for free :( More about this metric here: http://www.math.md/files/csjm/v25-n1/v25-n1-(pp44-74).pdf

http://www.sciencedirect.com/science/article/pii/S0950584910001552

**Comment by sergey-karazhenets** [comment]
Also info about MMAC metric you can find here http://waset.org/publications/5239/a-design-based-cohesion-metric-for-object-oriented-classes

**Comment by yegor256** [comment]
@sergey-karazhenets please, don't forget to update README

**Comment by yegor256** [comment]
@sergey-karazhenets also, please put the PDF file into `papers` folder

**Comment by sergey-karazhenets** [comment]
@yegor256 yes, I've updated README and added PDF to papers

**Comment by yegor256** [comment]
@rultor release, tag is `0.11`

**Comment by yegor256** [comment]
@sergey-karazhenets many thanks for your contribution!

**Comment by memoyil** [comment]
@yegor256 You can close this issue.

**Comment by yegor256** [comment]
@sergey-karazhenets thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#14`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#14` is not in scope.
