### ISSUE TITLE
App.java:69-72: MWE metric has impediments (see puzzles...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#143]
The puzzle `17-e0265053` from #17 has to be resolved:

https://github.com/yegor256/jpeek/blob/6fb7f028b1daed1d927f22e36b95dfdb70cb117b/src/main/java/org/jpeek/App.java#L69-L72

The puzzle was created by Kapralov Sergey on 30-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#143](https://github.com/yegor256/jpeek/issues/143) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#143](https://github.com/yegor256/jpeek/issues/143) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/581701151). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@yegor256 this is another job that has impediments declared upfront, they're all still open, and there's nothing to do with this puzzle right now. To avoid this in the future, perhaps `REV` can check to make sure puzzles like this one are not left behind in the source.

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/143#issuecomment-368958597))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#143](https://github.com/yegor256/jpeek/issues/143), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/143#issuecomment-368958597))

@llorllale Job `gh:yegor256/jpeek#143` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+865](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Mistake of @llorllale[/z](https://www.0crat.com/u/llorllale)[/z](https://www.0crat.com/u/llorllale) (your student): Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10964](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#143](https://github.com/yegor256/jpeek/issues/143) assigned to @izrik[/z](https://www.0crat.com/u/izrik), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1021465700); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@izrik[/z](https://www.0crat.com/u/izrik) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @izrik[/z](https://www.0crat.com/u/izrik) resigned from [#143](https://github.com/yegor256/jpeek/issues/143), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @izrik[/z](https://www.0crat.com/u/izrik)

**Comment by 0crat** [comment]
The job [#143](https://github.com/yegor256/jpeek/issues/143) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1350818902); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
> @0crat wait #232 ([here](https://github.com/yegor256/jpeek/issues/143#issuecomment-390016868))

@uurl The impediment for [#143](https://github.com/yegor256/jpeek/issues/143) was registered successfully by @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by uurl** [comment]
@0crat wait #240

**Comment by 0crat** [comment]
> @0crat wait #240 ([here](https://github.com/yegor256/jpeek/issues/143#issuecomment-390440523))

@uurl Job [#143](https://github.com/yegor256/jpeek/issues/143) is already on hold

**Comment by uurl** [comment]
@yegor256 this issue is solved with the PR #247.
While you don't close it, I can't receive more jobs.

**Comment by 0pdd** [comment]
The puzzle `17-e0265053` has disappeared from the source code, that's why I closed this issue.

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
