### ISSUE TITLE
MWE.xsl:47-52: The current implementation of MWE metric...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#144]
The puzzle `17-049820b6` from #17 has to be resolved:

https://github.com/yegor256/jpeek/blob/6fb7f028b1daed1d927f22e36b95dfdb70cb117b/src/main/resources/org/jpeek/metrics/MWE.xsl#L47-L52

The puzzle was created by Kapralov Sergey on 30-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#144](https://github.com/yegor256/jpeek/issues/144) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#144](https://github.com/yegor256/jpeek/issues/144) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/581831056). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#144` already assigned to @llorllale, can't assign to @llorllale

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-370426461))

@llorllale You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-370426461))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#144](https://github.com/yegor256/jpeek/issues/144), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#144](https://github.com/yegor256/jpeek/issues/144) assigned to @izrik[/z](https://www.0crat.com/u/izrik), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1121464573); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@izrik[/z](https://www.0crat.com/u/izrik) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by izrik** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-385139730))

@izrik The user @izrik[/z](https://www.0crat.com/u/izrik) resigned from [#144](https://github.com/yegor256/jpeek/issues/144), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @izrik[/z](https://www.0crat.com/u/izrik)

**Comment by 0crat** [comment]
The job [#144](https://github.com/yegor256/jpeek/issues/144) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1350823006); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by uurl** [comment]
@0crat wait #232

**Comment by 0crat** [comment]
> @0crat wait #232 ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-390268513))

@uurl The impediment for [#144](https://github.com/yegor256/jpeek/issues/144) was registered successfully by @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by uurl** [comment]
@0crat wait #241

**Comment by 0crat** [comment]
> @0crat wait #241 ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-390440553))

@uurl Job [#144](https://github.com/yegor256/jpeek/issues/144) is already on hold

**Comment by uurl** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-392072647))

@uurl This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#144](https://github.com/yegor256/jpeek/issues/144) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @uurl[/z](https://www.0crat.com/u/uurl) for [10days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @uurl[/z](https://www.0crat.com/u/uurl) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @llorllale[/z](https://www.0crat.com/u/llorllale): User was resigned from the ticket
    * @izrik[/z](https://www.0crat.com/u/izrik): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23144%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by uurl** [comment]
@0crat wait #244

**Comment by 0crat** [comment]
> @0crat wait #244 ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-392118730))

@uurl Job [#144](https://github.com/yegor256/jpeek/issues/144) is already on hold

**Comment by uurl** [comment]
@yegor256 please close this with #244

**Comment by uurl** [comment]
@yegor256 this issue was solved with PR #244 
I can't receive more jobs if you don't close it.

**Comment by uurl** [comment]
@0crat close with #244

**Comment by 0crat** [comment]
> @0crat close with #244  ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-396718406))

@uurl Can't understand "close", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by uurl** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/144#issuecomment-396720088))

@uurl This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#144](https://github.com/yegor256/jpeek/issues/144) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @uurl[/z](https://www.0crat.com/u/uurl) for [29days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @uurl[/z](https://www.0crat.com/u/uurl) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @llorllale[/z](https://www.0crat.com/u/llorllale): User was resigned from the ticket
    * @izrik[/z](https://www.0crat.com/u/izrik): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23144%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by yegor256** [comment]
@uurl the issue is still open. This is most likely because you didn't remove the puzzle form the code.

**Comment by 0pdd** [comment]
The puzzle `17-049820b6` has disappeared from the source code, that's why I closed this issue.

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
