### ISSUE TITLE
MWE.xsl:75-79: Di value is supposed to be calculated by...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#145]
The puzzle `17-f82757ae` from #17 has to be resolved:

https://github.com/yegor256/jpeek/blob/6fb7f028b1daed1d927f22e36b95dfdb70cb117b/src/main/resources/org/jpeek/metrics/MWE.xsl#L75-L79

The puzzle was created by Kapralov Sergey on 30-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#145](https://github.com/yegor256/jpeek/issues/145) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#145](https://github.com/yegor256/jpeek/issues/145) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/581703219). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@0crat waiting for review on PR #221

**Comment by 0crat** [comment]
> @0crat waiting for review on PR #221 ([here](https://github.com/yegor256/jpeek/issues/145#issuecomment-369596916))

@llorllale The impediment for [#145](https://github.com/yegor256/jpeek/issues/145) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `17-f82757ae` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#145](https://github.com/yegor256/jpeek/issues/145) is now out of scope
