### ISSUE TITLE
App.java:122-124: Add the CCM metric report here when all...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#146]
The puzzle `66-9d79a0db` from #66 has to be resolved:

https://github.com/yegor256/jpeek/blob/faea600f44b8a750701047afee520df9bdbeb3a1/src/main/java/org/jpeek/App.java#L122-L124

The puzzle was created by George Aristy on 01-Feb-18. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#146](https://github.com/yegor256/jpeek/issues/146) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#146](https://github.com/yegor256/jpeek/issues/146) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/591359165). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/146#issuecomment-370426574))

@llorllale You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/146#issuecomment-370426574))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#146](https://github.com/yegor256/jpeek/issues/146), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#146](https://github.com/yegor256/jpeek/issues/146) assigned to @izrik[/z](https://www.0crat.com/u/izrik), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1121509714); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by izrik** [comment]
@0crat wait for #147 and #148 and #149

**Comment by 0crat** [comment]
> @0crat wait for #147 and #148 and #149 ([here](https://github.com/yegor256/jpeek/issues/146#issuecomment-383800956))

@izrik The impediment for [#146](https://github.com/yegor256/jpeek/issues/146) was registered successfully by @izrik[/z](https://www.0crat.com/u/izrik)

**Comment by 0crat** [comment]
The job [#146](https://github.com/yegor256/jpeek/issues/146) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1371365379); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat waiting for #147 and #148 and #149

**Comment by 0crat** [comment]
> @0crat waiting for #147 and #148 and #149  ([here](https://github.com/yegor256/jpeek/issues/146#issuecomment-392276615))

@pbenety The impediment for [#146](https://github.com/yegor256/jpeek/issues/146) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0pdd** [comment]
The puzzle `66-9d79a0db` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#146](https://github.com/yegor256/jpeek/issues/146) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
