### ISSUE TITLE
CCM.xsl:63-67: For CCM, need to add OR condition to the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#149]
The puzzle `66-72fdfc23` from #66 has to be resolved:

https://github.com/yegor256/jpeek/blob/faea600f44b8a750701047afee520df9bdbeb3a1/src/main/resources/org/jpeek/metrics/CCM.xsl#L63-L67

The puzzle was created by George Aristy on 01-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#149](https://github.com/yegor256/jpeek/issues/149) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#149](https://github.com/yegor256/jpeek/issues/149) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/601500264). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/149#issuecomment-370427187))

@llorllale You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/149#issuecomment-370427187))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#149](https://github.com/yegor256/jpeek/issues/149), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/149#issuecomment-370427187))

@llorllale You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/149#issuecomment-370427187))

@llorllale Job `gh:yegor256/jpeek#149` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#149](https://github.com/yegor256/jpeek/issues/149) assigned to @oridan[/z](https://www.0crat.com/u/oridan), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1371445434); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@oridan[/z](https://www.0crat.com/u/oridan) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by oridan** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/149#issuecomment-392332372))

@oridan The user @oridan[/z](https://www.0crat.com/u/oridan) resigned from [#149](https://github.com/yegor256/jpeek/issues/149), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0crat** [comment]
The job [#149](https://github.com/yegor256/jpeek/issues/149) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1481147294); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@20719cfd

**Comment by 0crat** [comment]
@uurl[/z](https://www.0crat.com/u/uurl) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by uurl** [comment]
@0crat wait #255

**Comment by 0crat** [comment]
> @0crat wait #255 ([here](https://github.com/yegor256/jpeek/issues/149#issuecomment-394582104))

@uurl The impediment for [#149](https://github.com/yegor256/jpeek/issues/149) was registered successfully by @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0pdd** [comment]
The puzzle `66-72fdfc23` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @uurl[/z](https://www.0crat.com/u/uurl), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#149](https://github.com/yegor256/jpeek/issues/149) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by elenavolokhova** [comment]
@0crat status
