### ISSUE TITLE
LORM

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#15]
Let's implement LORM metric.

L. Etzkorn and H. Delugach, “Towards a semantic metrics suite
for object-oriented design,” in Technology of Object-Oriented Languages
and Systems, 2000. TOOLS 34. Proceedings. 34th International
Conference on. IEEE, 2000, pp. 71–80.

No PDF available :(

http://ieeexplore.ieee.org/document/868960/

It's explained here, briefly: http://www.math.md/files/csjm/v25-n1/v25-n1-(pp44-74).pdf

**Comment by t-izbassar** [comment]
Hello,

so how we define 

> set of concepts

of method? Can we assume that it is all local and class variables? And if two methods use the same field of the class we can collect it is as _conceptual relation_ between methods? Do we adding static method calls to that?

Overall, it is an interesting metric. It is suppose to show the correlated methods with each other. Another interesting thing is - how much does it related to quality?

**Comment by 0crat** [comment]
Job [#15](https://github.com/yegor256/jpeek/issues/15) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7225](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#15](https://github.com/yegor256/jpeek/issues/15) assigned to @allanws[/z](http://www.0crat.com/u/allanws). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by allanws** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/15#issuecomment-357827940))

@allanws @allanws[/z](http://www.0crat.com/u/allanws) resigned from [#15](https://github.com/yegor256/jpeek/issues/15), please stop working

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://datum.zerocracy.com/pages/policy.html#6): -15 points just awarded to @allanws[/z](http://www.0crat.com/u/allanws), total is [+90](http://www.0crat.com/u/allanws)

**Comment by 0crat** [comment]
The job [#15](https://github.com/yegor256/jpeek/issues/15) assigned to @flslkxtc[/z](http://www.0crat.com/u/flslkxtc). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The job [#15](https://github.com/yegor256/jpeek/issues/15) assigned to @skapral[/z](https://www.0crat.com/u/skapral). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by skapral** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/15#issuecomment-360220329))

@skapral This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#15](https://github.com/yegor256/jpeek/issues/15) is in scope for 10days
  * The role is `DEV`
  * The job is assigned to @skapral[/z](https://www.0crat.com/u/skapral) for 1days
  * These users are banned: @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket; @allanws[/z](https://www.0crat.com/u/allanws): User was resigned from the ticket; @flslkxtc[/z](https://www.0crat.com/u/flslkxtc): User was resigned from the ticket

**Comment by skapral** [comment]
@yegor256 the pull request is merged, the puzzlels are created so I consider this done. Do you agree? Would you please close this issue?

**Comment by skapral** [comment]
@0crat status

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/15#issuecomment-361005037). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by skapral** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/15#issuecomment-361005106))

@skapral This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#15](https://github.com/yegor256/jpeek/issues/15) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 13days
  * The role is `DEV`
  * The job is assigned to @skapral[/z](https://www.0crat.com/u/skapral) for [4days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @allanws[/z](https://www.0crat.com/u/allanws): User was resigned from the ticket
    * @flslkxtc[/z](https://www.0crat.com/u/flslkxtc): User was resigned from the ticket

**Comment by skapral** [comment]
@yegor256 ?

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@skapral thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @skapral[/z](https://www.0crat.com/u/skapral), total is [+75](https://www.0crat.com/u/skapral)

**Comment by 0crat** [comment]
The job [#15](https://github.com/yegor256/jpeek/issues/15) is now out of scope
