### ISSUE TITLE
Path /dev/null not found on Windows

### ISSUE THREAD

**Issue by rok-povsic** [yegor256/jpeek#151]
Because path `/dev/null` is used [here](https://github.com/yegor256/jpeek/blob/faea600f44b8a750701047afee520df9bdbeb3a1/src/main/java/org/jpeek/web/Reports.java#L121), an IOException is thrown (and swallowed) when running the test `TkAppTest:rendersOneReport` on Windows.

This stack trace is below is written to the output window. The test otherwise passes. All other tests also pass, without outputting any stack traces or other logs.

```
Futures-1 com.jcabi.log.VerboseCallable: swallowed exception: java.io.IOException: Cannot run program "unzip" (in directory "C:\Users\rok\AppData\Local\Temp\x2864671055049887563\sources\org\jpeek\jpeek"): \dev\null (The system cannot find the file specified)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jpeek.web.Reports.apply(Reports.java:128)
	at org.jpeek.web.Reports.apply(Reports.java:51)
	at org.jpeek.web.Futures.lambda$apply$0(Futures.java:105)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:179)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: \dev\null (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.lang.ProcessImpl.start(ProcessImpl.java:112)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#151](https://github.com/yegor256/jpeek/issues/151) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#151](https://github.com/yegor256/jpeek/issues/151) assigned to @oridan[/z](https://www.0crat.com/u/oridan), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1480790695); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@5a27ede6

**Comment by 0crat** [comment]
@oridan[/z](https://www.0crat.com/u/oridan) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by oridan** [comment]
@0crat wait PR #254.

**Comment by 0crat** [comment]
> @0crat wait PR #254. ([here](https://github.com/yegor256/jpeek/issues/151#issuecomment-394700172))

@oridan The impediment for [#151](https://github.com/yegor256/jpeek/issues/151) was registered successfully by @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by oridan** [comment]
@yegor256 PR #254 was successfully merged. Please close this ticket.

**Comment by yegor256** [comment]
@oridan it's not mine :)

**Comment by oridan** [comment]
@rok-povsic could you please close this issue?

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @oridan[/z](https://www.0crat.com/u/oridan), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#151](https://github.com/yegor256/jpeek/issues/151) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
