### ISSUE TITLE
Main.java:104-107: The logic for overwriting the target...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#154]
The puzzle `104-9f730941` from #104 has to be resolved:

https://github.com/yegor256/jpeek/blob/bcab016ee68717091fd0b8345e78f507cade036c/src/main/java/org/jpeek/Main.java#L104-L107

The puzzle was created by George Aristy on 04-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#154](https://github.com/yegor256/jpeek/issues/154) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#154](https://github.com/yegor256/jpeek/issues/154) assigned to @oridan[/z](https://www.0crat.com/u/oridan), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1550839063); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@oridan[/z](https://www.0crat.com/u/oridan) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by oridan** [comment]
@0crat wait PR #258.

**Comment by 0crat** [comment]
> @0crat wait PR #258. ([here](https://github.com/yegor256/jpeek/issues/154#issuecomment-396720771))

@oridan The impediment for [#154](https://github.com/yegor256/jpeek/issues/154) was registered successfully by @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0pdd** [comment]
The puzzle `104-9f730941` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @oridan[/z](https://www.0crat.com/u/oridan), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#154](https://github.com/yegor256/jpeek/issues/154) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
