### ISSUE TITLE
README.md misses information on how to deploy jpeek as a web application

### ISSUE THREAD

**Issue by skapral** [yegor256/jpeek#162]
Taking into account the issues like #57, it seems that the current documentation of JPeek misses any information on how to use it as a web service. This issue is proposal to fit this gap.

README.md should describe a way to deploy JPeek locally or as a user-controlled heroku application, including all prerequisites for it (dynamodb key/secret? sentry?) explicitly.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#162](https://github.com/yegor256/jpeek/issues/162) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @skapral[/z](https://www.0crat.com/u/skapral), total is [+180](https://www.0crat.com/u/skapral)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9430](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@skapral explained in b57f576 Good enough?

**Comment by skapral** [comment]
@yegor256 To be honest, I don't know. Probably this would be enough for a person who is experienced in DynamoDB, but for a newbie it is certainly not. And IMO it is not fair to expect Amazon amateur in a sandbox 0crat project, to where any noob is supposed to join in. I am not experienced in DynamoDB so I am not the right guy to comment on this.

As a complete noob in DynamoDB, I tried out the procedure. And ended up with exception on start page, saying that:
```
Caused by: com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found: Table: jpeek-results not found
```
It will take me a while before I'll get the root cause of it. Generally, it is a sign of not very good deployment procedure. But on the other hand it is hard to argue against "this is not a school" principle.

**Comment by yegor256** [comment]
@skapral we are not expecting a newbie to deploy this project to a new platform. I don't actually see why that would be necessary...

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by skapral** [comment]
@yegor256 Ok, no objections besides this. At least crucial stuff is described (DynamoDB schema), so I am ok with passing it.

**Comment by yegor256** [comment]
@skapral please, close the ticket

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@0crat quality acceptable.
No associated PR is created.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/162#issuecomment-366796247). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+135](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/162#issuecomment-366796327))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor236[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Paypal[122] java.io.IOException: Failed to pay $12.50 to yegor@tpc2.com with memo "Payment for gh:yegor256/jpeek#162 (30 minutes): Order was finished, quality was "acceptable""
com.zerocracy.pmo.banks.Paypal[201] java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The sender and each receiver must have different accounts]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10199](https://www.0crat.com/u/yegor256)
