### ISSUE TITLE
The way the metric tests are set up is broken: slows down development of the project as a whole

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#164]
**Problem**
We're currently adding all tests for all metrics inside the same test fixture in `MetricsTest`. This can unnecessarily create coupling between tests which then turns into impediments.

Example 1:
The [job](https://github.com/yegor256/jpeek/issues/93) asking for implementation of NHD. The [decision](https://github.com/yegor256/jpeek/issues/102) was made to use a certain value that happens to be incompatible with the current test fixture. A [puzzle](https://github.com/yegor256/jpeek/issues/121) was left to add those test cases later. This puzzle shouldn't have been required in the first place if the tests would've been implemented separately.

Example 2:
Adding [method-method interactions](https://github.com/yegor256/jpeek/issues/106) is introducing extra `<op>` which consequently breaks some existing tests, leading one to then have to create a puzzle to fix those later.

[EDIT]
Another symptom of this problem is that I keep having to constantly solve merge conflicts on my PRs long after I initially delivered them

**Proposal**
Let's separate tests for each metric. Each metric can have its own test class (eg. `NhdTest`) with its own `@Test` methods. Each metric should also have its own set of test resources in its own folder, separate from the rest (eg. `org.jpeek.samples.nhd`). 

Any reusable test functionality could be refactored into its own "helper" class in the test packages.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by llorllale** [comment]
@yegor256 WDYT?

**Comment by llorllale** [comment]
Someone in another issue explained a few of the guiding principles of this project's management to me and I've now come to realize that most of the problems described in this issue is beyond the scope of my role in this project, so I'm closing this.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#164` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#164](https://github.com/yegor256/jpeek/issues/164) was not in scope

**Comment by yegor256** [comment]
@llorllale you can submit bugs no matter what is your role. This ticket was a good one, but I would not accept it anyway, since I think our current configuration of tests is good enough. But, again, don't hesitate to submit bugs -- you have nothing to lose. If they are accepted, you earn. If they are not, you just move on.
