### ISSUE TITLE
README.md missing static code analysis cmd & link leading to non-existing URL

### ISSUE THREAD

**Issue by rok-povsic** [yegor256/jpeek#165]
Two issues with README.md

1) It does not say how to statically check the code. Add the `mvn clean install -Pqulice` instruction.

2) The link in [How to contribute](https://github.com/yegor256/jpeek#how-to-contribute) returns 404.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rok-povsic fixed in 7047e58 thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#165` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#165](https://github.com/yegor256/jpeek/issues/165) was not in scope
