### ISSUE TITLE
App.java:127-131: The skeleton for each Report is...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#166]
The puzzle `100-e0c9e789` from #100 has to be resolved:

https://github.com/yegor256/jpeek/blob/558a63f04849f953fae8ebe5e1e76fc367d7e148/src/main/java/org/jpeek/App.java#L127-L131

The puzzle was created by Mihai Andronache on 10-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#166](https://github.com/yegor256/jpeek/issues/166) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#166](https://github.com/yegor256/jpeek/issues/166) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/420711897). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9635](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
The puzzle `100-e0c9e789` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
java.lang.reflect.InvocationTargetException: null
java.io.IOException: Failed to pay $12.50 to yegor@tpc2.com with memo "Payment for gh:yegor256/jpeek#166 (30 minutes): Order was successfully finished"
java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The sender and each receiver must have different accounts]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

cc @yegor256

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9665](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#166](https://github.com/yegor256/jpeek/issues/166) is now out of scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.25`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
