### ISSUE TITLE
MetricsTest is broken: updates frequently force me to resolve conflicts on PRs I've already delivered

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#169]
**Problem**
We're currently adding all tests for all metrics inside the same test fixture in MetricsTest. This  tends to create conflicts when merging PRs, forcing me to do additional work on my PRs every time some other PR gets merged which modifies this file, especially the test parameters.

**Proposal**
Let's separate tests for each metric. Each metric can have its own test class (eg. `NhdTest`) with its own `@Test` methods. Each metric should also have its own set of test resources in its own folder, separate from the rest (eg. `org.jpeek.samples.nhd`).

Any reusable test functionality could be refactored into its own "helper" class in the test packages.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale how will this separation of tests help in resolving merge conflicts? You will still have conflicts between your branches and the changes introduces by other developers... I feel that we will only have a lot of code duplication if go that way. Don't you think?

**Comment by llorllale** [comment]
@yegor256 
> how will this separation of tests help in resolving merge conflicts?

I keep having to constantly go back and solve conflicts in method `MetricsTest.targets()`, which as of this moment has 50 lines.

> code duplication

Extract a class from `MetricsTest.testsTarget()`. Perhaps something that would look like

```java
new Metric(xml, metric, value).test();
```

**Comment by yegor256** [comment]
@llorllale let's keep it on hold for a while. I don't think this list of lines will be changed frequently, since most of the metrics are stable now.

**Comment by llorllale** [comment]
Happening in #168

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#169` is not assigned, can't get performer
