### ISSUE TITLE
Build is broken: pdd failing when parsing PDFs

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#170]
See rultor's log [here](http://www.rultor.com/t/13816-364922513) for PR #153.

The error is:

> Reading papers/henderson96.pdf...
31mERROR0m: papers/henderson96.pdf; puzzle at line #2; invalid byte sequence in UTF-8. If you can't understand the cause of this issue or you don't know how to fix it, please submit a GitHub issue, we will try to help you: https://github.com/yegor256/pdd/issues. This tool is still in its beta version and we will appreciate your feedback. Here is where you can find more documentation: https://github.com/yegor256/pdd/blob/master/README.md.
Exit code is 1

PR #153 did not modify file `henderson96.pdf` in any way.

Shouldn't the `papers` directory be ignored by `pdd` anyway?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale fixed in a9913a1

**Comment by 0crat** [comment]
The job [#170](https://github.com/yegor256/jpeek/issues/170) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/431526395). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+525](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9690](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
java.lang.reflect.InvocationTargetException: null
java.io.IOException: Failed to pay $12.50 to yegor@tpc2.com with memo "Payment for gh:yegor256/jpeek#170 (30 minutes): Order was successfully finished"
java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The sender and each receiver must have different accounts]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

cc @yegor256

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9720](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#170](https://github.com/yegor256/jpeek/issues/170) is now out of scope
