### ISSUE TITLE
Ignore bridge methods

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/jpeek#171]
Let's try to calc LCOM2 on [`Reports.java`](https://github.com/yegor256/jpeek/blob/master/src/main/java/org/jpeek/web/Reports.java):
```xml
<class color="yellow" element="true" id="Reports" value="0.5">
    <vars>
       <var id="methods">2</var>
       <var id="attributes">2</var>
   </vars>
</class>
```
But in class `Reports` only one method: [`apply`](https://github.com/yegor256/jpeek/blob/master/src/main/java/org/jpeek/web/Reports.java#L83-L158).

Let's see the `skeleton.xml`:
```xml
...
<method abstract="false"
        ctor="false"
        desc="(Ljava/lang/String;Ljava/lang/String;)Lorg/cactoos/Func;"
        name="apply"
        public="true"
        static="false">
   <return>Lorg/cactoos/Func</return>
   <args>
      <arg type="Ljava/lang/String">?</arg>
      <arg type="Ljava/lang/String">?</arg>
   </args>
   <ops>
      <op code="get">sources</op>
      <op code="get">target</op>
      <op code="get">sources</op>
   </ops>
</method>
<method abstract="false"
        ctor="false"
        desc="(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"
        name="apply"
        public="true"
        static="false">
   <return>Ljava/lang/Object</return>
   <args>
      <arg type="Ljava/lang/Object">?</arg>
      <arg type="Ljava/lang/Object">?</arg>
   </args>
</method>
...
```

There is [bridge method](https://stackoverflow.com/questions/5007357/java-generics-bridge-method).

So, let's ignore bridge methods.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#171](https://github.com/yegor256/jpeek/issues/171) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), total is [+90](https://www.0crat.com/u/nikialeksey)

**Comment by llorllale** [comment]
These are so called *synthetic methods* as per the [JLS spec](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.1):

> A construct emitted by a Java compiler must be marked as synthetic if it does not correspond to a construct declared explicitly or implicitly in source code, unless the emitted construct is a class initialization method

They should be excluded from the `skeleton`

**Comment by 0crat** [comment]
The job [#171](https://github.com/yegor256/jpeek/issues/171) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1631748510); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@uurl[/z](https://www.0crat.com/u/uurl) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by uurl** [comment]
@0crat wait #260

**Comment by 0crat** [comment]
> @0crat wait #260 ([here](https://github.com/yegor256/jpeek/issues/171#issuecomment-397908810))

@uurl The impediment for [#171](https://github.com/yegor256/jpeek/issues/171) was registered successfully by @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by uurl** [comment]
@yegor256 please help, the PR #260 closes this ticket, PR #260 is already accepted and merged but I don't know how to indicate that it closes this issue. While the issue is open, I don't receive any payment.

**Comment by yegor256** [comment]
@uurl I don't think I understand. What exactly do you want me to do?

**Comment by uurl** [comment]
@yegor256  didn't received payment for this job yet; the PR #260 closes this ticket. Could you indicate @0crat that it's closed?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/171#issuecomment-405843321); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by yegor256** [comment]
@uurl why do you expect to receive the payment, if the job is not closed yet? Please, read this: https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@nikialeksey Looks like this one already been merged, please take a look

**Comment by nikialeksey** [comment]
O, yeah, cool!

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
The job [#171](https://github.com/yegor256/jpeek/issues/171) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment
