### ISSUE TITLE
Build is broken: xcop failing on TCC.xsl

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#172]
See travis log [here](https://travis-ci.org/yegor256/jpeek/builds/340537562?utm_source=github_status&utm_medium=notification)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale fixed, thanks: 7033094

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#172` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#172](https://github.com/yegor256/jpeek/issues/172) was not in scope
