### ISSUE TITLE
MetricsTest.java:73-76: Adding a new 'op' for calls to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#176]
The puzzle `106-8e3f4f01` from #106 has to be resolved:

https://github.com/yegor256/jpeek/blob/34aa4252d8456825d778681ae1a8a168d8b8f457/src/test/java/org/jpeek/MetricsTest.java#L73-L76

The puzzle was created by George Aristy on 09-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#176](https://github.com/yegor256/jpeek/issues/176) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#176](https://github.com/yegor256/jpeek/issues/176) assigned to @gauee[/z](https://www.0crat.com/u/gauee), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1870667044); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@gauee[/z](https://www.0crat.com/u/gauee) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @gauee[/z](https://www.0crat.com/u/gauee) resigned from [#176](https://github.com/yegor256/jpeek/issues/176), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @gauee[/z](https://www.0crat.com/u/gauee)

**Comment by gauee** [comment]
@yegor256, could you please reassign that issue to me.

**Comment by yegor256** [comment]
@0crat assign @gauee

**Comment by gauee** [comment]
@0crat wait for PR #265

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `106-8e3f4f01` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#176](https://github.com/yegor256/jpeek/issues/176) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @gauee[/z](https://www.0crat.com/u/gauee)
