### ISSUE TITLE
Skeleton.java:270-281: Find and include the name of the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#180]
The puzzle `114-7bfa1f3a` from #114 has to be resolved:

https://github.com/yegor256/jpeek/blob/119e6ba9b97919794eb9820445c0214e1ec3b73d/src/main/java/org/jpeek/Skeleton.java#L270-L281

The puzzle was created by Rok Povsic on 13-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#180](https://github.com/yegor256/jpeek/issues/180) is now in scope, role is `DEV`

**Comment by llorllale** [comment]
See my comment [here](https://github.com/yegor256/jpeek/issues/138#issuecomment-366548476)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#180](https://github.com/yegor256/jpeek/issues/180) assigned to @baybatu[/z](https://www.0crat.com/u/baybatu), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1870672094); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@baybatu[/z](https://www.0crat.com/u/baybatu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @baybatu[/z](https://www.0crat.com/u/baybatu) resigned from [#180](https://github.com/yegor256/jpeek/issues/180), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @baybatu[/z](https://www.0crat.com/u/baybatu)

**Comment by uurl** [comment]
@0crat assign @uurl

**Comment by 0crat** [comment]
> @0crat assign @uurl ([here](https://github.com/yegor256/jpeek/issues/180#issuecomment-415375358))

@uurl You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @uurl[/z](https://www.0crat.com/u/uurl) are: `DEV`

**Comment by 0crat** [comment]
The job [#180](https://github.com/yegor256/jpeek/issues/180) assigned to @oridan[/z](https://www.0crat.com/u/oridan), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/70d0e888-d97d-49a8-b6c4-e4b9dee57c74); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by oridan** [comment]
@paulodamaso ping.

**Comment by paulodamaso** [comment]
@oridan Your PR have merge conflicts, please resolve them

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
The job [#180](https://github.com/yegor256/jpeek/issues/180) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment
