### ISSUE TITLE
MetricsTest.java:63-69: NaN-based assertions introduced...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#181]
The puzzle `103-11fe8626` from #103 has to be resolved:

https://github.com/yegor256/jpeek/blob/82887588d50eafffe1f2a2c759ff37ca35086562/src/test/java/org/jpeek/MetricsTest.java#L63-L69

The puzzle was created by Kapralov Sergey on 08-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#181](https://github.com/yegor256/jpeek/issues/181) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#181](https://github.com/yegor256/jpeek/issues/181) assigned to @robsonataide[/z](https://www.0crat.com/u/robsonataide), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1870717146); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@robsonataide[/z](https://www.0crat.com/u/robsonataide) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @robsonataide[/z](https://www.0crat.com/u/robsonataide) resigned from [#181](https://github.com/yegor256/jpeek/issues/181), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @robsonataide[/z](https://www.0crat.com/u/robsonataide)

**Comment by 0crat** [comment]
The job [#181](https://github.com/yegor256/jpeek/issues/181) assigned to @danielpalafox[/z](https://www.0crat.com/u/danielpalafox), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/af8a566a-c3ff-4fc6-8e26-d42878f489e9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @danielpalafox[/z](https://www.0crat.com/u/danielpalafox) resigned from [#181](https://github.com/yegor256/jpeek/issues/181), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @danielpalafox[/z](https://www.0crat.com/u/danielpalafox)

**Comment by 0crat** [comment]
The job [#181](https://github.com/yegor256/jpeek/issues/181) assigned to @gauee[/z](https://www.0crat.com/u/gauee), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/80876a62-8b90-4bcd-afeb-826a61b3fade); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @gauee[/z](https://www.0crat.com/u/gauee)

**Comment by 0crat** [comment]
The user @gauee[/z](https://www.0crat.com/u/gauee) resigned from [#181](https://github.com/yegor256/jpeek/issues/181), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#181](https://github.com/yegor256/jpeek/issues/181) assigned to @szaffarano[/z](https://www.0crat.com/u/szaffarano), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/b0bead54-3dad-4269-b600-71f91096cb19); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ebercamargo** [comment]
@0crat wait I'm short on time, I ask you to wait so I can handle it in the near future.

**Comment by 0crat** [comment]
The user @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) resigned from [#181](https://github.com/yegor256/jpeek/issues/181), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0crat** [comment]
The job [#181](https://github.com/yegor256/jpeek/issues/181) assigned to @nermeen78[/z](https://www.0crat.com/u/nermeen78), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/49e376b7-1983-4b24-993f-7904d62cc8e0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@nermeen78[/z](https://www.0crat.com/u/nermeen78) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Nermeen78** [comment]
@yegor256 I think this issue is already solved if no please could you describe this issue in more details ?

**Comment by 0crat** [comment]
> @0crat wait I'm short on time, I ask you to wait so I can handle it in the near future. ([here](https://github.com/yegor256/jpeek/issues/181#issuecomment-496538364))

@ebercamargo @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) you can't register impediment for this job

**Comment by Nermeen78** [comment]
@0crat wait for more details about the issue

**Comment by 0crat** [comment]
> @0crat wait for more details about the issue ([here](https://github.com/yegor256/jpeek/issues/181#issuecomment-504756540))

@Nermeen78 The impediment for [#181](https://github.com/yegor256/jpeek/issues/181) was registered successfully by @nermeen78[/z](https://www.0crat.com/u/nermeen78)

**Comment by yegor256** [comment]
@Nermeen78 just remove the puzzle in a pull request and see what the reviewer will say

**Comment by 0crat** [comment]
The job [#181](https://github.com/yegor256/jpeek/issues/181) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/dec7db52-1c38-4b6e-bfdc-b252d43c650e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by aivinog1** [comment]
@0crat wait for merge #330

**Comment by 0crat** [comment]
> @0crat wait for merge #330  ([here](https://github.com/yegor256/jpeek/issues/181#issuecomment-511296211))

@aivinog1 The impediment for [#181](https://github.com/yegor256/jpeek/issues/181) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0pdd** [comment]
The puzzle `103-11fe8626` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @aivinog1[/z](https://www.0crat.com/u/aivinog1), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#181](https://github.com/yegor256/jpeek/issues/181) is now out of scope

**Comment by fabriciofx** [comment]
@0pdd quality is good.

**Comment by fabriciofx** [comment]
@0crat quality is good.

**Comment by 0crat** [comment]
> @0crat quality is good. ([here](https://github.com/yegor256/jpeek/issues/181#issuecomment-511578446))

@fabriciofx Argument "is" doesn't match regex `good|bad|acceptable`

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)
