### ISSUE TITLE
logging is absent

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#185]
Let's add logging.

**Comment by 0crat** [comment]
The job [#185](https://github.com/yegor256/jpeek/issues/185) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/460556257). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9819](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9819](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9819](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job [#185](https://github.com/yegor256/jpeek/issues/185) is already in scope

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#185](https://github.com/yegor256/jpeek/issues/185), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#185](https://github.com/yegor256/jpeek/issues/185) is now out of scope
