### ISSUE TITLE
Skeleton XML building is very slow

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#186]
When the amount of classes is big (over 200), the `Skeleton` takes minutes to create an XML file. The problem is in the long list of Xembly directives (over 200,000). They contain XPath instructions, which consume a lot of CPU power.

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.1`

**Comment by 0crat** [comment]
The job [#186](https://github.com/yegor256/jpeek/issues/186) is now out of scope
