### ISSUE TITLE
OCC

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#19]
Let's implement OCC cohesion metric.

H. Aman, K. Yamasaki, H. Yamada, and M.-T. Noda, “A proposal
of class cohesion metrics using sizes of cohesive parts,” in Proc. of
Fifth Joint Conference on Knowledge-based Software Engineering,
2002, pp. 102–107.

https://www.researchgate.net/profile/Hirohisa_Aman/publication/268046583_A_Proposal_of_Class_Cohesion_Metrics_Using_Sizes_of_Cohesive_Parts/links/5729ca4b08ae057b0a060fa6/A-Proposal-of-Class-Cohesion-Metrics-Using-Sizes-of-Cohesive-Parts.pdf

**Comment by VsSekorin** [comment]
I'll try to do it.

**Comment by yegor256** [comment]
@VsSekorin thanks!

**Comment by yegor256** [comment]
@VsSekorin many thanks for your contribution!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#19`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#19` is not in scope.
