### ISSUE TITLE
Build is broken: failing due to lack of test coverage

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#192]
PR builds are failing due to test coverage not being met even when those PRs do not modify java code.

Example [here](https://github.com/yegor256/jpeek/pull/184#issuecomment-365719046).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by llorllale** [comment]
@yegor256 please see attached jacoco coverage report: [jacoco.zip](https://github.com/yegor256/jpeek/files/1737249/jacoco.zip)

The `org.jpeek.web` package has only ~40% coverage, which is too low.

**Comment by yegor256** [comment]
@llorllale I don't understand what exactly is broken? Travis is green, Rultor releases successfully and it builds on my laptop. What's wrong?

**Comment by llorllale** [comment]
@yegor256 I think there's some kind of intermittency or environmental factors that cause it to fail sometimes

I uploaded the jacoco.zip report after having the coverage check fail when solving some conflicts due to updated `master`. Still, I pushed solved conflicts and saw that Travis build did not fail. Weird.

Closing this, will open new issue in case it happens again

**Comment by llorllale** [comment]
@yegor256 just happened in [this PR](https://github.com/yegor256/jpeek/pull/198) (see rultor log [here](http://www.rultor.com/t/13942-367441962)).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#192](https://github.com/yegor256/jpeek/issues/192) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+760](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#192](https://github.com/yegor256/jpeek/issues/192) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/92d34ce5-737a-4b2f-886c-b1f23a262325); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#192](https://github.com/yegor256/jpeek/issues/192), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
The job [#192](https://github.com/yegor256/jpeek/issues/192) assigned to @danilomo[/z](https://www.0crat.com/u/danilomo), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/92a5f67e-692e-41fa-a4f7-1a9f54f33164); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by danilomo** [comment]
@0crat  status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/192#issuecomment-456468705))

@danilomo This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#192](https://github.com/yegor256/jpeek/issues/192) is [in scope](http://www.zerocracy.com/policy.html#14) for 11mon
  * The role is `DEV`
  * The job is assigned to @danilomo[/z](https://www.0crat.com/u/danilomo) for [11min](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @llorllale[/z](https://www.0crat.com/u/llorllale): This user reported the ticket
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23192%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by danilomo** [comment]
@llorllale How to reproduce the bug? What should be done exactly?

Things continue to appear normal in travis/codecov.

**Comment by llorllale** [comment]
@danilomo it was happening with the merge builds. I guess it's fixed now. Closing.

**Comment by 0crat** [comment]
Job was finished in 45 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@cucumber007[/z](https://www.0crat.com/u/cucumber007) please review this job completed by @danilomo[/z](https://www.0crat.com/u/danilomo), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#192](https://github.com/yegor256/jpeek/issues/192) is now out of scope

**Comment by cucumber007** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @danilomo[/z](https://www.0crat.com/u/danilomo)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @cucumber007[/z](https://www.0crat.com/u/cucumber007)
