### ISSUE TITLE
TCC.xsl:57-59: TCC: need to come back and refactor the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#195]
The puzzle `120-bc67ce38` from #120 has to be resolved:

https://github.com/yegor256/jpeek/blob/d73541f09fb419892636db79c043182c309ce06f/src/main/resources/org/jpeek/metrics/TCC.xsl#L57-L59

The puzzle was created by rultor on 17-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#195](https://github.com/yegor256/jpeek/issues/195) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @baybatu[/z](https://www.0crat.com/u/baybatu), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1870737351); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@baybatu[/z](https://www.0crat.com/u/baybatu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @baybatu[/z](https://www.0crat.com/u/baybatu) resigned from [#195](https://github.com/yegor256/jpeek/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @baybatu[/z](https://www.0crat.com/u/baybatu)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/07ffaf31-bcbd-486e-8bdd-ae8898de7713); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#195](https://github.com/yegor256/jpeek/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @szaffarano[/z](https://www.0crat.com/u/szaffarano), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/23f0f9bf-0a4e-44ba-968c-3ff60897c9a3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The user @szaffarano[/z](https://www.0crat.com/u/szaffarano) resigned from [#195](https://github.com/yegor256/jpeek/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @szaffarano[/z](https://www.0crat.com/u/szaffarano)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/6e054148-db88-4b70-be83-f1a49dc19e27); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@yegor256 
I'm confused due to my bad quality in XSLT
is adding a condition like the following sufficient?

`<xsl:variable name="right_attrs" select="$attrs[. = $right/ops/op/text() and ancestor::calss[@id]=$left_attrs/ancestor::calss[@id]]"/>`

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/6503fd0d-faef-4b3c-bb2a-b194d7a13faa); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#195` already assigned to @marceloamadeu, can't assign to @marceloamadeu

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/45ace8cd-21d0-44cb-a872-0b0504e6e535); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#195](https://github.com/yegor256/jpeek/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f19ad8b5-4751-4261-a9d1-4ca98eb14f03); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#195](https://github.com/yegor256/jpeek/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @mesut[/z](https://www.0crat.com/u/mesut), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/7ce8b8a6-f76a-4b69-9d3b-216ecb4c3380); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ebercamargo** [comment]
@0crat wait I'm short on time, I ask you to wait so I can handle it in the near future.

**Comment by 0crat** [comment]
> @0crat wait I'm short on time, I ask you to wait so I can handle it in the near future. ([here](https://github.com/yegor256/jpeek/issues/195#issuecomment-496538239))

@ebercamargo The impediment for [#195](https://github.com/yegor256/jpeek/issues/195) was registered successfully by @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by ebercamargo** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/195#issuecomment-581887517))

@ebercamargo The user @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) resigned from [#195](https://github.com/yegor256/jpeek/issues/195), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged (job refused in 6251 hours), see [§6](http://www.zerocracy.com/policy.html#6): -20 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3d90ce0e-6670-47dc-98fc-4babbb434a44); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk) resigned from [#195](https://github.com/yegor256/jpeek/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/jpeek/issues/195) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3198a2d7-eaa3-45fa-89b5-46bd5bdaa57a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@llorllale I am confused here since `$attrs` xslt variable on which we test and filter already takes attributes in skeleton that:
* are not static (so the problem in #156 can not happen)
* in skeleton `ops/op` text content already has the fully qualified name when it comes to other classes static fields

I will anyway add a test for this.

**Comment by 0pdd** [comment]
The puzzle `120-bc67ce38` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)
