### ISSUE TITLE
index.xsd:26-28: Index.xsd: add `xsd:documentation` tags...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#199]
The puzzle `134-9a3b0d90` from #134 has to be resolved:

https://github.com/yegor256/jpeek/blob/0d4a79106f05652d4c5874638278262b31a8177a/src/main/resources/org/jpeek/xsd/index.xsd#L26-L28

The puzzle was created by rultor on 19-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#199](https://github.com/yegor256/jpeek/issues/199) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
@robsonataide[/z](https://www.0crat.com/u/robsonataide) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @robsonataide[/z](https://www.0crat.com/u/robsonataide) resigned from [#199](https://github.com/yegor256/jpeek/issues/199), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @robsonataide[/z](https://www.0crat.com/u/robsonataide)

**Comment by 0crat** [comment]
The job [#199](https://github.com/yegor256/jpeek/issues/199) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/4fc00f3b-4433-4851-a454-be3345ecda90); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The user @serranya[/z](https://www.0crat.com/u/serranya) resigned from [#199](https://github.com/yegor256/jpeek/issues/199), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by 0pdd** [comment]
The puzzle `134-9a3b0d90` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#282](https://github.com/yegor256/jpeek/issues/282) is still not solved.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#199` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#199](https://github.com/yegor256/jpeek/issues/199) is now out of scope

**Comment by paulodamaso** [comment]
@0crat pay @Serranya 30min

**Comment by 0crat** [comment]
> @0crat pay @Serranya 30min ([here](https://github.com/yegor256/jpeek/issues/199#issuecomment-448550921))

@paulodamaso Argument "@Serranya" doesn't match regex `\d+min`

**Comment by paulodamaso** [comment]
@0crat pay 30min @Serranya

**Comment by 0crat** [comment]
> @0crat pay 30min @Serranya  ([here](https://github.com/yegor256/jpeek/issues/199#issuecomment-448551562))

@paulodamaso The project is under-funded, you can't do it now, see [§49](http://www.zerocracy.com/policy.html#49)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat assign @Serranya

**Comment by 0crat** [comment]
> @0crat assign @Serranya  ([here](https://github.com/yegor256/jpeek/issues/199#issuecomment-448557512))

@paulodamaso The job [#199](https://github.com/yegor256/jpeek/issues/199) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/76fc0152-86c1-4c79-9121-92939d22f987); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#199](https://github.com/yegor256/jpeek/issues/199) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#282](https://github.com/yegor256/jpeek/issues/282) is solved here.
