### ISSUE TITLE
MetricsTest.java:77-78: OCC metric: need to implement the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#203]
The puzzle `90-29fbce76` from #90 has to be resolved:

https://github.com/yegor256/jpeek/blob/f5fa44ddc8c7b44c880f8e84ef1dcf7b4ce30201/src/test/java/org/jpeek/MetricsTest.java#L77-L78

The puzzle was created by George Aristy on 11-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#203](https://github.com/yegor256/jpeek/issues/203) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#203](https://github.com/yegor256/jpeek/issues/203) assigned to @mesut[/z](https://www.0crat.com/u/mesut), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1871139128); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by mesut** [comment]
0crat wait for PR #264

**Comment by mesut** [comment]
@0crat  wait for PR #264

**Comment by 0crat** [comment]
> @0crat wait for PR #264 ([here](https://github.com/yegor256/jpeek/issues/203#issuecomment-404124568))

@mesut The impediment for [#203](https://github.com/yegor256/jpeek/issues/203) was registered successfully by @mesut[/z](https://www.0crat.com/u/mesut)

**Comment by 0pdd** [comment]
The puzzle `90-29fbce76` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @mesut[/z](https://www.0crat.com/u/mesut), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#203](https://github.com/yegor256/jpeek/issues/203) is now out of scope

**Comment by mesut** [comment]
@elenavolokhova can we please review the quality for closing this issue ?

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @mesut[/z](https://www.0crat.com/u/mesut)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
