### ISSUE TITLE
MetricsTest.java:77-78: PCC: add the rest of the test...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#205]
The puzzle `67-33d40469` from #67 has to be resolved:

https://github.com/yegor256/jpeek/blob/bdacc739c3660720f3bbb2a1fbf23f236f117030/src/test/java/org/jpeek/MetricsTest.java#L77-L78

The puzzle was created by George Aristy on 12-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#205](https://github.com/yegor256/jpeek/issues/205) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `67-33d40469` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@cucumber007[/z](https://www.0crat.com/u/cucumber007) please review this job completed by @serranya[/z](https://www.0crat.com/u/serranya), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#205](https://github.com/yegor256/jpeek/issues/205) is now out of scope

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
