### ISSUE TITLE
TCC scores 0 on a class with no methods

### ISSUE THREAD

**Issue by rok-povsic** [yegor256/jpeek#213]
The TCC scoring method returns a value of 0 for a class that has no methods (excluding static functions and the constructor method) - specifically, [this class](https://github.com/yegor256/jpeek/blob/c1e76a06eea316c9c73530d9ad6c4b0730cd4daa/src/test/resources/org/jpeek/samples/NoMethods.java). 

One might expect either a value of 1, or Nan in this case, since it is either that the class is cohesive (value 1) or the value cannot be calculated (value Nan). Saying that a class with no methods is not cohesive doesn't seem to hold.

Similarly, a class with methods but no attributes (see [this class](https://github.com/yegor256/jpeek/blob/fc4437faaff683cfecb073cb7e04f3418cdefca9/src/test/resources/org/jpeek/samples/WithoutAttributes.java)) also gets a score of 0.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by rok-povsic** [comment]
@yegor256 The original paper doesn't define what the score is for these two cases.

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/213#issuecomment-454557031))

@paulodamaso Job [#213](https://github.com/yegor256/jpeek/issues/213) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic)

**Comment by 0crat** [comment]
The job [#213](https://github.com/yegor256/jpeek/issues/213) assigned to @dfrau32[/z](https://www.0crat.com/u/dfrau32), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/2b697cbe-fa0d-49f0-a751-c8bef1b5c438); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@dfrau32[/z](https://www.0crat.com/u/dfrau32) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @dfrau32[/z](https://www.0crat.com/u/dfrau32) resigned from [#213](https://github.com/yegor256/jpeek/issues/213), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @dfrau32[/z](https://www.0crat.com/u/dfrau32)

**Comment by 0crat** [comment]
The job [#213](https://github.com/yegor256/jpeek/issues/213) assigned to @jekeam[/z](https://www.0crat.com/u/jekeam), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/ad9a322a-105d-425a-888a-4fa8261317f4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#213](https://github.com/yegor256/jpeek/issues/213) assigned to @romach[/z](https://www.0crat.com/u/romach), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/5eb5af03-4a2c-47e9-9b23-a8bf4205349d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@romach[/z](https://www.0crat.com/u/romach) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @romach[/z](https://www.0crat.com/u/romach) resigned from [#213](https://github.com/yegor256/jpeek/issues/213), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @romach[/z](https://www.0crat.com/u/romach)

**Comment by GnusinPavel** [comment]
@paulodamaso @rok-povsic 
So what is the decision? Should we return 1 or NaN?

**Comment by rok-povsic** [comment]
@GnusinPavel It's not my decision to make, but likely @yegor256 's.

**Comment by paulodamaso** [comment]
@yegor256 please take a look at this

**Comment by GnusinPavel** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait  ([here](https://github.com/yegor256/jpeek/issues/213#issuecomment-558690082))

@GnusinPavel The impediment for [#213](https://github.com/yegor256/jpeek/issues/213) was registered successfully by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by 0crat** [comment]
The job [#213](https://github.com/yegor256/jpeek/issues/213) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/2e2422c7-0f7c-4601-9a68-4529baa30449); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@rajanamistry[/z](https://www.0crat.com/u/rajanamistry) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#213](https://github.com/yegor256/jpeek/issues/213), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#213](https://github.com/yegor256/jpeek/issues/213) assigned to @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/7f9f476c-e055-41f6-a3dc-b72f6e95c670); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
@volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk) resigned from [#213](https://github.com/yegor256/jpeek/issues/213), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk)

**Comment by 0crat** [comment]
The job [#213](https://github.com/yegor256/jpeek/issues/213) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3b4b1451-56a4-4844-9e74-bf6138d78ea2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@rok-povsic PR #409 reviewed and merged. Please close the issue.

**Comment by HDouss** [comment]
@rok-povsic Could you please close the issue?

**Comment by HDouss** [comment]
@rok-povsic ping..

**Comment by paulodamaso** [comment]
@HDouss I'll close it, thank you for

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
