### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#22]
Let's create it.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#22` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4340](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.4`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#22` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4425](http://www.0crat.com/u/yegor256).
