### ISSUE TITLE
SCOM: MetricsTest does not provide a way to test the SCOM_minK value

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#222]
(This may or may not be relevant if the proposal for #169 is approved.)

**Problem:**
As per #142, I am implementing calculation of `SCOM_minK` value for `SCOM`. I have the calculation ready. It will be stored in a new `var` in the metric.xml, but `MetricsTest` currently only tests the `//class/@value` of metrics.

**Proposal**
Ideally, enable tests of arbitrary xpaths in `MetricsTest`. Otherwise, enable tests of `<var>` using an xpath similar to : `//var[@id = 'SCOM_minK']`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale but only `@value` matters for us. Or you want our tests to be more detailed oriented. I didn't understand, what is broken?

**Comment by llorllale** [comment]
@yegor256 For `SCOM_minK` I need the tests to be more detail oriented.

`SCOM_minK` is another number calculated for `SCOM` separate from its `@value`. The paper says that if SCOM < SCOM_minK then you should consider splitting the class into more cohesive classes.

**Comment by yegor256** [comment]
@llorllale we don't need to test those supplementary variables. Each metric has them. We just have them in the XML report for visibility. That's enough.
