### ISSUE TITLE
skeleton.xsd:26-28: Skeleton.xsd: add a reference to this...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#224]
The puzzle `135-d5b2c3f6` from #135 has to be resolved:

https://github.com/yegor256/jpeek/blob/752b4d52b6a0c293e8a71cd4ca902b3656fcf43e/src/main/resources/org/jpeek/xsd/skeleton.xsd#L26-L28

The puzzle was created by George Aristy on 27-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#224](https://github.com/yegor256/jpeek/issues/224) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/jpeek/issues/224) assigned to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a28e74ec-0814-4c8e-a506-9756d5c31a77); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#224](https://github.com/yegor256/jpeek/issues/224), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/jpeek/issues/224) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/0fd7f886-8ad7-468c-b4a7-1b58ae77e1fe); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#224](https://github.com/yegor256/jpeek/issues/224), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/jpeek/issues/224) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/992b20fd-e9f4-4723-bdf9-136d67382c44); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#224](https://github.com/yegor256/jpeek/issues/224), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by aivinog1** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/224#issuecomment-513607444))

@aivinog1 This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#224](https://github.com/yegor256/jpeek/issues/224) is [in scope](http://www.zerocracy.com/policy.html#14) for 17mon
  * The role is `DEV`
  * The job is assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1) for [6hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @supra89kren[/z](https://www.0crat.com/u/supra89kren): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23224%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/jpeek/issues/224) assigned to @baybatu[/z](https://www.0crat.com/u/baybatu), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/09130869-a498-4c6e-b3df-85b78a809637); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@baybatu[/z](https://www.0crat.com/u/baybatu) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @baybatu[/z](https://www.0crat.com/u/baybatu) resigned from [#224](https://github.com/yegor256/jpeek/issues/224), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @baybatu[/z](https://www.0crat.com/u/baybatu)

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/jpeek/issues/224) assigned to @dfrau32[/z](https://www.0crat.com/u/dfrau32), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/cb4bee7d-a111-4794-8a65-e0d08b32ea0c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @dfrau32[/z](https://www.0crat.com/u/dfrau32) resigned from [#224](https://github.com/yegor256/jpeek/issues/224), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @dfrau32[/z](https://www.0crat.com/u/dfrau32)

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/jpeek/issues/224) assigned to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f8a56a23-9fae-42fe-96ad-7ba6026d092a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) resigned from [#224](https://github.com/yegor256/jpeek/issues/224), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by stepanov-dmitry** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/224#issuecomment-536315864))

@stepanov-dmitry This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#224](https://github.com/yegor256/jpeek/issues/224) is [in scope](http://www.zerocracy.com/policy.html#14) for 19mon
  * The role is `DEV`
  * The job is assigned to @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @supra89kren[/z](https://www.0crat.com/u/supra89kren): User was resigned from the ticket
    * @aivinog1[/z](https://www.0crat.com/u/aivinog1): User was resigned from the ticket
    * @baybatu[/z](https://www.0crat.com/u/baybatu): User was resigned from the ticket
    * @dfrau32[/z](https://www.0crat.com/u/dfrau32): User was resigned from the ticket
    * @ebercamargo[/z](https://www.0crat.com/u/ebercamargo): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23224%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by stepanov-dmitry** [comment]
@0crat wait for https://github.com/yegor256/jpeek/pull/339

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/jpeek/pull/339 ([here](https://github.com/yegor256/jpeek/issues/224#issuecomment-536755223))

@stepanov-dmitry The impediment for [#224](https://github.com/yegor256/jpeek/issues/224) was registered successfully by @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry)

**Comment by stepanov-dmitry** [comment]
@mohamednizar @paulodamaso since the task has been done and the code has been merge, could you please close it and mark as done? Seems I have not enough permissions to do that or tell me how can do it please.

**Comment by stepanov-dmitry** [comment]
Reference to the pull request: https://github.com/yegor256/jpeek/pull/339

**Comment by mohamednizar** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@stepanov-dmitry When you solve an issue opened by @0pdd you have to remove the puzzle form the code so it understands that the issue was solved and it can be closed. Please make another pull request removing the puzzle from the code.

**Comment by 0pdd** [comment]
The puzzle `135-d5b2c3f6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/jpeek/issues/224) is now out of scope

**Comment by fabriciofx** [comment]
@0pdd quality good

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/224#issuecomment-552981779))

@paulodamaso This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#224](https://github.com/yegor256/jpeek/issues/224) is not in scope
  * The job is waiting quality review verdict by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for 12hr
  * @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23224%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)
