### ISSUE TITLE
matrix.xsd:29-31: Matrix.xsd: add a reference to this...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#225]
The puzzle `135-9cabe027` from #135 has to be resolved:

https://github.com/yegor256/jpeek/blob/752b4d52b6a0c293e8a71cd4ca902b3656fcf43e/src/main/resources/org/jpeek/xsd/matrix.xsd#L29-L31

The puzzle was created by George Aristy on 27-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/225#issuecomment-451405387))

@paulodamaso This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#225](https://github.com/yegor256/jpeek/issues/225) is [in scope](http://www.zerocracy.com/policy.html#14) for 10mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23225%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat assign @ilyakharlamov

**Comment by 0crat** [comment]
> @0crat assign @ilyakharlamov  ([here](https://github.com/yegor256/jpeek/issues/225#issuecomment-451406394))

@paulodamaso The job [#225](https://github.com/yegor256/jpeek/issues/225) assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/5b001620-d0f3-43c6-8f2e-d38c6ae37818); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `135-9cabe027` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@cucumber007[/z](https://www.0crat.com/u/cucumber007) please review this job completed by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#225](https://github.com/yegor256/jpeek/issues/225) is now out of scope

**Comment by cucumber007** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @cucumber007[/z](https://www.0crat.com/u/cucumber007)
