### ISSUE TITLE
index.xsd:29-31: Index.xsd: add a reference to this...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#226]
The puzzle `135-4462c34d` from #135 has to be resolved:

https://github.com/yegor256/jpeek/blob/752b4d52b6a0c293e8a71cd4ca902b3656fcf43e/src/main/resources/org/jpeek/xsd/index.xsd#L29-L31

The puzzle was created by George Aristy on 27-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#226](https://github.com/yegor256/jpeek/issues/226) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#226](https://github.com/yegor256/jpeek/issues/226) assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/e1707cdf-4d2b-420f-a9c6-15307cf35261); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this job was assigned to you 9days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ilyakharlamov** [comment]
@0crat wait #317

**Comment by 0crat** [comment]
> @0crat wait #317  ([here](https://github.com/yegor256/jpeek/issues/226#issuecomment-482087161))

@ilyakharlamov The impediment for [#226](https://github.com/yegor256/jpeek/issues/226) was registered successfully by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by 0pdd** [comment]
The puzzle `135-4462c34d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#226](https://github.com/yegor256/jpeek/issues/226) is now out of scope

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)
