### ISSUE TITLE
Report.java:142-146: The current solution to add the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#227]
The puzzle `135-1c80191e` from #135 has to be resolved:

https://github.com/yegor256/jpeek/blob/752b4d52b6a0c293e8a71cd4ca902b3656fcf43e/src/main/java/org/jpeek/Report.java#L142-L146

The puzzle was created by George Aristy on 27-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#227](https://github.com/yegor256/jpeek/issues/227) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#227](https://github.com/yegor256/jpeek/issues/227) assigned to @protagores[/z](https://www.0crat.com/u/protagores), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/077c524e-6ade-4d3e-9896-da18702bcd5e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@protagores[/z](https://www.0crat.com/u/protagores) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Protagores** [comment]
@0crat wait for #322

**Comment by 0crat** [comment]
> @0crat wait for #322  ([here](https://github.com/yegor256/jpeek/issues/227#issuecomment-485745961))

@Protagores The impediment for [#227](https://github.com/yegor256/jpeek/issues/227) was registered successfully by @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by 0pdd** [comment]
The puzzle `135-1c80191e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#327](https://github.com/yegor256/jpeek/issues/327) is still not solved.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @protagores[/z](https://www.0crat.com/u/protagores), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#227](https://github.com/yegor256/jpeek/issues/227) is now out of scope

**Comment by Protagores** [comment]
@paulodamaso QA review was assigned 15 days ago, please resolve.

**Comment by paulodamaso** [comment]
@Protagores All messages must have to be addressed to someone, [this one](https://github.com/yegor256/jpeek/issues/322#issuecomment-488788125) is not, please fix it.

**Comment by Protagores** [comment]
@paulodamaso Done.

**Comment by paulodamaso** [comment]
@Protagores Thanks

**Comment by paulodamaso** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#507](https://github.com/cqfn/jpeek/issues/507) is still not solved.

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/cqfn/jpeek/issues/227#issuecomment-493797286))

@paulodamaso There is no quality review for [#227](https://github.com/cqfn/jpeek/issues/227), no performer

**Comment by 0crat** [comment]
> @0crat wait for #322  ([here](https://github.com/cqfn/jpeek/issues/227#issuecomment-485745961))

@Protagores Job `gh:cqfn/jpeek#227` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#507](https://github.com/cqfn/jpeek/issues/507) is solved here.
