### ISSUE TITLE
XmlClass.java:142-149: LCOM3: Must first fix #171 by...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#228]
The puzzle `139-752903d5` from #139 has to be resolved:

https://github.com/yegor256/jpeek/blob/7ed2e4249c336fd5068955987dc96edafe260cc4/src/main/java/org/jpeek/skeleton/XmlClass.java#L142-L149

The puzzle was created by George Aristy on 18-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#228](https://github.com/yegor256/jpeek/issues/228) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `139-752903d5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#228` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#228](https://github.com/yegor256/jpeek/issues/228) is now out of scope
