### ISSUE TITLE
Starting application is broken

### ISSUE THREAD

**Issue by piotrkot** [yegor256/jpeek#229]
As described [here](https://github.com/yegor256/jpeek) in *How to use?* section I run:
```
$> java -jar ../Downloads/jpeek-0.5-jar-with-dependencies.jar --sources takes --target ./jpeek-takes
Exception in thread "main" java.lang.IllegalArgumentException: Exactly two arguments required: source and output directory
        at org.jpeek.Main.main(Main.java:54)
```
Directory `takes` is present and contains [takes](https://github.com/yegor256/takes) project.
I expect the application to start or describe what I do wrong.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@piotrkot you need a fresh version of the app. 0.5 is a very old one. Try the latest one: https://github.com/yegor256/jpeek/releases

**Comment by 0crat** [comment]
The job is not in WBS, can't close

**Comment by piotrkot** [comment]
@yegor256 I see. Thanks. That means it is a mistake to keep link to version 0.5 in the *How to use* section. Can you fix this?

**Comment by yegor256** [comment]
@piotrkot yep, fixed in 0cb7e82 thanks!

**Comment by piotrkot** [comment]
@yegor256 And yet another detail. The first sentence in *How to use* - "Load this JAR file" - is linked with the version 0.5. Can you fix this too?

**Comment by yegor256** [comment]
@piotrkot how about now? 8c40bd2

**Comment by piotrkot** [comment]
@yegor256 perfect, thanks!
