### ISSUE TITLE
CAMC values can't be higher than 1.0

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#23]
In theory, CAMC values can't be higher than 1.0. However, our software produces 2.0 and sometimes even 3.0. Let's investigate and fix.

For example [`org.takes.misc.TransformAction`](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/misc/TransformAction.java) gives 2.0.

**Comment by memoyil** [comment]
I am looking at it

**Comment by memoyil** [comment]
@yegor256 with Transformaction, jpeek doesnt produce any results. Could you please give another example classes?

**Comment by memoyil** [comment]
@yegor256 You can close this issue.

**Comment by yegor256** [comment]
@memoyil thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#23`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#23` is not in scope.
