### ISSUE TITLE
MWE.xsl 47-54 For the MWE metric, how to calculate the topics is not implemented. 

### ISSUE THREAD

**Issue by uurl** [yegor256/jpeek#234]
To calculate the Maximal Weighted Entropy (MWE) the "topic" is needed. Currently this process is not implemented.

To calculate the topics: a method contains words excluding programming language keywords, stop words and punctuation. So, to calculate the MWE metric each "variable's name" is a topic.

A High Cohesive Class has two characteristics:
 - High Occupancy (Oi): the main topic is present in all the methods.
 - High Distribution (Di): all the methods are related to the same topic.

For more information on how to calculate the MWE metric, check the PDF [lyu09] in the papers.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@uurl we have a puzzle for that, right?

**Comment by uurl** [comment]
@yegor256 the puzzle #144 talked about it, but currently it doesn't specify how calculate the topics

**Comment by yegor256** [comment]
@uurl this is a problem related to the puzzle. No need to create a new ticket for it. While you (or someone else) will be solving the puzzle, the problem will appear and it will lead to new puzzles.

**Comment by uurl** [comment]
@yegor256 Ok, thanks
