### ISSUE TITLE
web front

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#24]
Let's create a simple web front for public Maven artifacts.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#24` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4345](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4345](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#24` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4485](http://www.0crat.com/u/yegor256).
