### ISSUE TITLE
metrics summary and entire project summary

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#25]
Let's create summary numbers and a badge.

**Comment by yegor256** [comment]
@rultor release, tag is `0.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#25`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#25` is not in scope.
