### ISSUE TITLE
App.java:75-77: LCC metric has impediments (see puzzles...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#253]
The puzzle `118-16445758` from #118 has to be resolved:

https://github.com/yegor256/jpeek/blob/808514e6faae8f75c83a6e4aaeb6390d2abbfb75/src/main/java/org/jpeek/App.java#L75-L77

The puzzle was created by Alexander Menshikov on 27-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#253](https://github.com/yegor256/jpeek/issues/253) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#253](https://github.com/yegor256/jpeek/issues/253) assigned to @protagores[/z](https://www.0crat.com/u/protagores), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/98796eca-1f2e-4c73-8854-5c8acb4150bc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@protagores[/z](https://www.0crat.com/u/protagores) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Protagores** [comment]
@0crat wait for #252

**Comment by 0crat** [comment]
> @0crat wait for #252 ([here](https://github.com/yegor256/jpeek/issues/253#issuecomment-485714354))

@Protagores The impediment for [#253](https://github.com/yegor256/jpeek/issues/253) was registered successfully by @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by Nermeen78** [comment]
@0crat apply

**Comment by 0crat** [comment]
> @0crat apply  ([here](https://github.com/yegor256/jpeek/issues/253#issuecomment-497992401))

@Nermeen78 Can't understand "apply", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by Protagores** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/253#issuecomment-508724021))

@Protagores The user @protagores[/z](https://www.0crat.com/u/protagores) resigned from [#253](https://github.com/yegor256/jpeek/issues/253), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by 0crat** [comment]
The job [#253](https://github.com/yegor256/jpeek/issues/253) assigned to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/575a5440-d8fa-40b4-81ee-520f00e02450); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@thomas-melville[/z](https://www.0crat.com/u/thomas-melville) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#253](https://github.com/yegor256/jpeek/issues/253), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#253](https://github.com/yegor256/jpeek/issues/253) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/7763beb8-4873-481e-947f-d11c8d20e141); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#253](https://github.com/yegor256/jpeek/issues/253), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
The job [#253](https://github.com/yegor256/jpeek/issues/253) assigned to @dfrau32[/z](https://www.0crat.com/u/dfrau32), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/d5d19ade-909c-4cb1-a022-973f3fa0ff78); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @dfrau32[/z](https://www.0crat.com/u/dfrau32) resigned from [#253](https://github.com/yegor256/jpeek/issues/253), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by romach** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/253#issuecomment-536224961))

@romach This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#253](https://github.com/yegor256/jpeek/issues/253) is [in scope](http://www.zerocracy.com/policy.html#14) for 16mon
  * The role is `DEV`
  * The job is assigned to @romach[/z](https://www.0crat.com/u/romach) for [24hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @protagores[/z](https://www.0crat.com/u/protagores): User was resigned from the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @dfrau32[/z](https://www.0crat.com/u/dfrau32): User was resigned from the ticket
    * @baybatu[/z](https://www.0crat.com/u/baybatu): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23253%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@romach[/z](https://www.0crat.com/u/romach) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @romach[/z](https://www.0crat.com/u/romach) resigned from [#253](https://github.com/yegor256/jpeek/issues/253), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @romach[/z](https://www.0crat.com/u/romach)

**Comment by 0crat** [comment]
The job [#253](https://github.com/yegor256/jpeek/issues/253) assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/7a6a3529-9fe5-419a-acff-55c26fe5f948); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by GnusinPavel** [comment]
@0crat wait #252

**Comment by 0crat** [comment]
> @0crat wait #252 ([here](https://github.com/yegor256/jpeek/issues/253#issuecomment-539687509))

@GnusinPavel The impediment for [#253](https://github.com/yegor256/jpeek/issues/253) was registered successfully by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by GnusinPavel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/jpeek/issues/253#issuecomment-557807535))

@GnusinPavel This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#253](https://github.com/yegor256/jpeek/issues/253) is [in scope](http://www.zerocracy.com/policy.html#14) for 18mon
  * The role is `DEV`
  * The job is assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) for [2mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @protagores[/z](https://www.0crat.com/u/protagores): User was resigned from the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @dfrau32[/z](https://www.0crat.com/u/dfrau32): User was resigned from the ticket
    * @baybatu[/z](https://www.0crat.com/u/baybatu): User was resigned from the ticket
    * @romach[/z](https://www.0crat.com/u/romach): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23253%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#253](https://github.com/yegor256/jpeek/issues/253) assigned to @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/d19e9e8e-8968-4ccf-a0de-0dcbd245f421); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk) resigned from [#253](https://github.com/yegor256/jpeek/issues/253), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @volodymyrbondarchuk[/z](https://www.0crat.com/u/volodymyrbondarchuk)

**Comment by 0crat** [comment]
The job [#253](https://github.com/yegor256/jpeek/issues/253) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/ca7d47ba-be13-4f7c-9422-272b5fe29bec); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `118-16445758` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 27 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
