### ISSUE TITLE
SkeletonTest.java:39-43: Skeleton must be upgraded to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#261]
The puzzle `156-4fb50d79` from #156 has to be resolved:

https://github.com/yegor256/jpeek/blob/12575825f444153308126680a85c621a78123cad/src/test/java/org/jpeek/skeleton/SkeletonTest.java#L39-L43

The puzzle was created by rultor on 13-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#261](https://github.com/yegor256/jpeek/issues/261) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#261](https://github.com/yegor256/jpeek/issues/261) assigned to @humb1t[/z](https://www.0crat.com/u/humb1t), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/b8aae244-ee3c-4551-8d4e-e67b7015773f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/261#issuecomment-484805560))

@g4s8 This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#261](https://github.com/yegor256/jpeek/issues/261) is [in scope](http://www.zerocracy.com/policy.html#14) for 10mon
  * The role is `DEV`
  * The job is assigned to @humb1t[/z](https://www.0crat.com/u/humb1t) for [12hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23261%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@humb1t[/z](https://www.0crat.com/u/humb1t) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by humb1t** [comment]
@0crat wait for #321 approval

**Comment by 0crat** [comment]
> @0crat wait for #321 approval ([here](https://github.com/yegor256/jpeek/issues/261#issuecomment-486181286))

@humb1t The impediment for [#261](https://github.com/yegor256/jpeek/issues/261) was registered successfully by @humb1t[/z](https://www.0crat.com/u/humb1t)

**Comment by 0pdd** [comment]
The puzzle `156-4fb50d79` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @humb1t[/z](https://www.0crat.com/u/humb1t), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#261](https://github.com/yegor256/jpeek/issues/261) is now out of scope

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @humb1t[/z](https://www.0crat.com/u/humb1t)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)
