### ISSUE TITLE
Update README.md with location of valid intellij codestyle scheme.

### ISSUE THREAD

**Issue by gauee** [yegor256/jpeek#267]
I cannot find the location of valid IntelliJ code style scheme for that project. 
I imported the yegors [settings.jar](http://img.teamed.io/settings.jar) from [Strict Control of Java Code Quality](https://www.yegor256.com/2014/08/13/strict-code-quality-control.html) and after applied auto formatting I see that whole project changed for scheme _be_ and _Default_1_.

Having such information in REAMDE.md will be beneficial for new contributors.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@gauee we don't recommend auto-formatting in our projects, it's better to do it all manually, here is the reason: https://www.yegor256.com/2018/01/16/educational-aspect-of-static-analysis.html

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#267` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
