### ISSUE TITLE
http://i.jpeek.org/ is down

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/jpeek#271]
jpeek webpage at http://i.jpeek.org/ is down, showing the heroku default error page

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7JGJ00DP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#271` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
