### ISSUE TITLE
Automate jpeek analisys with maven plugin

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/jpeek#274]
`jpeek` should provide an maven plugin so we could run it automatically on each build.
Proposed features:
- `jpeek-maven-plugin` to be configured on project `pom.xml` file, and will collect metrics on maven builds (similar to `qulice-maven-plugin`), saving it from some directory on build path
- cohesion check: `jpeek-maven-plugin` will allow to set target values from cohesion metrics and will check report files generated on execution. Build can be configured to fail when target values are not met
- plugin should allow to ignore / exclude classes and metrics from cohesion check by pom configuration and by annotation configuration in files, like `qulice`/`checkstyle`/`PMD` plugins;

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7JGJ00DP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/jpeek/issues/274#issuecomment-623154095))

@paulodamaso The job [#274](https://github.com/yegor256/jpeek/issues/274) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/6a432f28-b1fa-45f8-8ad2-22fdb11a016a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#274](https://github.com/yegor256/jpeek/issues/274), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#274](https://github.com/yegor256/jpeek/issues/274) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/7f0e2c80-a6da-4f8a-bd03-0e0d936cfec4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso I'm not sure why 0crat assigned me this, maybe you should refuse then out it

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/274#issuecomment-630239936))

@paulodamaso The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#274](https://github.com/yegor256/jpeek/issues/274), please stop working. Reason for job resignation: Order was cancelled

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/274#issuecomment-630247696))

@paulodamaso Job `gh:yegor256/jpeek#274` is not assigned, can't get performer
