### ISSUE TITLE
LCOM4.xsl:60-62: LCOM4: need to finish implementing the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#294]
The puzzle `216-0c93d2e3` from #216 has to be resolved: 

https://github.com/yegor256/jpeek/blob/a0588eabe8dae3337baa22e930c7f0e346a722fb/src/main/resources/org/jpeek/metrics/LCOM4.xsl#L60-L62

The puzzle was created by rultor on 07-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#294](https://github.com/yegor256/jpeek/issues/294) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#294](https://github.com/yegor256/jpeek/issues/294) assigned to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/b9836056-47e6-4a16-97e7-b69e861dd62c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@thomas-melville[/z](https://www.0crat.com/u/thomas-melville) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#294](https://github.com/yegor256/jpeek/issues/294), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#294](https://github.com/yegor256/jpeek/issues/294) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/c067e044-d1c7-4297-9b8a-04f60698ca6d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@rajanamistry[/z](https://www.0crat.com/u/rajanamistry) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#294](https://github.com/yegor256/jpeek/issues/294), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
The job [#294](https://github.com/yegor256/jpeek/issues/294) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/ebcd3bbd-7af7-4829-bbf3-c71d390bb4d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `216-0c93d2e3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#294](https://github.com/yegor256/jpeek/issues/294) is now out of scope

**Comment by GnusinPavel** [comment]
@0crat status

**Comment by GnusinPavel** [comment]
@fabriciofx ping, please finish qa review

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/jpeek/issues/294#issuecomment-549714535))

@GnusinPavel This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#294](https://github.com/yegor256/jpeek/issues/294) is not in scope
  * The job is waiting quality review verdict by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for 1mon
  * @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23294%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)
