### ISSUE TITLE
Generate metrics.xml in pure Java, without XSLT

### ISSUE THREAD

**Issue by ilyakharlamov** [yegor256/jpeek#296]
The current architecture relies heavily on XSLT for data analysis.
If we want to implement issues like #204 with advanced semantic indexing such as ML, LSI, NLP
we'll have to use external Java libraries since it's very challenging to do complex calculations in pure XSLT.
So we need to have an option to generate an XML report by name, that is implemented in Java, not XSLT.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by danilomo** [comment]
The class [Report](https://github.com/yegor256/jpeek/blob/master/src/main/java/org/jpeek/Report.java) doesn't follow a [contract](https://www.yegor256.com/2014/11/20/seven-virtues-of-good-object.html). It's a concrete class that ties the report generation to the XSL implementation.

Refactoring with [extract interface](https://refactoring.com/catalog/extractInterface.html) should allow custom metrics to be implemented in Java rather than in XSL.

**Comment by ilyakharlamov** [comment]
@danilomo Yes, I think Report should become an interface and the current concrete class Report turned to XslReport or something

**Comment by danilomo** [comment]
@yegor256 

Some graph algorithms are extremely annoying to implement with XSL. They are doable, though, since you can have recursive templates, but nevertheless, it would be way easier to write them in Java.

So, I would like to know what do you think about this issue.

Thanks in advance.

**Comment by paulodamaso** [comment]
@ilyakharlamov How about making some performance tests to measure xml speed / efficiency and then implement some routines in java to compare both?

**Comment by ilyakharlamov** [comment]
@paulodamaso This issue is not about the performance. 
The original problem is that it's close to impossible to implement graph traversal algorithms that are needed for advanced semantic indexes, like depth-first search, A* algorithm, Dijkstra algorithm etc using XSLT. 
Better performance can be a nice bonus, but the real issue is the graph traversal.

**Comment by paulodamaso** [comment]
@ilyakharlamov Understood the problem. XSL was chosen because its performance, but as it does not have the required features it's time to move on to some more robust implementation.

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/296#issuecomment-483263742))

@paulodamaso Job [#296](https://github.com/yegor256/jpeek/issues/296) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by 0crat** [comment]
The job [#296](https://github.com/yegor256/jpeek/issues/296) assigned to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3ecb1dee-fa8c-4464-8811-39d744350652); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0crat** [comment]
The user @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) resigned from [#296](https://github.com/yegor256/jpeek/issues/296), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#296](https://github.com/yegor256/jpeek/issues/296) assigned to @monomonedula[/z](https://www.0crat.com/u/monomonedula), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a2dc3dd3-93f5-455f-a40f-962f7050ef50); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@paulodamaso @danilomo I agree that we should think about Java implementations of `Report`

**Comment by 0crat** [comment]
The user @monomonedula[/z](https://www.0crat.com/u/monomonedula) resigned from [#296](https://github.com/yegor256/jpeek/issues/296), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @monomonedula[/z](https://www.0crat.com/u/monomonedula)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#296](https://github.com/yegor256/jpeek/issues/296), see [§21](http://www.zerocracy.com/policy.html#21); @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
@rajanamistry[/z](https://www.0crat.com/u/rajanamistry) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#296](https://github.com/yegor256/jpeek/issues/296), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#296](https://github.com/yegor256/jpeek/issues/296), see [§21](http://www.zerocracy.com/policy.html#21); @uurl[/z](https://www.0crat.com/u/uurl) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
@uurl[/z](https://www.0crat.com/u/uurl) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#296](https://github.com/yegor256/jpeek/issues/296), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#296](https://github.com/yegor256/jpeek/issues/296), see [§21](http://www.zerocracy.com/policy.html#21); @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by HDouss** [comment]
@paulodamaso 0crat reports this ticket in my agenda. Is this ticket assigned to me?

**Comment by HDouss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/296#issuecomment-587427191))

@HDouss This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#296](https://github.com/yegor256/jpeek/issues/296) is [in scope](http://www.zerocracy.com/policy.html#14) for 10mon
  * The role is `DEV`
  * The job is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss) for [19hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov): This user reported the ticket
    * @ebercamargo[/z](https://www.0crat.com/u/ebercamargo): User was resigned from the ticket
    * @monomonedula[/z](https://www.0crat.com/u/monomonedula): User was resigned from the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @dfrau32[/z](https://www.0crat.com/u/dfrau32): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23296%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by HDouss** [comment]
@ilyakharlamov Please see PR #379

**Comment by HDouss** [comment]
@ilyakharlamov PR #379 merged. Please close the issue.

**Comment by HDouss** [comment]
@ilyakharlamov ping

**Comment by ilyakharlamov** [comment]
@HDouss the issue will be closed when it’s implemented (metrics.xml is generated in pure Java without xml/xsl). 
So far I see only #379 which is renaming of existing XSL class and hiding it behind te Report interface. Which is a step towards the right direction, but the feature has not been completed yet

**Comment by HDouss** [comment]
@ilyakharlamov I resolved the main part 
>So we need to have an option to generate an XML report by name, that is implemented in Java, not XSLT.
The option is now here. That's what can be done in 30min. I don't know if you/we should create separate issues for specific metrics to be implemented in Java, or if you have in mind any specific metric that absolutely must be implemented, I could add a puzzle.

**Comment by HDouss** [comment]
@paulodamaso any opinion here?

**Comment by paulodamaso** [comment]
@HDouss We need to have hooks / checkpoints which allows us to continue to break a complex task in many other micro-tasks. These hooks came in forma of puzzles in the code, and using them we will be able to know how much we still have to do and what is left to implement for our feature to be complete. I should have asked you to put these puzzles in the code before the merge. We need these puzzles, so could you please add them?

**Comment by HDouss** [comment]
@paulodamaso that's what I said in:
>The option is now here. That's what can be done in 30min. I don't know if you/we should create separate issues for specific metrics to be implemented in Java, or if you have in mind any specific metric that absolutely must be implemented, I could add a puzzle.

However the puzzle should be precise. Should we implement all the metrics in Java? Are they some must-have implementations in Java. I can't just say "implement some metrics" in Java.

**Comment by HDouss** [comment]
@paulodamaso puzzle added in PR #389

**Comment by 0pdd** [comment]
@ilyakharlamov the puzzle [#390](https://github.com/yegor256/jpeek/issues/390) is still not solved.

**Comment by HDouss** [comment]
@ilyakharlamov PR #389 added a puzzle and merged. Please close the issue.

**Comment by HDouss** [comment]
@ilyakharlamov ping

**Comment by HDouss** [comment]
@ilyakharlamov PR #389 merged. Please close the issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@ilyakharlamov 2 puzzles [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390).

**Comment by 0pdd** [comment]
@ilyakharlamov the puzzle [#397](https://github.com/yegor256/jpeek/issues/397) is still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396).

**Comment by 0pdd** [comment]
@ilyakharlamov the puzzle [#408](https://github.com/yegor256/jpeek/issues/408) is still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397).

**Comment by 0pdd** [comment]
@ilyakharlamov 2 puzzles [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408).

**Comment by 0pdd** [comment]
@ilyakharlamov 3 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416), [#417](https://github.com/yegor256/jpeek/issues/417) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412).

**Comment by 0pdd** [comment]
@ilyakharlamov 2 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@ilyakharlamov 3 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@ilyakharlamov 5 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440).

**Comment by 0pdd** [comment]
@ilyakharlamov 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444).

**Comment by 0pdd** [comment]
@ilyakharlamov 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459).

**Comment by 0pdd** [comment]
@ilyakharlamov 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472).

**Comment by 0pdd** [comment]
@ilyakharlamov 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#484](https://github.com/yegor256/jpeek/issues/484) are still not solved; solved: [#390](https://github.com/yegor256/jpeek/issues/390), [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473).
