### ISSUE TITLE
skeleton.xsd:31-33: Skeleton.xsd: remove method/@public....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#297]
The puzzle `188-d010c845` from #188 has to be resolved: 

https://github.com/yegor256/jpeek/blob/fd5879b0f86c2721853b4ee4b2801a429e52b615/src/main/resources/org/jpeek/xsd/skeleton.xsd#L31-L33

The puzzle was created by @Serranya on 04-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#297](https://github.com/yegor256/jpeek/issues/297) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#297](https://github.com/yegor256/jpeek/issues/297) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a34d534c-1dad-4aa4-835b-f96ad870c640); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@uurl[/z](https://www.0crat.com/u/uurl) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#297](https://github.com/yegor256/jpeek/issues/297), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
The job [#297](https://github.com/yegor256/jpeek/issues/297) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/d1436117-9825-45a9-a2c1-cb03b8cd1ed7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@rajanamistry[/z](https://www.0crat.com/u/rajanamistry) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#297](https://github.com/yegor256/jpeek/issues/297), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
The job [#297](https://github.com/yegor256/jpeek/issues/297) assigned to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3eb6ac17-ef47-4a58-a193-8b12bede6c4d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by GnusinPavel** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello  ([here](https://github.com/yegor256/jpeek/issues/297#issuecomment-539684256))

@GnusinPavel Hey, what's up, how is it going?

**Comment by GnusinPavel** [comment]
@0crat  wait #346

**Comment by 0crat** [comment]
> @0crat wait #346  ([here](https://github.com/yegor256/jpeek/issues/297#issuecomment-539684867))

@GnusinPavel @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) you can't register impediment for this job

**Comment by GnusinPavel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/jpeek/issues/297#issuecomment-539685330))

@GnusinPavel This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#297](https://github.com/yegor256/jpeek/issues/297) is [in scope](http://www.zerocracy.com/policy.html#14) for 9mon
  * The role is `DEV`
  * The job is assigned to @romach[/z](https://www.0crat.com/u/romach) for [22hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @baybatu[/z](https://www.0crat.com/u/baybatu): User was resigned from the ticket
    * @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23297%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@romach[/z](https://www.0crat.com/u/romach) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @romach[/z](https://www.0crat.com/u/romach) resigned from [#297](https://github.com/yegor256/jpeek/issues/297), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @romach[/z](https://www.0crat.com/u/romach)

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#297` is not assigned, can't get performer

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @romach[/z](https://www.0crat.com/u/romach)

**Comment by 0crat** [comment]
The job [#297](https://github.com/yegor256/jpeek/issues/297) assigned to @protagores[/z](https://www.0crat.com/u/protagores), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/e3b4a5ce-1386-4cd2-9183-a45e9719fb15); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Protagores** [comment]
@0crat wait for #343

**Comment by 0crat** [comment]
> @0crat wait for #343 ([here](https://github.com/yegor256/jpeek/issues/297#issuecomment-546378659))

@Protagores The impediment for [#297](https://github.com/yegor256/jpeek/issues/297) was registered successfully by @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by 0pdd** [comment]
The puzzle `188-d010c845` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#359](https://github.com/yegor256/jpeek/issues/359) is still not solved.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @protagores[/z](https://www.0crat.com/u/protagores), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#297](https://github.com/yegor256/jpeek/issues/297) is now out of scope

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#359](https://github.com/yegor256/jpeek/issues/359) is solved here.
