### ISSUE TITLE
NHD

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#3]
Let's implement NHD cohesion metric.

S. Counsell, S. Swift, and J. Crampton, “The interpretation
and utility of three cohesion metrics for object-oriented design,”
ACM Transactions on Software Engineering and Methodology
(TOSEM), vol. 15, no. 2, pp. 123–149, 2006.

PDF: https://www.researchgate.net/profile/Stephen_Swift/publication/220403868_The_interpretation_and_utility_of_three_cohesion_metrics_for_object-oriented_design/links/00b7d52d0fc90cb989000000/The-interpretation-and-utility-of-three-cohesion-metrics-for-object-oriented-design.pdf

**Comment by Sammers21** [comment]
@yegor256 is that right that we have CAMC metric implemented ? If so can we reuse binary Binary k*l matrix generated during its execution for calculating of NHD metric?

**Comment by yegor256** [comment]
@Sammers21 yes, CAMC metrics is implemented. Feel free to reuse the code, of course.

**Comment by memoyil** [comment]
@yegor256 You can close this issue

**Comment by yegor256** [comment]
@memoyil thanks a lot!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#3`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#3` is not in scope.
