### ISSUE TITLE
Fix Shippable CI support or remove it

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/jpeek#305]
Shippable CI support is broken. It needs add support to Ruby because fails to install pdd gem:
```
 gem install pdd
/root/fff46763-5e41-4b9b-8811-35d928519337.sh: line 86: gem: command not found
```
So, let fix it or remove Shippable. @paulodamaso WDYT?

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#305` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by fabriciofx** [comment]
Fixed.

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#305](https://github.com/yegor256/jpeek/issues/305) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
