### ISSUE TITLE
Upgrade to qulice 0.18

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/jpeek#308]
Let's update `qulice-maven-plugin` to version 0.18.*.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/308#issuecomment-478206180))

@paulodamaso Job [#308](https://github.com/yegor256/jpeek/issues/308) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#308](https://github.com/yegor256/jpeek/issues/308) assigned to @romach[/z](https://www.0crat.com/u/romach), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/2ee1763e-263d-489f-b1ed-77f4ff98510d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@romach[/z](https://www.0crat.com/u/romach) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @romach[/z](https://www.0crat.com/u/romach) resigned from [#308](https://github.com/yegor256/jpeek/issues/308), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @romach[/z](https://www.0crat.com/u/romach)

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#308` is not assigned, can't get performer

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @romach[/z](https://www.0crat.com/u/romach)

**Comment by 0crat** [comment]
The job [#308](https://github.com/yegor256/jpeek/issues/308) assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/48630286-0221-4879-a647-e6ea9350fa77); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#308` already assigned to @gnusinpavel, can't assign to @gnusinpavel

**Comment by GnusinPavel** [comment]
@0crat  wait to #351

**Comment by 0crat** [comment]
> @0crat wait to #351 ([here](https://github.com/yegor256/jpeek/issues/308#issuecomment-552117917))

@GnusinPavel The impediment for [#308](https://github.com/yegor256/jpeek/issues/308) was registered successfully by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#357](https://github.com/yegor256/jpeek/issues/357) is still not solved.

**Comment by GnusinPavel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/jpeek/issues/308#issuecomment-556028729))

@GnusinPavel This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#308](https://github.com/yegor256/jpeek/issues/308) is [in scope](http://www.zerocracy.com/policy.html#14) for 8mon
  * The role is `DEV`
  * The job is assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) for [12days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): This user reported the ticket
    * @romach[/z](https://www.0crat.com/u/romach): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23308%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by GnusinPavel** [comment]
@fabriciofx can you close this ticket please? )

**Comment by fabriciofx** [comment]
@GnusinPavel yep.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#308](https://github.com/yegor256/jpeek/issues/308) is now out of scope

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/308#issuecomment-556423973))

@fabriciofx This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#308](https://github.com/yegor256/jpeek/issues/308) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23308%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#308` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@fabriciofx the only puzzle [#357](https://github.com/yegor256/jpeek/issues/357) is solved here.
