### ISSUE TITLE
Add support to cactoos-matchers

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/jpeek#309]
Let's add support to `cactoos-matchers` in tests. It will improve the tests in a more pure OO way.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@paulodamaso assign to me

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/309#issuecomment-478206212))

@paulodamaso Job [#309](https://github.com/yegor256/jpeek/issues/309) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#309](https://github.com/yegor256/jpeek/issues/309) assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1ceb08fe-72d3-4e9e-ad78-cce2e71e7d47); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by GnusinPavel** [comment]
@fabriciofx can you provide more details what actually need supposed to do?

**Comment by fabriciofx** [comment]
@GnusinPavel  you must replace usage of `MatcherAssert.assertThat` withcAssertion from `cactoos-matchers`. Once there is no more usage of `MatcherAssert.assertThat`, add the signature of `MatcherAssert.assertThat` to `forbidden-apis.txt`.

**Comment by GnusinPavel** [comment]
@0crat wait for #353

**Comment by 0crat** [comment]
> @0crat wait for #353 ([here](https://github.com/yegor256/jpeek/issues/309#issuecomment-553622062))

@GnusinPavel The impediment for [#309](https://github.com/yegor256/jpeek/issues/309) was registered successfully by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by GnusinPavel** [comment]
@fabriciofx close that ticket ,please )

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#309](https://github.com/yegor256/jpeek/issues/309) is now out of scope

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/309#issuecomment-557302289))

@fabriciofx This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#309](https://github.com/yegor256/jpeek/issues/309) is not in scope
  * The job is waiting quality review verdict by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for 2hr
  * @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23309%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@GnusinPavel please, improve the description's PR adding issue number (#issue) in it.

**Comment by GnusinPavel** [comment]
@fabriciofx done

**Comment by fabriciofx** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)
