### ISSUE TITLE
Update PR guidelines in PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/jpeek#312]
Cactoos project [updated PR guidelines](https://github.com/yegor256/cactoos/commit/b8bf44e4ddbe0b5a9b13e006208327358931c0cd) and I think it would be nice if we do that too. The new rules are:

- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/312#issuecomment-478206256))

@paulodamaso Job [#312](https://github.com/yegor256/jpeek/issues/312) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#312](https://github.com/yegor256/jpeek/issues/312) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a9da016f-794d-4afd-a087-c70f9f47c536); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by mohamednizar** [comment]
@fabriciofx , this was done, why the ticket still not closed ?

**Comment by mohamednizar** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/312#issuecomment-552388404))

@mohamednizar The impediment for [#312](https://github.com/yegor256/jpeek/issues/312) was registered successfully by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by fabriciofx** [comment]
Closed by #350

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by fabriciofx** [comment]
Closed by #350

**Comment by mohamednizar** [comment]
@0crat continue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat continue  ([here](https://github.com/yegor256/jpeek/issues/312#issuecomment-552726213))

@mohamednizar Job [#312](https://github.com/yegor256/jpeek/issues/312) is not on hold, no impediment to remove

**Comment by 0crat** [comment]
The job [#312](https://github.com/yegor256/jpeek/issues/312) is now out of scope

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)
