### ISSUE TITLE
Broken RawGit links

### ISSUE THREAD

**Issue by wholegroup** [yegor256/jpeek#315]
RawGit is now in a sunset phase and will soon shut down ([proof](https://rawgit.com/)). 
All links have to be replaced.
e.g. to jsDelivr.com

https://github.com/yegor256/jpeek/blob/master/src/main/resources/org/jpeek/xsl/matrix.xsl
https://github.com/yegor256/jpeek/blob/master/src/main/resources/org/jpeek/web/layout.xsl
https://github.com/yegor256/jpeek/blob/master/src/main/resources/org/jpeek/templates.xsl

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@wholegroup[/z](https://www.0crat.com/u/wholegroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7JGJ00DP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by paulodamaso** [comment]
@wholegroup Let's use the links shown on [tacit framework](https://github.com/yegor256/tacit)

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-478206501))

@paulodamaso Job [#315](https://github.com/yegor256/jpeek/issues/315) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @wholegroup[/z](https://www.0crat.com/u/wholegroup)

**Comment by 0crat** [comment]
The job [#315](https://github.com/yegor256/jpeek/issues/315) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/c11388f0-8aba-4976-95aa-5b3304e66a43); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by mohamednizar** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-554483706))

@mohamednizar The impediment for [#315](https://github.com/yegor256/jpeek/issues/315) was registered successfully by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by mohamednizar** [comment]
@0crat continue

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-555555575))

@mohamednizar @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) continued working on job [#315](https://github.com/yegor256/jpeek/issues/315)

**Comment by mohamednizar** [comment]
@paulodamaso  , are there any reviews QA tasks for this ticket ? shall we close this ticket ?

**Comment by paulodamaso** [comment]
@mohamednizar The review happened in https://github.com/yegor256/jpeek/pull/354 and was made by me; there was nothing to complain so I merged it right away. Now, the next step is to ask the issue opener (@wholegroup) to close the issue if the solution is ok.

**Comment by paulodamaso** [comment]
@wholegroup Please take a look and close the issue if it was solved.

**Comment by mohamednizar** [comment]
@0crat wait

**Comment by wholegroup** [comment]
@mohamednizar thanks

**Comment by mohamednizar** [comment]
@0crat continue

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-555843807))

@mohamednizar The impediment for [#315](https://github.com/yegor256/jpeek/issues/315) was registered successfully by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-555989349))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#315](https://github.com/yegor256/jpeek/issues/315) is [in scope](http://www.zerocracy.com/policy.html#14) for 8mon
  * The role is `DEV`
  * The job is assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) for [6days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @wholegroup[/z](https://www.0crat.com/u/wholegroup): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23315%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-555976943))

@mohamednizar @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) continued working on job [#315](https://github.com/yegor256/jpeek/issues/315)

**Comment by mohamednizar** [comment]
@paulodamaso , who is confirming the quality if the work?

**Comment by paulodamaso** [comment]
@mohamednizar I will

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-556847156))

@paulodamaso There is no quality review for [#315](https://github.com/yegor256/jpeek/issues/315), no performer

**Comment by mohamednizar** [comment]
@paulodamaso , can we take the task out from the scope ?

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-557369781))

@paulodamaso The job [#315](https://github.com/yegor256/jpeek/issues/315) is now out of scope

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-557390854))

@fabriciofx This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#315](https://github.com/yegor256/jpeek/issues/315) is not in scope
  * The job is waiting quality review verdict by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for 43min
  * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23315%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-557424096))

@fabriciofx The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/315#issuecomment-557424096))

@fabriciofx The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)
