### ISSUE TITLE
Optimal way of making Xembler work with Report is not obvious

### ISSUE THREAD

**Issue by Protagores** [yegor256/jpeek#322]
As per #227:
> Refactor towards a simpler solution that ideally would just require one or two Xembly instructions add the required attribute.

The problem with using Xembly here is summed up by the following (see https://github.com/yegor256/jpeek/pull/196#discussion_r170341425):
> `Xembler` works with nodes. Can't set the required attribute on the node returned by the `XML` resulting from transforming the skeleton into `metric` because it's a document node (throws error "Cannot cast ...DocumentImpl to ...Element").

Because it is not obvious what would a better solution look like exactly, I think this separate issue is needed so that the scope of #227 itself wouldn’t go beyond 30 minutes. We probably need to make a design decision here first.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by Protagores** [comment]
@yegor256 @paulodamaso @llorllale Apparently there _is_ a possible (relatively) clean solution. What was really needed here is to point the cursor to the `metric` element via an `XPATH` instruction first.

See #325

**Comment by llorllale** [comment]
@Protagores I see that you've successfully managed to add the attribute with Xembly; what I don't understand is how this is any less "weird" (as per [Yegor](https://github.com/yegor256/jpeek/pull/196#discussion_r169624018)) than simply making use of the existing `XSLChain`.

I'll let @yegor256 decide.

**Comment by Protagores** [comment]
Proposed solution already accepted and merged. Closing this.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#322` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
