### ISSUE TITLE
Restrict usage of `@Test(expected=...)` in favour of OO way

### ISSUE THREAD

**Issue by humb1t** [yegor256/jpeek#323]
As was mentioned in PR review https://github.com/yegor256/jpeek/pull/321#discussion_r277674648 it's prohibited to use `expected` parameter of JUnit test annotation in favour of `JUnit5-compatible, OO assertions`.

To don't check it manually and don't allow it's usage in jpeek code base it should be added to static analyze rules.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@humb1t How about we update all Junit to junit 5? This way we coukld get rid of `expected` once and for all?

**Comment by humb1t** [comment]
@paulodamaso why not, @ilyakharlamov - what do you think?

**Comment by ilyakharlamov** [comment]
@humb1t sure - upgrade to JUnit 5, why not.

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/323#issuecomment-486426354))

@paulodamaso Job [#323](https://github.com/yegor256/jpeek/issues/323) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @humb1t[/z](https://www.0crat.com/u/humb1t)

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/323#issuecomment-552741398))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#323](https://github.com/yegor256/jpeek/issues/323) is [in scope](http://www.zerocracy.com/policy.html#14) for 7mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @humb1t[/z](https://www.0crat.com/u/humb1t): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23323%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#323](https://github.com/yegor256/jpeek/issues/323) assigned to @englishman[/z](https://www.0crat.com/u/englishman), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/ac9c6bb5-f4a2-4ebf-9f10-d569dcf88212); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@englishman[/z](https://www.0crat.com/u/englishman) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @englishman[/z](https://www.0crat.com/u/englishman)

**Comment by 0crat** [comment]
The job [#323](https://github.com/yegor256/jpeek/issues/323) assigned to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/e8a0c847-066c-4c09-969f-150630be2913); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#323](https://github.com/yegor256/jpeek/issues/323), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The job [#323](https://github.com/yegor256/jpeek/issues/323) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/e42a995e-896c-4406-861a-85e99859723c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@humb1t Please see PR #378

**Comment by 0pdd** [comment]
@humb1t 2 puzzles [#380](https://github.com/yegor256/jpeek/issues/380), [#381](https://github.com/yegor256/jpeek/issues/381) are still not solved.

**Comment by HDouss** [comment]
@humb1t PR #378 is merged. Please close the issue.

**Comment by HDouss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/323#issuecomment-588378833))

@HDouss This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#323](https://github.com/yegor256/jpeek/issues/323) is [in scope](http://www.zerocracy.com/policy.html#14) for 10mon
  * The role is `DEV`
  * The job is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @humb1t[/z](https://www.0crat.com/u/humb1t): This user reported the ticket
    * @englishman[/z](https://www.0crat.com/u/englishman): User was resigned from the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23323%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by HDouss** [comment]
@humb1t PR #378 is reviewed and merged. Please close the issue.

**Comment by humb1t** [comment]
@0crat close

**Comment by 0crat** [comment]
> @0crat close ([here](https://github.com/yegor256/jpeek/issues/323#issuecomment-588420161))

@humb1t Can't understand "close", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `elect` Trigger election for ticket
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by HDouss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/323#issuecomment-588453980))

@HDouss This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#323](https://github.com/yegor256/jpeek/issues/323) is not in scope
  * The job is waiting quality review verdict by @sereshqua[/z](https://www.0crat.com/u/sereshqua) for 3min
  * @hdouss[/z](https://www.0crat.com/u/hdouss) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23323%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@humb1t 2 puzzles [#381](https://github.com/yegor256/jpeek/issues/381), [#388](https://github.com/yegor256/jpeek/issues/388) are still not solved; solved: [#380](https://github.com/yegor256/jpeek/issues/380).

**Comment by 0pdd** [comment]
@humb1t the puzzle [#400](https://github.com/yegor256/jpeek/issues/400) is still not solved; solved: [#380](https://github.com/yegor256/jpeek/issues/380), [#381](https://github.com/yegor256/jpeek/issues/381), [#388](https://github.com/yegor256/jpeek/issues/388).

**Comment by 0pdd** [comment]
@humb1t all 4 puzzles are solved here: [#380](https://github.com/yegor256/jpeek/issues/380), [#381](https://github.com/yegor256/jpeek/issues/381), [#388](https://github.com/yegor256/jpeek/issues/388), [#400](https://github.com/yegor256/jpeek/issues/400).
