### ISSUE TITLE
Update maven-compiler-plugin and fix bug on it to allow incremental compilation

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/jpeek#324]
Let's update `maven-compiler-plugin` to `3.8.0` version and fix a bug in this plugin which doesn't allow incremental compilation that increase compile and running time. To fix both we need change `pom.xml` to:
```
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.0</version>
  <configuration>
    <source>1.8</source>
    <target>1.8</target>
    <useIncrementalCompilation>false</useIncrementalCompilation>
  </configuration>
</plugin>
```
Please, pay attention to `<version>` and `<useIncrementalCompilation>` tag.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@fabriciofx Agree, thanks, good catch!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/324#issuecomment-486369411))

@paulodamaso Job [#324](https://github.com/yegor256/jpeek/issues/324) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/324#issuecomment-552741245))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#324](https://github.com/yegor256/jpeek/issues/324) is [in scope](http://www.zerocracy.com/policy.html#14) for 7mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23324%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#324](https://github.com/yegor256/jpeek/issues/324) assigned to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/d980e114-65ac-4811-bf77-24035f80141c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#324` is not assigned, can't get performer

**Comment by 0crat** [comment]
The user @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) resigned from [#324](https://github.com/yegor256/jpeek/issues/324), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0crat** [comment]
The job [#324](https://github.com/yegor256/jpeek/issues/324) assigned to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/fc2a17ed-47d6-473f-a1af-747aada1e658); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@akryvtsun[/z](https://www.0crat.com/u/akryvtsun) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @akryvtsun[/z](https://www.0crat.com/u/akryvtsun) resigned from [#324](https://github.com/yegor256/jpeek/issues/324), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun)

**Comment by 0crat** [comment]
The job [#324](https://github.com/yegor256/jpeek/issues/324) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/60e07779-26e6-4a8e-8507-b4a00c98f2b0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat assign @akryvtsun

**Comment by 0crat** [comment]
> @0crat assign @akryvtsun ([here](https://github.com/yegor256/jpeek/issues/324#issuecomment-573698917))

@paulodamaso There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@9c2ebbbaf9da, thread: PQ-C7JGJ00DP
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [comment, job, issue, repo, cause, _parent_sig, flow, login]
```

[0.50.38](https://github.com/zerocracy/farm): CID: [2e50efe4-a814-4da8-a94f-c4852f47a4ca](https://www.0crat.com/footprint/C7JGJ00DP/2e50efe4-a814-4da8-a94f-c4852f47a4ca), Type: "Order was canceled"

**Comment by 0crat** [comment]
> @0crat assign @akryvtsun ([here](https://github.com/yegor256/jpeek/issues/324#issuecomment-573698917))

@paulodamaso The job [#324](https://github.com/yegor256/jpeek/issues/324) assigned to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/9699c98b-5a55-4056-8548-6454990d5587); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @akryvtsun[/z](https://www.0crat.com/u/akryvtsun) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The user @akryvtsun[/z](https://www.0crat.com/u/akryvtsun) resigned from [#324](https://github.com/yegor256/jpeek/issues/324), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@d43b1184c029, thread: PQ-C7JGJ00DP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/jpeek#324] declared for identity constraint of element "speed".
```

[0.50.40](https://github.com/zerocracy/farm): CID: [e7f510fa-6640-4ad2-b6c2-9faeadb756da](https://www.0crat.com/footprint/C7JGJ00DP/e7f510fa-6640-4ad2-b6c2-9faeadb756da), Type: "Order was canceled"

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun)

**Comment by 0crat** [comment]
The job [#324](https://github.com/yegor256/jpeek/issues/324) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/80b5f3e2-644a-497a-9b2a-aecb67a29544); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@fabriciofx PR #367 is already merged. Please close this issue.

**Comment by paulodamaso** [comment]
@HDouss Thank you!

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by HDouss** [comment]
@fabriciofx ping

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/324#issuecomment-587957344))

@paulodamaso Job `gh:yegor256/jpeek#324` is not assigned, can't get performer

**Comment by HDouss** [comment]
@paulodamaso are we waiting for QA here? It doesn't seem @fabriciofx is available

**Comment by HDouss** [comment]
> @0crat refuse

@paulodamaso Just curious..can you refuse a job that is not assigned to you?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/324#issuecomment-588053940); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by paulodamaso** [comment]
> > @0crat refuse
> 
> @paulodamaso Just curious..can you refuse a job that is not assigned to you?

Not really. I'm trying to remove this job from @fabriciofx, so @0crat assign it to another QA

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/324#issuecomment-588232539); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by paulodamaso** [comment]
@0crat assign @sereshqua

**Comment by 0crat** [comment]
> @0crat assign @sereshqua ([here](https://github.com/yegor256/jpeek/issues/324#issuecomment-588234452))

@paulodamaso Job [#324](https://github.com/yegor256/jpeek/issues/324) is closed, can't start order

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)
