### ISSUE TITLE
"FAQ for Newcomers" is out of date - wallet is created automatically, there is no need to "Change payment method"

### ISSUE THREAD

**Issue by ideas-into-software** [yegor256/jpeek#328]
"FAQ for Newcomers" (http://www.zerocracy.com/faq.html) is out of date. 

Paragraph: (...) Now, talk to our Telegram bot: @zerocrat_bot. Ask him to change your payment method. (...) would need to be re-written to mention that wallet is created automatically. There's no 'zerocrat_bot' command which allows to change payment method since this is done automatically, only rate is changed.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@ideas-into-software[/z](https://www.0crat.com/u/ideas-into-software) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7JGJ00DP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ideas-into-software** [comment]
sorry, wrong board

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#328` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
