### ISSUE TITLE
heavy artifacts don't build reports

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#33]
Try http://i.jpeek.org/com.google.guava/guava/index.html Most likely it's too big, that's why the delay and then application error.

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.4`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#33`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#33` is not in scope.
