### ISSUE TITLE
PDF files in `/papers` directory should have meaningful names!

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/jpeek#333]
While working on some issues about implementing metrics, I found myself obligated to come back to each issue/comment where a **research paper** was mentioned -every time I need to read about a metric- because I can't and I don't have to remember those cryptic names for PDFs in `/papers` directory! and I found that distracting and time wasting. So I suggest renaming the PDFs related to some metric with relevant and meaningful names.
eg: papers/izadkhah17.pdf is mentioned some issues about LORM, maybe a good name would be izadkhah17_LORM.pdf

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@fellahi-ali We have a section at the readme about this, but I think it's outdated: https://github.com/yegor256/jpeek#cohesion-metrics . So I propose to update this section with the documents present in `/papers`. Then we should use the readme section to refer to the documents instead the `/papers` folder. WDYT?

**Comment by fellahi-ali** [comment]
@paulodamaso Sure! The readme should be updated by every one how adds new PDF to `/papers` or any other reference, but my initial concerne to give those PDFs meaningful name is to facilitate thier exploration directly from the IDE without the need to refer to other things.

**Comment by paulodamaso** [comment]
@fellahi-ali I see. I think that's a good idea

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/333#issuecomment-528959441))

@paulodamaso Job [#333](https://github.com/yegor256/jpeek/issues/333) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fellahi-ali[/z](https://www.0crat.com/u/fellahi-ali)

**Comment by 0crat** [comment]
The job [#333](https://github.com/yegor256/jpeek/issues/333) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/54219699-15e8-433e-925f-636118f94bea); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#333](https://github.com/yegor256/jpeek/issues/333), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#333](https://github.com/yegor256/jpeek/issues/333) assigned to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/4219e52b-57c0-4251-b483-5bcb04fd8eeb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@akryvtsun[/z](https://www.0crat.com/u/akryvtsun) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun)

**Comment by 0crat** [comment]
The user @akryvtsun[/z](https://www.0crat.com/u/akryvtsun) resigned from [#333](https://github.com/yegor256/jpeek/issues/333), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#333](https://github.com/yegor256/jpeek/issues/333) assigned to @englishman[/z](https://www.0crat.com/u/englishman), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/bca6df14-a47c-45d8-af93-d5db07a48fd5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @englishman[/z](https://www.0crat.com/u/englishman)

**Comment by HDouss** [comment]
@0crat status

**Comment by HDouss** [comment]
@fellahi-ali PR #383 resolves the issue. Please note that the paper izadkhah17.pdf was not renamed because it does not introduce any new metric.

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/333#issuecomment-588297895))

@HDouss This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#333](https://github.com/yegor256/jpeek/issues/333) is [in scope](http://www.zerocracy.com/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss) for [2hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @fellahi-ali[/z](https://www.0crat.com/u/fellahi-ali): This user reported the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @akryvtsun[/z](https://www.0crat.com/u/akryvtsun): User was resigned from the ticket
    * @englishman[/z](https://www.0crat.com/u/englishman): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23333%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by HDouss** [comment]
@fellahi-ali PR #383 merged. Please close this issue.

**Comment by fellahi-ali** [comment]
Done! Thanks very much

**Comment by 0crat** [comment]
Job was finished in 24 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
