### ISSUE TITLE
Travis build doesn't work anymore

### ISSUE THREAD

**Issue by GnusinPavel** [yegor256/jpeek#338]
It seems can't install java 8
```
Worker information
hostname: 5bd0b748-6b71-40e6-8cc5-b44d3a644087@1.worker-org-7d4f67b9bb-vq29w.gce-production-1
version: v6.2.1 https://github.com/travis-ci/worker/tree/4e3246c044eb4915c2378ffacd0b3d3ed0136bba
instance: travis-job-eceb62d0-f5ee-4554-8372-cc38390a2010 travis-ci-sardonyx-xenial-1565528588-0c06deb6 (via amqp)
startup: 6.68226005s
0.19s0.01s0.00s0.01s
system_info
Build system information
Build language: java
Build group: stable
Build dist: xenial
Build id: 591660119
Job id: 591660120
Runtime kernel version: 4.15.0-1037-gcp
travis-build version: beba64be6
Build image provisioning date and time
Sun Aug 11 13:28:49 UTC 2019
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
Systemd Version
systemd 229
Cookbooks Version
790f512 https://github.com/travis-ci/travis-cookbooks/tree/790f512
git version
git version 2.22.0
bash version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
clang version
clang version 7.0.0 (tags/RELEASE_700/final)
jq version
jq-1.5
bats version
Bats 0.4.0
shellcheck version
0.6.0
shfmt version
v2.6.3
ccache version
3.2.4
cmake version
cmake version 3.12.4
heroku version
heroku/7.27.1 linux-x64 node-v11.14.0
imagemagick version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2019-06-15 http://www.imagemagick.org
md5deep version
4.4
mercurial version
version 4.8
mysql version
mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
openssl version
OpenSSL 1.0.2g  1 Mar 2016
packer version
1.3.3
postgresql client version
psql (PostgreSQL) 10.10 (Ubuntu 10.10-1.pgdg16.04+1)
ragel version
Ragel State Machine Compiler version 6.8 Feb 2013
sudo version
1.8.16
gzip version
gzip 1.6
zip version
Zip 3.0
vim version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 07 2019 15:35:43)
iptables version
iptables v1.6.0
curl version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
wget version
GNU Wget 1.17.1 built on linux-gnu.
rsync version
rsync  version 3.1.1  protocol version 31
gimme version
v1.5.3
nvm version
0.34.0
perlbrew version
/home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.86
phpenv version
rbenv 1.1.2-2-g4e92322
rvm version
rvm 1.29.9 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
default ruby version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
CouchDB version
couchdb 1.6.1
ElasticSearch version
5.5.0
Installed Firefox version
firefox 63.0.1
MongoDB version
MongoDB 4.0.12
PhantomJS version
2.1.1
Pre-installed PostgreSQL versions
9.4.24
9.5.19
9.6.15
Redis version
redis-server 5.0.5
Pre-installed Go versions
1.11.1
ant version
Apache Ant(TM) version 1.9.6 compiled on July 20 2018
mvn version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T18:41:47Z)
gradle version
Gradle 5.1.1!
lein version
Leiningen 2.9.1 on Java 11.0.2 OpenJDK 64-Bit Server VM
Pre-installed Node.js versions
v10.16.2
v11.0.0
v4.9.1
v6.17.1
v8.12.0
v8.16.0
v8.9
phpenv versions
  system
  5.6
  5.6.40
  7.1
  7.1.27
  7.2
* 7.2.15 (set by /home/travis/.phpenv/version)
  hhvm
  hhvm-stable
composer --version
Composer version 1.8.4 2019-02-11 10:52:10
Pre-installed Ruby versions
ruby-2.3.8
ruby-2.4.5
ruby-2.5.3
0.01s0.01s4.97s0.28s0.07s0.00s0.05s0.00s0.01s0.01s0.01s0.01s0.01s0.00s0.00s0.03s0.00s0.02s0.44s0.00s0.00s0.00s0.01s0.01s0.12s0.00s0.94s0.00s0.00s0.05s0.00s2.92s0.00s2.39s
docker_mtu
resolvconf
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-09-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@GnusinPavel it is an error indeed, thanks

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/338#issuecomment-537725796))

@paulodamaso Job [#338](https://github.com/yegor256/jpeek/issues/338) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by mohamednizar** [comment]
Added a fix for this refer : #344

**Comment by paulodamaso** [comment]
@0crat assign @mohamednizar

**Comment by 0crat** [comment]
> @0crat assign @mohamednizar  ([here](https://github.com/yegor256/jpeek/issues/338#issuecomment-538515653))

@paulodamaso The job [#338](https://github.com/yegor256/jpeek/issues/338) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/764641d9-1f89-4506-a307-6a37e698758a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/338#issuecomment-538722021))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#338](https://github.com/yegor256/jpeek/issues/338) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23338%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by mohamednizar** [comment]
@GnusinPavel , The problem is resolved, can you close the issue ?

**Comment by GnusinPavel** [comment]
yep

**Comment by 0crat** [comment]
Job was finished in 39 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#338](https://github.com/yegor256/jpeek/issues/338) is now out of scope

**Comment by mohamednizar** [comment]
@fabriciofx , can you please do the reviews ?

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/338#issuecomment-538959312))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#338](https://github.com/yegor256/jpeek/issues/338) is not in scope
  * The job is waiting quality review verdict by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for 1days
  * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23338%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by mohamednizar** [comment]
@0crat status , I have already have negative points for this ticket, @paulodamaso please do the needful.

**Comment by 0crat** [comment]
> @0crat status , I have already have negative points for this ticket, @paulodamaso please do the n... ([here](https://github.com/yegor256/jpeek/issues/338#issuecomment-544621057))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#338](https://github.com/yegor256/jpeek/issues/338) is not in scope
  * The job is waiting quality review verdict by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for 15days
  * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23338%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@fabriciofx ping

**Comment by paulodamaso** [comment]
@mohamednizar You didn't received any penalty for this one yet, and the PR #344 is waiting for corrections pointed by QA.

**Comment by mohamednizar** [comment]
@fabriciofx any updates ?

**Comment by paulodamaso** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/338#issuecomment-552011484))

@fabriciofx This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#338](https://github.com/yegor256/jpeek/issues/338) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23338%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/338#issuecomment-552012781))

@fabriciofx There is no quality review for [#338](https://github.com/yegor256/jpeek/issues/338), no performer
