### ISSUE TITLE
> @Jekeam we're using java 8, as described in pom.XML

### ISSUE THREAD

**Issue by jekeam** [yegor256/jpeek#342]
> @Jekeam we're using java 8, as described in pom.XML
> 
> https://github.com/yegor256/jpeek/blob/c438906b581d2956eb52b320ffb3ed9eb5d1895c/pom.xml#L222

Thanks, why Maven did not install the correct version of Java automatically? Why did he use my local version of Java? Where can I read how it works?

_Originally posted by @Jekeam in https://github.com/yegor256/jpeek/issues/340#issuecomment-537796808_

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@jekeam[/z](https://www.0crat.com/u/jekeam) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7JGJ00DP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by mohamednizar** [comment]
@Jekeam change the following lines not the java version ,
```
  <artifactId>jacoco-maven-plugin</artifactId>
       <version>0.7.8</version> <-- change to this --> 
```
and 
```
   <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId> 
      <version>7.2</version>  <-- change to this --> 
    </dependency>
```

Hope this would help to you.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#342` is not assigned, can't get performer
