### ISSUE TITLE
Main.java:45-48: Due to introduce new version of qulice...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#357]
The puzzle `308-016448ee` from #308 has to be resolved: 

https://github.com/yegor256/jpeek/blob/a239998cbb18965cd1d6923abbc694c9da3d04cc/src/main/java/org/jpeek/Main.java#L45-L48

The puzzle was created by Gnusin Pavel on 19-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#357](https://github.com/yegor256/jpeek/issues/357) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#357](https://github.com/yegor256/jpeek/issues/357), see [§21](http://www.zerocracy.com/policy.html#21); @uurl[/z](https://www.0crat.com/u/uurl) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#357](https://github.com/yegor256/jpeek/issues/357), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#357](https://github.com/yegor256/jpeek/issues/357), see [§21](http://www.zerocracy.com/policy.html#21); @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#357](https://github.com/yegor256/jpeek/issues/357), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#357](https://github.com/yegor256/jpeek/issues/357), see [§21](http://www.zerocracy.com/policy.html#21); @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#357](https://github.com/yegor256/jpeek/issues/357), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by dgarus** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/357#issuecomment-585625685))

@dgarus This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#357](https://github.com/yegor256/jpeek/issues/357) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @dgarus[/z](https://www.0crat.com/u/dgarus) for [15hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @dfrau32[/z](https://www.0crat.com/u/dfrau32): User was resigned from the ticket
    * @baybatu[/z](https://www.0crat.com/u/baybatu): User was resigned from the ticket
    * @englishman[/z](https://www.0crat.com/u/englishman): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23357%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by dgarus** [comment]
@paulodamaso Hi! We cannot remove the 'since' tag because it is mandatory. 
Could you change the task description?

**Comment by dgarus** [comment]
@0crat wait

**Comment by paulodamaso** [comment]
@dgarus We don't need it, just make your PR and explain this on the description

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/357#issuecomment-585774107))

@dgarus The impediment for [#357](https://github.com/yegor256/jpeek/issues/357) was registered successfully by @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by 0pdd** [comment]
The puzzle `308-016448ee` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dgarus[/z](https://www.0crat.com/u/dgarus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @dgarus[/z](https://www.0crat.com/u/dgarus)
