### ISSUE TITLE
SkeletonTest.java:38-43: Skeleton must be upgraded to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#358]
The puzzle `156-7b4862fe` from #156 has to be resolved: 

https://github.com/yegor256/jpeek/blob/a239998cbb18965cd1d6923abbc694c9da3d04cc/src/test/java/org/jpeek/skeleton/SkeletonTest.java#L38-L43

The puzzle was created by Mohamed Nizar on 09-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#358](https://github.com/yegor256/jpeek/issues/358) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#358](https://github.com/yegor256/jpeek/issues/358) assigned to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/c0dbbace-4e6f-496e-ae40-d99815728797); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#358` already assigned to @thomas-melville, can't assign to @thomas-melville

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#358](https://github.com/yegor256/jpeek/issues/358), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The job [#358](https://github.com/yegor256/jpeek/issues/358) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/aefd064f-8d3c-462e-9769-1bd24a816f56); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#358](https://github.com/yegor256/jpeek/issues/358), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
The job [#358](https://github.com/yegor256/jpeek/issues/358) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/fc2acb59-7b91-441e-aaf5-f399c70eb429); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#358](https://github.com/yegor256/jpeek/issues/358), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by dgarus** [comment]
@paulodamaso Is this issue actual?
The findFieldWithQualifiedName test doesn't have "ignore" annotation, and he is green.

**Comment by paulodamaso** [comment]
@dgarus Looks like a stale puzzle. Just remove it and we're done

**Comment by 0pdd** [comment]
The puzzle `156-7b4862fe` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @dgarus[/z](https://www.0crat.com/u/dgarus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
