### ISSUE TITLE
XmlClassTest.java:85-86: this method appears three times...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#359]
The puzzle `297-5540e446` from #297 has to be resolved: 

https://github.com/yegor256/jpeek/blob/79004d0cf652c23f98ae6d0209ade3cd1cce8d5d/src/test/java/org/jpeek/skeleton/XmlClassTest.java#L85-L86

The puzzle was created by Gnusin Pavel on 19-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#359](https://github.com/yegor256/jpeek/issues/359) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#359](https://github.com/yegor256/jpeek/issues/359), see [§21](http://www.zerocracy.com/policy.html#21); @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @thomas-melville[/z](https://www.0crat.com/u/thomas-melville)

**Comment by 0crat** [comment]
The user @thomas-melville[/z](https://www.0crat.com/u/thomas-melville) resigned from [#359](https://github.com/yegor256/jpeek/issues/359), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#359](https://github.com/yegor256/jpeek/issues/359) assigned to @monomonedula[/z](https://www.0crat.com/u/monomonedula), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a0054405-c3bb-4b14-a6ff-fa29f7a901af); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@monomonedula[/z](https://www.0crat.com/u/monomonedula) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @monomonedula[/z](https://www.0crat.com/u/monomonedula)

**Comment by 0crat** [comment]
The user @monomonedula[/z](https://www.0crat.com/u/monomonedula) resigned from [#359](https://github.com/yegor256/jpeek/issues/359), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#359](https://github.com/yegor256/jpeek/issues/359) assigned to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/c04c7c63-02b8-4d4b-8432-3d469f2a1fa6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@akryvtsun[/z](https://www.0crat.com/u/akryvtsun) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat assign @akryvtsun

**Comment by 0crat** [comment]
> @0crat assign @akryvtsun ([here](https://github.com/yegor256/jpeek/issues/359#issuecomment-573681417))

@paulodamaso The job [#359](https://github.com/yegor256/jpeek/issues/359) assigned to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a77aff66-0ae3-4fa9-97c8-a45ae0161f19); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @akryvtsun[/z](https://www.0crat.com/u/akryvtsun) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
> @0crat assign @akryvtsun ([here](https://github.com/yegor256/jpeek/issues/359#issuecomment-573681417))

@paulodamaso There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@9c2ebbbaf9da, thread: PQ-C7JGJ00DP
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [comment, job, issue, repo, cause, _parent_sig, flow, login]
```

[0.50.38](https://github.com/zerocracy/farm): CID: [d25c1093-bc67-4aeb-896a-bfbf32048417](https://www.0crat.com/footprint/C7JGJ00DP/d25c1093-bc67-4aeb-896a-bfbf32048417), Type: "Order was canceled"

**Comment by 0pdd** [comment]
The puzzle `297-5540e446` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @akryvtsun[/z](https://www.0crat.com/u/akryvtsun), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@9c2ebbbaf9da, thread: PQ-C7JGJ00DP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/jpeek#359] declared for identity constraint of element "speed".
```

[0.50.38](https://github.com/zerocracy/farm): CID: [9e587d77-5745-4a41-9d21-b8cabaa5b3a9](https://www.0crat.com/footprint/C7JGJ00DP/9e587d77-5745-4a41-9d21-b8cabaa5b3a9), Type: "Order was finished"

**Comment by 0crat** [comment]
The job [#359](https://github.com/yegor256/jpeek/issues/359) is now out of scope
