### ISSUE TITLE
duplicate class names crash the build

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#362]

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.4`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#362` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
