### ISSUE TITLE
gray badge

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#364]

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.5`

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#364` is not assigned, can't get performer
