### ISSUE TITLE
Test coverage of org.jpeek.web.Reports#apply has to be increased

### ISSUE THREAD

**Issue by akryvtsun** [yegor256/jpeek#371]
Code coverage of `org.jpeek.web.Reports#apply` was decreased and doesn't pass `Codecov` check for PRs #370 and #367 

https://codecov.io/gh/yegor256/jpeek/pull/367?src=pr&el=continue

![coverage](https://user-images.githubusercontent.com/1883572/71999270-c0fc8f00-3249-11ea-91ad-025ea63e7d33.png)

Probably, a test for branch of code should be added
```
...
if (exit != 0) {
    throw new IllegalStateException(
        String.format(
            "Failed to unzip %s:%s archive, exit code %d",
            group, artifact, exit
        )
    );
}
...
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/371#issuecomment-573696195))

@paulodamaso Job [#371](https://github.com/yegor256/jpeek/issues/371) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun)

**Comment by 0crat** [comment]
The job [#371](https://github.com/yegor256/jpeek/issues/371) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/b24d8e77-2209-4cbe-a586-fe77126f9b48); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dgarus** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/371#issuecomment-591462556))

@dgarus The impediment for [#371](https://github.com/yegor256/jpeek/issues/371) was registered successfully by @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by dgarus** [comment]
@akryvtsun Hello!

**Comment by dgarus** [comment]
> @akryvtsun Hello!
> Could you please close the issue.
> This problem was fixed [here](https://github.com/yegor256/jpeek/pull/385#issuecomment-592505454).

@paulodamaso pay attention please
