### ISSUE TITLE
package-info.java:31-34: Migrate the tests in the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#380]
The puzzle `323-1d9c6835` from #323 has to be resolved: 

https://github.com/yegor256/jpeek/blob/37d6b954d13c11672361a79a07fe2c0618a27eab/src/test/java/org/jpeek/package-info.java#L31-L34

The puzzle was created by Hamdi Douss on 17-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#380](https://github.com/yegor256/jpeek/issues/380) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/2cd953f8-b387-4974-b492-a6b0770de04b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `323-1d9c6835` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#388](https://github.com/yegor256/jpeek/issues/388) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#388](https://github.com/yegor256/jpeek/issues/388) is solved here.
