### ISSUE TITLE
MetricsTest.java:58-59: This test is fully written...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#381]
The puzzle `323-a6bff461` from #323 has to be resolved: 

https://github.com/yegor256/jpeek/blob/37d6b954d13c11672361a79a07fe2c0618a27eab/src/test/java/org/jpeek/MetricsTest.java#L58-L59

The puzzle was created by HDouss on 18-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#381](https://github.com/yegor256/jpeek/issues/381) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/83a07953-c055-46f8-9090-0c3a1b3e4121); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `323-a6bff461` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#381` is not assigned, can't get performer
