### ISSUE TITLE
ReportsTest should remove temp files.

### ISSUE THREAD

**Issue by dgarus** [yegor256/jpeek#386]
ReportsTest creates a dir and a few files. After the test finish, this stuff should be deleted.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by 0crat** [comment]
The job [#386](https://github.com/yegor256/jpeek/issues/386) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/31c08f53-0651-4a26-9ede-ec3e2884ca66); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@dgarus Please see PR #392

**Comment by dgarus** [comment]
@HDouss Ok. What should I do?

**Comment by HDouss** [comment]
@dgarus Nothing special. Mentioned you, so you can look at the solution and a link of this issue to the PR that solves it.

**Comment by HDouss** [comment]
@dgarus PR #392 reviewed and merged. Please close the issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
