### ISSUE TITLE
package-info.java:29-33: Migrate the tests in the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#388]
The puzzle `380-bf034369` from #380 has to be resolved: 

https://github.com/yegor256/jpeek/blob/c13b3213ae87d05fcde37ed91ef807938422227b/src/test/java/org/jpeek/package-info.java#L29-L33

The puzzle was created by HDouss on 19-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#388](https://github.com/yegor256/jpeek/issues/388) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1935fba1-3c12-4a70-a7e3-0db4c90befe3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@hdouss[/z](https://www.0crat.com/u/hdouss) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by HDouss** [comment]
@0crat wait some problems with rultor image

**Comment by 0crat** [comment]
> @0crat wait some problems with rultor image ([here](https://github.com/yegor256/jpeek/issues/388#issuecomment-591841841))

@HDouss The impediment for [#388](https://github.com/yegor256/jpeek/issues/388) was registered successfully by @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0pdd** [comment]
The puzzle `380-bf034369` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
