### ISSUE TITLE
Report.java:32-35: Now that we have the infrastructure to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#390]
The puzzle `296-9cbcd906` from #296 has to be resolved: 

https://github.com/yegor256/jpeek/blob/cd1547efa8c8f5b321dc07ca5e489c7fa8683f3b/src/main/java/org/jpeek/Report.java#L32-L35

The puzzle was created by Hamdi Douss on 21-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#390](https://github.com/yegor256/jpeek/issues/390) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/ee5b3aa4-9e48-4090-b303-5acd9385ad13); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `296-9cbcd906` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#397](https://github.com/yegor256/jpeek/issues/397) is still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#408](https://github.com/yegor256/jpeek/issues/408) is still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416), [#417](https://github.com/yegor256/jpeek/issues/417) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#484](https://github.com/yegor256/jpeek/issues/484) are still not solved; solved: [#396](https://github.com/yegor256/jpeek/issues/396), [#397](https://github.com/yegor256/jpeek/issues/397), [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473).
