### ISSUE TITLE
Too many temperory directories

### ISSUE THREAD

**Issue by HDouss** [yegor256/jpeek#394]
In our tests, we have too many creation of temporary folders that never gets deleted.
Every time we have `Files.createTempDirectory` (there are 25 in master at this exact time), we should replace that by JUnit `@TempDir` folders that gets deleted by JUnit automatically (this is the equivalent of temporary folders rules in JUnit 4).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0crat** [comment]
The job [#394](https://github.com/yegor256/jpeek/issues/394) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/44bcc718-b784-41a5-af27-3ea0fb667ee7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@dgarus[/z](https://www.0crat.com/u/dgarus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by dgarus** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/394#issuecomment-593969761))

@dgarus The impediment for [#394](https://github.com/yegor256/jpeek/issues/394) was registered successfully by @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by dgarus** [comment]
@HDouss could you pls close the issue.

**Comment by HDouss** [comment]
@dgarus Thank you!
