### ISSUE TITLE
XslReport.java:146-151: this constructor now has too many...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#396]
The puzzle `390-2105ac60` from #390 has to be resolved: 

https://github.com/yegor256/jpeek/blob/70ca3b893a386a475809bca70f019a904cffe7c7/src/main/java/org/jpeek/XslReport.java#L146-L151

The puzzle was created by HDouss on 24-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#396](https://github.com/yegor256/jpeek/issues/396) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/b56a25bb-25d4-4510-ad93-9b53d5caad47); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@0crat wait for merge

**Comment by 0crat** [comment]
> @0crat wait for merge ([here](https://github.com/yegor256/jpeek/issues/396#issuecomment-593126596))

@HDouss The impediment for [#396](https://github.com/yegor256/jpeek/issues/396) was registered successfully by @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0pdd** [comment]
The puzzle `390-2105ac60` has disappeared from the source code, that's why I closed this issue.
