### ISSUE TITLE
Calculus.java:33-36: We have a separate interface to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#397]
The puzzle `390-3f627cdf` from #390 has to be resolved: 

https://github.com/yegor256/jpeek/blob/70ca3b893a386a475809bca70f019a904cffe7c7/src/main/java/org/jpeek/Calculus.java#L33-L36

The puzzle was created by Hamdi Douss on 22-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#397](https://github.com/yegor256/jpeek/issues/397) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/54eb4930-12aa-4d27-a168-08cdc037cb92); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@0crat wait for merge

**Comment by 0crat** [comment]
> @0crat wait for merge ([here](https://github.com/yegor256/jpeek/issues/397#issuecomment-593317349))

@HDouss The impediment for [#397](https://github.com/yegor256/jpeek/issues/397) was registered successfully by @hdouss[/z](https://www.0crat.com/u/hdouss)

**Comment by 0pdd** [comment]
The puzzle `390-3f627cdf` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#408](https://github.com/yegor256/jpeek/issues/408) is still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416), [#417](https://github.com/yegor256/jpeek/issues/417) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#484](https://github.com/yegor256/jpeek/issues/484) are still not solved; solved: [#408](https://github.com/yegor256/jpeek/issues/408), [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473).
