### ISSUE TITLE
Add unit test to CAMC class that verifies a  single class.

### ISSUE THREAD

**Issue by alayor** [yegor256/jpeek#4]

**Comment by 0crat** [comment]
@alayor I'm not managing this repo, remove the [webhook](https://github.com/yegor256/jpeek/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@alayor fixed, I believe? Thanks for your contribution!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#4`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#4` is not in scope.
