### ISSUE TITLE
Optimize layer transformation in App

### ISSUE THREAD

**Issue by HDouss** [yegor256/jpeek#405]
The analysis process (`analyze` method in `App` class) is building a chain of xsl layer files. The skeleton transformation by these layers is done for every xsl report, to be given as input for that report.:
```java
new XslReport(
    chain.transform(skeleton), xsl,
    new ReportData("...", this.params)
)
```
`chain.transform` is called as many times as we have reports.
 We could do this transformation once and for all and give the result as input to the reports.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#405` is not assigned, can't get performer
