### ISSUE TITLE
release with new Docker image

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#406]
Let's release it with new config

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release tag is `0.30.9`

**Comment by 0crat** [comment]
The job [#406](https://github.com/yegor256/jpeek/issues/406) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/044ad772-9c82-4f16-ba75-5cc24287614b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release tag is `0.30.9`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.9`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.9`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.9`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.10`

**Comment by paulodamaso** [comment]
@rultor version tag is `0.30.11`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.11`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.12`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.12`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.13`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.14`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.15`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.16`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.17`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.17`

**Comment by yegor256** [comment]
@rultor release tag is `0.30.17`

**Comment by yegor256** [comment]
@paulodamaso fixed

**Comment by paulodamaso** [comment]
@yegor256 Thanks!
