### ISSUE TITLE
Calculus.java:33-36: We start having the infrastructure...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#408]
The puzzle `397-94351875` from #397 has to be resolved: 

https://github.com/yegor256/jpeek/blob/f0182127ff59ddd888ea4d9a322ca1cd86731059/src/main/java/org/jpeek/Calculus.java#L33-L36

The puzzle was created by HDouss on 28-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#408](https://github.com/yegor256/jpeek/issues/408) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/7394344c-b300-423a-a7ba-6210558b624b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `397-94351875` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416), [#417](https://github.com/yegor256/jpeek/issues/417) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#413](https://github.com/yegor256/jpeek/issues/413), [#416](https://github.com/yegor256/jpeek/issues/416) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#441](https://github.com/yegor256/jpeek/issues/441), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#484](https://github.com/yegor256/jpeek/issues/484) are still not solved; solved: [#412](https://github.com/yegor256/jpeek/issues/412), [#413](https://github.com/yegor256/jpeek/issues/413), [#417](https://github.com/yegor256/jpeek/issues/417), [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473).
