### ISSUE TITLE
Calculus.java:33-35: We start having the infrastructure...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#412]
The puzzle `408-c3533a7c` from #408 has to be resolved: 

https://github.com/yegor256/jpeek/blob/e76abc933c9a2e4ed9e700b78ffe98bd865c978f/src/main/java/org/jpeek/Calculus.java#L33-L35

The puzzle was created by Hamdi Douss on 05-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#412](https://github.com/yegor256/jpeek/issues/412) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/93b6ecbe-9465-4c91-a98b-2157c8d898cd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `408-c3533a7c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#416](https://github.com/yegor256/jpeek/issues/416), [#417](https://github.com/yegor256/jpeek/issues/417) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#416](https://github.com/yegor256/jpeek/issues/416) is still not solved; solved: [#417](https://github.com/yegor256/jpeek/issues/417).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#510](https://github.com/cqfn/jpeek/issues/510) is still not solved.
