### ISSUE TITLE
Lcom4Test.java:40-42: The methodMethodCalls test is...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#417]
The puzzle `412-a459088d` from #412 has to be resolved: 

https://github.com/yegor256/jpeek/blob/42e6dda5f2774c34ce51e2456bcd3eb350cea4eb/src/test/java/org/jpeek/calculus/java/Lcom4Test.java#L40-L42

The puzzle was created by HDouss on 09-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#417](https://github.com/yegor256/jpeek/issues/417) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/19cb8700-ed38-4c49-8203-0c93b23788f9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `412-a459088d` has disappeared from the source code, that's why I closed this issue.
