### ISSUE TITLE
OpsOf.java:87-102: Method call description has to contain...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#437]
The puzzle `403-214b0d9e` from #403 has to be resolved: 

https://github.com/yegor256/jpeek/blob/b62ae0fc337919e1f54d2b8d081343c69d536c97/src/main/java/org/jpeek/skeleton/OpsOf.java#L87-L102

The puzzle was created by sbt-garus-dg on 25-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#437](https://github.com/yegor256/jpeek/issues/437) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/da3090c2-e2f4-4d8c-a2b2-4f8adfaaaef0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/437#issuecomment-607716599))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#437](https://github.com/yegor256/jpeek/issues/437), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/437#issuecomment-607716599))

@victornoel Job refused in 17 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#437](https://github.com/yegor256/jpeek/issues/437) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/9068c887-ca86-4ca8-a7bd-f45559f10c5e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by dgarus** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/437#issuecomment-610254364))

@dgarus This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#437](https://github.com/yegor256/jpeek/issues/437) is [in scope](http://www.zerocracy.com/policy.html#14) for 6days
  * The role is `DEV`
  * The job is assigned to @dgarus[/z](https://www.0crat.com/u/dgarus) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @dgarus[/z](https://www.0crat.com/u/dgarus) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @victornoel[/z](https://www.0crat.com/u/victornoel): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23437%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@dgarus[/z](https://www.0crat.com/u/dgarus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by dgarus** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/437#issuecomment-612046263))

@dgarus This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#437](https://github.com/yegor256/jpeek/issues/437) is [in scope](http://www.zerocracy.com/policy.html#14) for 9days
  * The role is `DEV`
  * The job is assigned to @dgarus[/z](https://www.0crat.com/u/dgarus) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @dgarus[/z](https://www.0crat.com/u/dgarus) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @victornoel[/z](https://www.0crat.com/u/victornoel): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23437%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by dgarus** [comment]
@0crat wait

**Comment by vzurauskas** [comment]
@dgarus @paulodamaso What are we waiting for here?

**Comment by dgarus** [comment]
@0crat refuse

**Comment by dgarus** [comment]
@vzurauskas sorry, it's my fault. I'm on vacation

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/437#issuecomment-618946421))

@dgarus The user @dgarus[/z](https://www.0crat.com/u/dgarus) resigned from [#437](https://github.com/yegor256/jpeek/issues/437), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#437](https://github.com/yegor256/jpeek/issues/437) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3b98db94-57aa-40cf-a3ea-3f3a50c6bb74); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@hdouss[/z](https://www.0crat.com/u/hdouss) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by HDouss** [comment]
@0crat wait

**Comment by HDouss** [comment]
@paulodamaso please review or merge PR #464

**Comment by 0pdd** [comment]
The puzzle `403-214b0d9e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#469](https://github.com/yegor256/jpeek/issues/469), [#470](https://github.com/yegor256/jpeek/issues/470) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the puzzle [#469](https://github.com/yegor256/jpeek/issues/469) is still not solved; solved: [#470](https://github.com/yegor256/jpeek/issues/470).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#515](https://github.com/cqfn/jpeek/issues/515) is still not solved.
