### ISSUE TITLE
XmlGraph.java:110-113: The following 2 private methods...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#440]
The puzzle `413-309fe9c4` from #413 has to be resolved: 

https://github.com/yegor256/jpeek/blob/27d7bb11de1e6576f6c27b75635517c442451fe6/src/main/java/org/jpeek/graph/XmlGraph.java#L110-L113

The puzzle was created by Hamdi Douss on 06-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#440](https://github.com/yegor256/jpeek/issues/440) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/55270bc6-6300-4a8e-823b-03218a4681d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #442 to be merged

**Comment by 0pdd** [comment]
The puzzle `413-309fe9c4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by victornoel** [comment]
@sereshqua for the record, why just acceptable? thx :)

**Comment by sereshqua** [comment]
@victornoel wow, i am sorry, seems like i was having couple of issues opened and wrote wrong verdict here, instead of other one

**Comment by victornoel** [comment]
@sereshqua well no problem, I was just worried I was missing something :)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#459](https://github.com/yegor256/jpeek/issues/459) is still not solved; solved: [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#459](https://github.com/yegor256/jpeek/issues/459).
