### ISSUE TITLE
XmlGraphTest.java:43-45: In #413 we evolved graph...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#441]
The puzzle `413-b264bb98` from #413 has to be resolved: 

https://github.com/yegor256/jpeek/blob/27d7bb11de1e6576f6c27b75635517c442451fe6/src/test/java/org/jpeek/graph/XmlGraphTest.java#L43-L45

The puzzle was created by Hamdi Douss on 05-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#441](https://github.com/yegor256/jpeek/issues/441) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/8d664c5d-84c2-4b9d-8715-c601fd597648); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/441#issuecomment-610536549))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#441](https://github.com/yegor256/jpeek/issues/441), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/441#issuecomment-610536549))

@victornoel Job refused in 22 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#441](https://github.com/yegor256/jpeek/issues/441) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/6e678f17-4bdf-4391-afd9-b989b20cbad3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#445](https://github.com/yegor256/jpeek/issues/445) is still not solved.

**Comment by 0crat** [comment]
@dgarus[/z](https://www.0crat.com/u/dgarus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @dgarus[/z](https://www.0crat.com/u/dgarus) resigned from [#441](https://github.com/yegor256/jpeek/issues/441), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#441](https://github.com/yegor256/jpeek/issues/441) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/048ca3ca-1276-4ea6-a3f4-d3ad1122e97e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by marceloamadeu** [comment]
@0crat wait

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#445](https://github.com/yegor256/jpeek/issues/445).

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/441#issuecomment-625588275))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#441](https://github.com/yegor256/jpeek/issues/441), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#441](https://github.com/yegor256/jpeek/issues/441) assigned to @dfrau32[/z](https://www.0crat.com/u/dfrau32), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3a1b74b7-de00-4ad0-97e6-9da2747ff08d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by dfrau32** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/yegor256/jpeek/issues/441#issuecomment-625783504))

@dfrau32 The user @dfrau32[/z](https://www.0crat.com/u/dfrau32) resigned from [#441](https://github.com/yegor256/jpeek/issues/441), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/yegor256/jpeek/issues/441#issuecomment-625783504))

@dfrau32 Job refused in 7 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#441](https://github.com/yegor256/jpeek/issues/441) assigned to @iiylll[/z](https://www.0crat.com/u/iiylll), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1355a236-344b-45c4-a281-08da3ffa7c5c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@iiylll[/z](https://www.0crat.com/u/iiylll) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @iiylll[/z](https://www.0crat.com/u/iiylll) resigned from [#441](https://github.com/yegor256/jpeek/issues/441), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#441](https://github.com/yegor256/jpeek/issues/441) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/68f66f55-3cf0-4726-b26d-e0ff42ba6617); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for #441

**Comment by 0pdd** [comment]
The puzzle `413-b264bb98` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#473](https://github.com/yegor256/jpeek/issues/473) is still not solved; solved: [#445](https://github.com/yegor256/jpeek/issues/445), [#472](https://github.com/yegor256/jpeek/issues/472).

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/441#issuecomment-651532384))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/441#issuecomment-651532384))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0pdd** [comment]
@0pdd the puzzle [#484](https://github.com/yegor256/jpeek/issues/484) is still not solved; solved: [#445](https://github.com/yegor256/jpeek/issues/445), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473).
