### ISSUE TITLE
XmlMethodCall.java:35-37: This class XmlMethodCall should...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#443]
The puzzle `440-332bf733` from #440 has to be resolved: 

https://github.com/yegor256/jpeek/blob/94b2e98a33d57f864f7ac8a82ae373de11cc5f20/src/main/java/org/jpeek/graph/XmlMethodCall.java#L35-L37

The puzzle was created by Victor Noël on 09-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#443](https://github.com/yegor256/jpeek/issues/443) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3fe4b7c7-7362-4321-808b-854ac39480af); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vzurauskas** [comment]
@paulodamaso `XmlMethodCall` expects an `XML` in its constructor. Can you clarify whether this XML is supposed to be `method`, or `op` from within the `method`? Judging from the name of the class ("call" is a type of "op") and the way this class is used in `XmlGraph`, it should expect an `op`, but the way it's implemented, it expects a `method`: it expects the XML to contain `name` and `args`, and as far as I can tell, `op` elements don't have them.

**Comment by vzurauskas** [comment]
@0crat wait for an answer

**Comment by vzurauskas** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@vzurauskas Seems that it is supposed to be a method

**Comment by vzurauskas** [comment]
@paulodamaso I stumbled upon [this comment](https://github.com/yegor256/jpeek/issues/403#issuecomment-600493656) today. It turns out there are plans to enhance the `op` element with everything required for `XmlMethodCall` as it is now. So turns out it's an `op` after all.

**Comment by 0pdd** [comment]
The puzzle `440-332bf733` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good  ([here](https://github.com/yegor256/jpeek/issues/443#issuecomment-617914365))

@sereshqua There is no quality review for [#443](https://github.com/yegor256/jpeek/issues/443), no performer
