### ISSUE TITLE
XmlMethodArgs.java:35-37: This class XmlMethodArgs should...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#444]
The puzzle `440-83d3f1f7` from #440 has to be resolved: 

https://github.com/yegor256/jpeek/blob/94b2e98a33d57f864f7ac8a82ae373de11cc5f20/src/main/java/org/jpeek/graph/XmlMethodArgs.java#L35-L37

The puzzle was created by Victor Noël on 09-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#444](https://github.com/yegor256/jpeek/issues/444) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/14713d81-135c-4b40-bb6a-a7852298b1b1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-612435549))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#444](https://github.com/yegor256/jpeek/issues/444), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-612435549))

@victornoel Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#444](https://github.com/yegor256/jpeek/issues/444) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/d9ba340f-4633-4db4-b156-f7304239bae4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `440-83d3f1f7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#459](https://github.com/yegor256/jpeek/issues/459) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by HDouss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-618595607))

@HDouss This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#444](https://github.com/yegor256/jpeek/issues/444) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23444%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by HDouss** [comment]
@paulodamaso how to trigger rewards here?

**Comment by HDouss** [comment]
@paulodamaso I don't know if that helps, but can we do same thing here?

**Comment by HDouss** [comment]
@paulodamaso It helps, I received my reward in the other ticket.

**Comment by HDouss** [comment]
@paulodamaso Could you please ask 0crat out here?

**Comment by HDouss** [comment]
@paulodamaso ping

**Comment by HDouss** [comment]
@paulodamaso ping

**Comment by HDouss** [comment]
@paulodamaso Could you ask 0crat out here in order to trigger rewards?

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-619632824))

@paulodamaso Job `gh:yegor256/jpeek#444` is not assigned, can't get performer

**Comment by HDouss** [comment]
@paulodamaso any other idea how to trigger rewards?

**Comment by HDouss** [comment]
@paulodamaso the job is still listed in my agenda. Any help?

**Comment by HDouss** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-621185659))

@paulodamaso Job `gh:yegor256/jpeek#444` is not assigned, can't get performer

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-621314324))

@paulodamaso This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#444](https://github.com/yegor256/jpeek/issues/444) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23444%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@paulodamaso sorry to chip in (I'm getting the notifications), but why don't you just use 0crat pay? It seems 0crat missed the qa/payment because of a bug and the job is closed and invisible to 0crat now.

**Comment by paulodamaso** [comment]
@victornoel I usually use pay command as a last resort, because 0crat can close the issue and then the payment would be done twice.

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-621332070))

@paulodamaso There is no quality review for [#444](https://github.com/yegor256/jpeek/issues/444), no performer

**Comment by paulodamaso** [comment]
@0crat pay @HDouss 35min

**Comment by 0crat** [comment]
> @0crat pay @HDouss 35min ([here](https://github.com/yegor256/jpeek/issues/444#issuecomment-621344517))

@paulodamaso Argument "@HDouss" doesn't match regex `\d+min`

**Comment by HDouss** [comment]
@paulodamaso The job should also go away from my agenda, I don't want to keep it forever there.

**Comment by HDouss** [comment]
> @0crat pay @HDouss 35min

@paulodamaso  I think you should do "35min @HDouss"

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/444#issuecomment-621363046); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by paulodamaso** [comment]
@0crat pay 35min @HDouss

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ea0ebc5-1e90-4d29-b5a1-8c93eef19bcd, thread: pool-1222-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.13](https://github.com/zerocracy/farm): Issue: yegor256/jpeek#444, Comment: 621383825

**Comment by paulodamaso** [comment]
@0crat pay 35min @HDouss

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#459](https://github.com/yegor256/jpeek/issues/459) is solved here.
