### ISSUE TITLE
XmlGraph.java:40-43: Continue the work started with...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#445]
The puzzle `441-ed4884a5` from #441 has to be resolved: 

https://github.com/yegor256/jpeek/blob/94b2e98a33d57f864f7ac8a82ae373de11cc5f20/src/main/java/org/jpeek/graph/XmlGraph.java#L40-L43

The puzzle was created by Victor Noël on 09-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#445](https://github.com/yegor256/jpeek/issues/445) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/33713d44-ad22-45af-8e43-9af8adfb1953); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/jpeek/issues/443. Depending on how it goes, there's an opportunity to reuse some logic.

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/jpeek/pull/463

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/jpeek/pull/463 ([here](https://github.com/yegor256/jpeek/issues/445#issuecomment-618969567))

@vzurauskas Job [#445](https://github.com/yegor256/jpeek/issues/445) is already on hold

**Comment by 0pdd** [comment]
The puzzle `441-ed4884a5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the puzzle [#473](https://github.com/yegor256/jpeek/issues/473) is still not solved; solved: [#472](https://github.com/yegor256/jpeek/issues/472).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#484](https://github.com/yegor256/jpeek/issues/484) is still not solved; solved: [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473).
