### ISSUE TITLE
CCM calculation is wrong

### ISSUE THREAD

**Issue by vzurauskas** [yegor256/jpeek#447]
In `metricstest-params` there is a line `OverloadMethods,CCM,0.6d`. This means `OverloadMethods` class from the test samples has CCM of 0.6.

CCM = NC/(NMP x NCC)

In `OverloadMethods` there are 4 methods, each accessing the same attribute. So:
NC = 6
NMP = 6
NCC = 1

Therefore CCM should be 1.0, not 0.6.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#447](https://github.com/yegor256/jpeek/issues/447) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/dbd6bbaf-77c9-448d-bb68-d3fbf7d814cf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@vzurauskas why does NCC equals 1 ? It is the number of connected components, there are 4 methods and they are all connected to another method, so it should be 4, no?

And thus, CCM should be 6/(6x4) = 0.25

**Comment by victornoel** [comment]
@vzurauskas my bad, I better understand now, the number of connected component is the set of 4 methods that are connected together, so it is 1.

**Comment by victornoel** [comment]
@0crat wait for #450 to be merged

**Comment by victornoel** [comment]
@vzurauskas the problem is that the constructor is counted as one of the methods.

Furthermore I realised that the computation for NCC is incorrect (even though in this particular case it computes the correct result of 1). I opened #449 for that since it wasn't related to the bug you uncovered.

**Comment by 0pdd** [comment]
@vzurauskas the puzzle [#453](https://github.com/yegor256/jpeek/issues/453) is still not solved.

**Comment by victornoel** [comment]
@vzurauskas the PR has been merged and the work will continue in #453. Can you close this issue?

**Comment by vzurauskas** [comment]
@victornoel Closing, thanks.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@vzurauskas the only puzzle [#453](https://github.com/yegor256/jpeek/issues/453) is solved here.
