### ISSUE TITLE
Sorting is broken on the i.jpeek.org page

### ISSUE THREAD

**Issue by victornoel** [yegor256/jpeek#448]
When you try to sort the table on i.jpeek.org on the first column, you get the following:
![image](https://user-images.githubusercontent.com/160975/79071618-feefd000-7cdc-11ea-9da6-988b7416c221.png)

I would expect them to be ordered by number, no string.

Actually, it's not even clear what this number is for in the first column... maybe it could simply be deleted.

**Comment by paulodamaso** [comment]
@0crat in

**Comment by paulodamaso** [comment]
@victornoel Let's correct the ordering

**Comment by 0crat** [comment]
The job [#448](https://github.com/yegor256/jpeek/issues/448) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/53db2624-d6d1-497f-9394-7024126819d7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@victornoel PR #457 is merged. Please close the issue.

**Comment by victornoel** [comment]
@paulodamaso can we release a new version to validate the behaviour?

**Comment by HDouss** [comment]
@victornoel another possibility is to checkout master and test locally

**Comment by victornoel** [comment]
@HDouss I don't have the time nor the energy to do that :)

**Comment by HDouss** [comment]
@victornoel no problem :) it was in the case a new release is not possible today.

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.19`

**Comment by paulodamaso** [comment]
@victornoel @HDouss done, released a new version

**Comment by HDouss** [comment]
@victornoel Could you please verify?

**Comment by victornoel** [comment]
@HDouss @paulodamaso I don't know if the release failed or whatever, but looking at i.jpeek.org I still see the problem when sorting the first column:
![image](https://user-images.githubusercontent.com/160975/80089398-27d65780-855e-11ea-95c3-b35183a98f09.png)

**Comment by paulodamaso** [comment]
@victornoel The site is in the old version yet:
![image](https://user-images.githubusercontent.com/33915433/80094356-7a9f1780-853c-11ea-8ecd-2ce9b8eb1de7.png)

**Comment by HDouss** [comment]
@paulodamaso Should we wait or there is something to do to deploy the new release?

**Comment by paulodamaso** [comment]
@HDouss I'll check it

**Comment by HDouss** [comment]
@victornoel @paulodamaso if any of you can take 4 mins to checkout master and check it locally, that would be great..so we can close the issue.

**Comment by paulodamaso** [comment]
@victornoel could you please do this?

**Comment by victornoel** [comment]
@HDouss @paulodamaso let me close this without checking, I really don't have the time :) I will open another issue if it is still there in the future…

**Comment by HDouss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/448#issuecomment-618595452))

@HDouss This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#448](https://github.com/yegor256/jpeek/issues/448) is [in scope](http://www.zerocracy.com/policy.html#14) for 8days
  * The role is `DEV`
  * The job is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @hdouss[/z](https://www.0crat.com/u/hdouss) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23448%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by HDouss** [comment]
@paulodamaso how to trigger rewards here ?

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/448#issuecomment-618648091))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2a2b616a-ab99-4f89-991b-b5da510ebdce, thread: PQ-C7JGJ00DP
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pmo.awards.update_reputation
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.12](https://github.com/zerocracy/farm): CID: [4ce6849c-e290-4aab-acfa-1af734896e07](https://www.0crat.com/footprint/C7JGJ00DP/4ce6849c-e290-4aab-acfa-1af734896e07), Type: "Award points were added"

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/448#issuecomment-618648091))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2a2b616a-ab99-4f89-991b-b5da510ebdce, thread: PQ-C7JGJ00DP
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pmo.awards.activate_person
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.12](https://github.com/zerocracy/farm): CID: [4ce6849c-e290-4aab-acfa-1af734896e07](https://www.0crat.com/footprint/C7JGJ00DP/4ce6849c-e290-4aab-acfa-1af734896e07), Type: "Award points were added"

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.19`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.19`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.20`

**Comment by paulodamaso** [comment]
@victornoel Sorting is working as expected now

**Comment by paulodamaso** [comment]
@HDouss Thank you!

**Comment by HDouss** [comment]
@paulodamaso Nice!

**Comment by victornoel** [comment]
@paulodamaso @HDouss thanks :)
