### ISSUE TITLE
XmlMethodArgsTest.java:54-56: This test was disabled...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#459]
The puzzle `444-ff900aeb` from #444 has to be resolved: 

https://github.com/yegor256/jpeek/blob/3adeab9fb46585cc5947ce1dc8518f0b53d54052/src/test/java/org/jpeek/graph/XmlMethodArgsTest.java#L54-L56

The puzzle was created by Hamdi Douss on 21-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#459](https://github.com/yegor256/jpeek/issues/459) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1657ce78-877c-4c6e-a644-04c86324754c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat refuse - still blocked by https://github.com/yegor256/jpeek/issues/437

**Comment by 0crat** [comment]
> @0crat refuse - still blocked by https://github.com/yegor256/jpeek/issues/437 ([here](https://github.com/yegor256/jpeek/issues/459#issuecomment-618861703))

@vzurauskas The user @vzurauskas[/z](https://www.0crat.com/u/vzurauskas) resigned from [#459](https://github.com/yegor256/jpeek/issues/459), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse - still blocked by https://github.com/yegor256/jpeek/issues/437 ([here](https://github.com/yegor256/jpeek/issues/459#issuecomment-618861703))

@vzurauskas Job refused in 15 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#459](https://github.com/yegor256/jpeek/issues/459) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/262bf6a9-0f30-4786-8e95-ca23f4893dc0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/459#issuecomment-618926171))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#459](https://github.com/yegor256/jpeek/issues/459), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/459#issuecomment-618926171))

@HDouss Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#459](https://github.com/yegor256/jpeek/issues/459) assigned to @dfrau32[/z](https://www.0crat.com/u/dfrau32), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/84b0b8e6-4284-4646-a98a-b520003c0730); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@dfrau32[/z](https://www.0crat.com/u/dfrau32) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `444-ff900aeb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dfrau32[/z](https://www.0crat.com/u/dfrau32), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
