### ISSUE TITLE
ignore AjcClosure classes

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#46]
They are coming from AspectJ and shouldn't be analyzed.

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.4`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#46`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#46` is not in scope.
