### ISSUE TITLE
Fix jpeek merge and release

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/jpeek#465]
We need to fix jpeek merge and release
- fix merge,
- fix release with sonar execution, deploy at sonatype repository and deploy at dokku site

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/jpeek/issues/465#issuecomment-619553151))

@paulodamaso The job [#465](https://github.com/yegor256/jpeek/issues/465) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/ffb9b83a-a53b-4492-bdbf-335c45ff2901); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.22`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.23`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.23`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.24`
