### ISSUE TITLE
LormTest.java:41-42: This test was disabled after...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#470]
The puzzle `437-e6b95171` from #437 has to be resolved: 

https://github.com/yegor256/jpeek/blob/2b4d871b608c39a3d041619bc3dae7089930d4a7/src/test/java/org/jpeek/metrics/LormTest.java#L41-L42

The puzzle was created by rultor on 29-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#470](https://github.com/yegor256/jpeek/issues/470) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/8224e8fa-9162-48ff-9fbc-7595ba97046d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/jpeek/pull/471

**Comment by vzurauskas** [comment]
@paulodamaso PR was merged, the [puzzle was removed](https://github.com/yegor256/jpeek/pull/471/files), but PDD bot didn't close this task for some reason.

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/470#issuecomment-633262931))

@paulodamaso GitHub issue is still open, won't close

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
