### ISSUE TITLE
XmlGraph.java:77-80: This method works only for skeletons...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#473]
The puzzle `445-1cfd81f6` from #445 has to be resolved: 

https://github.com/yegor256/jpeek/blob/05d4100f0ab757ce44fd7f2087f8c35f5dfe3588/src/main/java/org/jpeek/graph/XmlGraph.java#L77-L80

The puzzle was created by Vytautas Žurauskas on 24-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#473](https://github.com/yegor256/jpeek/issues/473) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a7b46842-1549-4dd4-b201-dee400959eb5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#473](https://github.com/yegor256/jpeek/issues/473) assigned to @dfrau32[/z](https://www.0crat.com/u/dfrau32), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/fa6128a9-124a-4d1f-a53e-26372ce0d4ce); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@dfrau32[/z](https://www.0crat.com/u/dfrau32) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @dfrau32[/z](https://www.0crat.com/u/dfrau32) resigned from [#473](https://github.com/yegor256/jpeek/issues/473), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#473](https://github.com/yegor256/jpeek/issues/473) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/26b04210-7e40-49d1-b25f-c0d6e3ed488c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/473#issuecomment-631004439))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#473](https://github.com/yegor256/jpeek/issues/473), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#473](https://github.com/yegor256/jpeek/issues/473) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/c20c50c0-f26c-461d-93d3-211b8c897e59); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by dgarus** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/473#issuecomment-639508380))

@dgarus The user @dgarus[/z](https://www.0crat.com/u/dgarus) resigned from [#473](https://github.com/yegor256/jpeek/issues/473), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/473#issuecomment-639508380))

@dgarus Job refused in 7 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#473](https://github.com/yegor256/jpeek/issues/473) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/dc54ec49-2bd5-472e-84b1-8c4cba626a4e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/jpeek/pull/480

**Comment by 0pdd** [comment]
The puzzle `445-1cfd81f6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#484](https://github.com/yegor256/jpeek/issues/484) is still not solved.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bcf4c1ce-a1bb-461a-bc3c-b71f9064f293, thread: PQ-C7JGJ00DP
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.pay_cash
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: Failed to add transaction
com.zerocracy.pm.cost.Ledger[133] java.io.IOException: Failed to add transaction
org.postgresql.jdbc.PgConnection[767] org.postgresql.util.PSQLException: This connection has been closed.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [9d83c85f-65a7-4729-97f3-53220896f51d](https://www.0crat.com/footprint/C7JGJ00DP/9d83c85f-65a7-4729-97f3-53220896f51d), Type: "Pay cash"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bcf4c1ce-a1bb-461a-bc3c-b71f9064f293, thread: PQ-C7JGJ00DP
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.pay_cash
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: Failed to add transaction
com.zerocracy.pm.cost.Ledger[133] java.io.IOException: Failed to add transaction
org.postgresql.core.v3.ConnectionFactoryImpl[245] org.postgresql.util.PSQLException: Connection to pgsql.0dmx.com:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
java.net.PlainSocketImpl[-2] java.net.ConnectException: Connection refused (Connection refused)
```

[0.54.5](https://github.com/zerocracy/farm): CID: [1195bef0-0da3-457d-a9a7-c6a50a7e5b68](https://www.0crat.com/footprint/C7JGJ00DP/1195bef0-0da3-457d-a9a7-c6a50a7e5b68), Type: "Pay cash"

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0pdd** [comment]
@0pdd the puzzle [#509](https://github.com/cqfn/jpeek/issues/509) is still not solved.
