### ISSUE TITLE
LCOM

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#6]
Let's implement LCOM cohesion metric.

S. R. Chidamber and C. F. Kemerer, A metrics suite for object oriented design. IEEE Transactions on Software Engineering, vol.20, no.6, 1994.

http://www.pitt.edu/~ckemerer/CK%20research%20papers/MetricForOOD_ChidamberKemerer94.pdf

Shyam R. Chidamber, Chris F. Kemerer. A Metrics suite for Object Oriented design. M.I.T. Sloan School of Management E53-315. 1993. http://uweb.txstate.edu/~mg43/CS5391/Papers/Metrics/OOMetrics.pdf

Victor Basili, Lionel Briand and Walcelio Melo. A Validation of Object-Oriented Design Metrics as Quality Indicators. IEEE Transactions on Software Engineering. Vol. 22, No. 10, October 1996. http://www.cs.umd.edu/users/basili/publications/journals/J60.pdf

Bindu S. Gupta: A Critique of Cohesion Measures in the Object-Oriented Paradigm. Master of Science Thesis. Michigan Technological University, Department of Computer Science. 1997.

**Comment by yegor256** [comment]
@rultor release, tag is `0.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#6`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#6` was not in scope
