### ISSUE TITLE
TLCOM

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#65]
Let's implement TLCOM cohesion metric:

Transitive-based object-oriented lack-of-cohesion metric, Jehad Al Dallal, Department of Information Science, Kuwait University, P.O. Box 5969, Safat 13060, Kuwait.

https://www.researchgate.net/publication/220307725_Transitive-based_object-oriented_lack-of-cohesion_metric

**Comment by 0crat** [comment]
Job [#65](https://github.com/yegor256/jpeek/issues/65) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7225](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#65](https://github.com/yegor256/jpeek/issues/65) assigned to janczer. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@janczer[/z](https://www.0crat.com/u/janczer) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by janczer** [comment]
0crat refuse

**Comment by janczer** [comment]
@0crat refuse

**Comment by 0crat** [comment]
@janczer[/z](https://www.0crat.com/u/janczer) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by janczer** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/65#issuecomment-359427123))

@janczer The user @janczer[/z](https://www.0crat.com/u/janczer) resigned from [#65](https://github.com/yegor256/jpeek/issues/65), please stop working

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/65#issuecomment-359696292))

@janczer Job `gh:yegor256/jpeek#65` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://datum.zerocracy.com/pages/policy.html#6): -15 points just awarded to @janczer[/z](https://www.0crat.com/u/janczer), total is [-45](https://www.0crat.com/u/janczer)

**Comment by 0crat** [comment]
The job [#65](https://github.com/yegor256/jpeek/issues/65) assigned to @driver733[/z](https://www.0crat.com/u/driver733). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/65#issuecomment-362111613))

@driver733 The impediment for [#65](https://github.com/yegor256/jpeek/issues/65) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#65](https://github.com/yegor256/jpeek/issues/65) assigned to @gizmomogwai[/z](https://www.0crat.com/u/gizmomogwai). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The user @skapral[/z](https://www.0crat.com/u/skapral) resigned from [#65](https://github.com/yegor256/jpeek/issues/65), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://datum.zerocracy.com/pages/policy.html#8): -30 points just awarded to @skapral[/z](https://www.0crat.com/u/skapral), total is [+150](https://www.0crat.com/u/skapral)

**Comment by 0crat** [comment]
The job [#65](https://github.com/yegor256/jpeek/issues/65) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/510730555). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@yegor256 this metric establishes indirect connections between methods via chains of method calls that can be arbitrarily long. 

For example, if `m1` calls `m2` and `m2` calls `m3` and `m3` calls `m4` and `m4` uses attribute `a4`, then `m1` is connected to `m4` (they both use `a4`).

This recursion of arbitrary depth is proving to be hard to implement within budget. Can the full recursion be left as a puzzle?

**Comment by yegor256** [comment]
@llorllale yes, sure

**Comment by llorllale** [comment]
@yegor256 can we close this?

* Initial implementation was merged in PR #209 
* Puzzle #219 left to complete the [full recursion](https://github.com/yegor256/jpeek/issues/65#issuecomment-367102226)
* Puzzle #218 left due to impediment on #156 
* Puzzle #220 left due to impediment on #171

**Comment by yegor256** [comment]
@llorllale thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+869](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+900](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/65#issuecomment-369213428))

@ypshenychka The job [#65](https://github.com/yegor256/jpeek/issues/65) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#499](https://github.com/cqfn/jpeek/issues/499), [#500](https://github.com/cqfn/jpeek/issues/500), [#501](https://github.com/cqfn/jpeek/issues/501) are still not solved.

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/cqfn/jpeek/issues/65#issuecomment-369213428))

@ypshenychka You @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) need to have one of these roles in order to do "Complete `QA` review": `ARC`, `QA`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/cqfn/jpeek/issues/65#issuecomment-362111613))

@driver733 Job `gh:cqfn/jpeek#65` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/cqfn/jpeek/issues/65#issuecomment-359427123))

@janczer Job `gh:cqfn/jpeek#65` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/cqfn/jpeek/issues/65#issuecomment-359696292))

@janczer Job `gh:cqfn/jpeek#65` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#499](https://github.com/cqfn/jpeek/issues/499), [#500](https://github.com/cqfn/jpeek/issues/500) are still not solved; solved: [#501](https://github.com/cqfn/jpeek/issues/501).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#583](https://github.com/cqfn/jpeek/issues/583), [#584](https://github.com/cqfn/jpeek/issues/584) are still not solved; solved: [#499](https://github.com/cqfn/jpeek/issues/499), [#500](https://github.com/cqfn/jpeek/issues/500), [#501](https://github.com/cqfn/jpeek/issues/501).
