### ISSUE TITLE
CCM

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#66]
Let's implement CCM cohesion metric:

A. Jarallah, M. Wasiq, and M. Ahmed, “Principle and metrics
for cohesion-based object-oriented component assessment,” 2001,
confidential Draft Copy.

http://ijarcsee.org/index.php/IJARCSEE/article/view/385 (I didn't find the PDF)

**Comment by 0crat** [comment]
Job [#66](https://github.com/yegor256/jpeek/issues/66) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7225](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#66](https://github.com/yegor256/jpeek/issues/66) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/66#issuecomment-361562661))

@llorllale This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#66](https://github.com/yegor256/jpeek/issues/66) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 16days
  * The role is `DEV`
  * The job is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale) for [7hr](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @llorllale[/z](https://www.0crat.com/u/llorllale) will get 0.00 of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @flslkxtc[/z](https://www.0crat.com/u/flslkxtc): User was resigned from the ticket

**Comment by llorllale** [comment]
PDF obtained from the link
[Alhadi13.pdf](https://github.com/yegor256/jpeek/files/1680118/Alhadi13.pdf)

**Comment by llorllale** [comment]
@yegor256 I do not see the definition for CCM:

* The link you provided contains only the paper's abstract
* The PDF obtained from the "Full PDF" link does not contain its definition either

**Comment by yegor256** [comment]
@llorllale I guess this metric can't be implemented. I also didn't manage to find the original PDF. Maybe you can email the author of the metric?

**Comment by llorllale** [comment]
@yegor256 I believe this is what you're looking for, starting at page 40, obtained from [here](http://eprints.kfupm.edu.sa/10437/): 

[Wasiq01.pdf](https://github.com/yegor256/jpeek/files/1682891/Wasiq01.pdf)

To implement CCM we need a way to include in every `<method>` any invocation of another method of the same class.

**Comment by llorllale** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/66#issuecomment-362033609))

@llorllale The impediment for [#66](https://github.com/yegor256/jpeek/issues/66) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by yegor256** [comment]
@llorllale feel free to submit a new bug about it, if something is not enough in `skeleton.xml`

**Comment by llorllale** [comment]
@yegor256 I think we can close this now

**Comment by yegor256** [comment]
@llorllale thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+420](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#66](https://github.com/yegor256/jpeek/issues/66) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#146](https://github.com/yegor256/jpeek/issues/146), [#148](https://github.com/yegor256/jpeek/issues/148), [#149](https://github.com/yegor256/jpeek/issues/149) are still not solved; solved: [#147](https://github.com/yegor256/jpeek/issues/147).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#146](https://github.com/yegor256/jpeek/issues/146), [#148](https://github.com/yegor256/jpeek/issues/148) are still not solved; solved: [#147](https://github.com/yegor256/jpeek/issues/147), [#149](https://github.com/yegor256/jpeek/issues/149).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#146](https://github.com/yegor256/jpeek/issues/146) is still not solved; solved: [#147](https://github.com/yegor256/jpeek/issues/147), [#148](https://github.com/yegor256/jpeek/issues/148), [#149](https://github.com/yegor256/jpeek/issues/149).

**Comment by 0pdd** [comment]
@yegor256 all 4 puzzles are solved here: [#146](https://github.com/yegor256/jpeek/issues/146), [#147](https://github.com/yegor256/jpeek/issues/147), [#148](https://github.com/yegor256/jpeek/issues/148), [#149](https://github.com/yegor256/jpeek/issues/149).
