### ISSUE TITLE
SCOM

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#68]
Let's implement SCOM cohesion metric:

L. Fern´andez and R. Pe˜na, “A sensitive metric of class cohesion,”
vol. 13, pp. 82–91, 2006.

http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=55D08270F99333F15E0937AF137F4468?doi=10.1.1.84.1506&rep=rep1&type=pdf

**Comment by 0crat** [comment]
Job [#68](https://github.com/yegor256/jpeek/issues/68) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7225](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#68](https://github.com/yegor256/jpeek/issues/68) assigned to janczer. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@janczer[/z](https://www.0crat.com/u/janczer) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by janczer** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/68#issuecomment-359427088))

@janczer The user @janczer[/z](https://www.0crat.com/u/janczer) resigned from [#68](https://github.com/yegor256/jpeek/issues/68), please stop working

**Comment by 0crat** [comment]
The job [#68](https://github.com/yegor256/jpeek/issues/68) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@yegor256 I believe we can close this

**Comment by yegor256** [comment]
@llorllale thanks!

**Comment by llorllale** [comment]
@yegor256 missed points + payment on this one

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/68#issuecomment-362936411))

@llorllale This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#68](https://github.com/yegor256/jpeek/issues/68) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 21days
  * The role is `DEV`
  * The job is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale) for [6days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @llorllale[/z](https://www.0crat.com/u/llorllale) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @janczer[/z](https://www.0crat.com/u/janczer): User was resigned from the ticket

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+450](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#68](https://github.com/yegor256/jpeek/issues/68) is now out of scope

**Comment by yegor256** [comment]
@llorllale fixed, I believe. Feel free to report this situation to Zerocrat.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#140](https://github.com/yegor256/jpeek/issues/140) is still not solved; solved: [#141](https://github.com/yegor256/jpeek/issues/141), [#142](https://github.com/yegor256/jpeek/issues/142).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#513](https://github.com/cqfn/jpeek/issues/513) is still not solved.
