### ISSUE TITLE
LCOM2 and LCOM3

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#7]
Let's implement LCOM2 and LCOM3. See http://www.aivosto.com/project/help/pm-oo-cohesion.html

Henderson-Sellers, B, L, Constantine and I, Graham , 'Coupling and Cohesion (Towards a Valid Metrics Suite for Object-Oriented Analysis and Design)', Object-Oriented Systems, 3(3), pp143-158, 1996.

http://www.ibrarian.net/navon/paper/Coupling_and_cohesion__towards_a_valid_metrics_su.pdf?paperid=1090060

**Comment by memoyil** [comment]
I am looking at it

**Comment by yegor256** [comment]
@memoyil thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.9`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#7`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#7` is not in scope.

**Comment by yegor256** [comment]
@memoyil you didn't update the README page. Could you please do that?

**Comment by memoyil** [comment]
@yegor256 done.
