### ISSUE TITLE
RsPage for XML rendering

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#71]
Let's make XML visible in web front.

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#71`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#71` is not in scope.
