### ISSUE TITLE
show all artifacts in /all

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#72]
Let's add `/all` page

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.2`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#72`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#72` is not in scope.
