### ISSUE TITLE
best μ and σ

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#74]
Let's record best μ and σ for all visible metrics.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#74` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+6225](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+6225](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#74` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+6255](http://www.0crat.com/u/yegor256).
