### ISSUE TITLE
reports and mistakes are not synchronized

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#75]
Let's synchronize them.

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#75`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#75` is not in scope.
