### ISSUE TITLE
represent classes in XML

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#85]
Let's make them visible in XML and all metrics make XML processing.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#85` assigned to @yegor256  ([profile](http://www.0crat.com/u/yegor256})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@yegor256 this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@yegor256 this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:yegor256/jpeek#85`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#85` assigned to [@janczer](http://www.0crat.com/u/janczer}) (`DEV`). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by janczer** [comment]
@yegor256 What's mean 'represent classes'? Classes are in xml already:

```
<package element="false" id="org.jpeek.metrics.cohesion">
         <class color="yellow" element="true" id="NHD" value="0.5000">
```

**Comment by yegor256** [comment]
@0crat assign me

**Comment by yegor256** [comment]
@janczer I will do it myself (almost finished)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/jpeek/issues/85#issuecomment-356661233))

@yegor256 The job [#85](https://github.com/yegor256/jpeek/issues/85) assigned to yegor256. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+6690](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+6690](http://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.23`

**Comment by yegor256** [comment]
@rultor release, tag is `0.23`

**Comment by yegor256** [comment]
@rultor release, tag is `0.23`

**Comment by 0crat** [comment]
The job [#85](https://github.com/yegor256/jpeek/issues/85) is now out of scope

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7280](http://www.0crat.com/u/yegor256)
