### ISSUE TITLE
0crat rejects validly formatted rate when applying

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/jpeek#88]
I'm trying to apply to a project via Slack. `@0crat` does not accept the request, telling me that my rate is invalidly formatted. But I used the correct format (e.g. $25)

![image](https://user-images.githubusercontent.com/1917892/34751237-5798bc2e-f5e6-11e7-826c-9146902110ba.png)

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by carlosmiranda** [comment]
@0crat Oops, wrong project.

**Comment by 0crat** [comment]
> @0crat Oops, wrong project. ([here](https://github.com/yegor256/jpeek/issues/88#issuecomment-356467741))

@carlosmiranda Can't understand "Oops,", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#88` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#88` was not in scope
