### ISSUE TITLE
Contibuting guidelines doesn't say about PDD

### ISSUE THREAD

**Issue by janczer** [yegor256/jpeek#89]
File [CONTRIBUTING.md](https://github.com/yegor256/jpeek/blob/master/CONTRIBUTING.md) hasn't anything about [PDD](http://www.yegor256.com/2010/03/04/pdd.html) but the project use it.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#89` is not assigned, can't get performer
