### ISSUE TITLE
TCC and LCC

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#9]
Let's implement TCC and LCC metrics.

Bieman, James M. & Kang, Byung-Kyoo: Cohesion and reuse in an object-oriented system. Proceedings of the 1995 Symposium on Software. Pages: 259 - 262. ISSN:0163-5948. ACM Press New York, NY, USA. 

https://pdfs.semanticscholar.org/672e/de6e3e600eafd84036a0b983b88e481ac626.pdf

**Comment by sergey-karazhenets** [comment]
I'm working on it

**Comment by 0crat** [comment]
Job [#9](https://github.com/yegor256/jpeek/issues/9) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7225](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#9](https://github.com/yegor256/jpeek/issues/9) assigned to @skapral[/z](https://www.0crat.com/u/skapral). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by skapral** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/9#issuecomment-359929760))

@skapral This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#9](https://github.com/yegor256/jpeek/issues/9) is in scope
  * The role is `DEV`
  * The job is assigned to @skapral[/z](https://www.0crat.com/u/skapral)
  * These users are banned: @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/9#issuecomment-360139225))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#9](https://github.com/yegor256/jpeek/issues/9) is in scope
  * The role is `DEV`
  * The job is assigned to @skapral[/z](https://www.0crat.com/u/skapral) for 21hr
  * These users are banned: @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by skapral** [comment]
@yegor256 please close this issue, since the pull request changes are in upstream.

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by skapral** [comment]
> @yegor256 please close this issue, since the pull request changes are in upstream.

@yegor256 ?

**Comment by yegor256** [comment]
@skapral thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @skapral[/z](https://www.0crat.com/u/skapral), total is [+135](https://www.0crat.com/u/skapral)

**Comment by 0crat** [comment]
The job [#9](https://github.com/yegor256/jpeek/issues/9) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 6 puzzles [#193](https://github.com/yegor256/jpeek/issues/193), [#194](https://github.com/yegor256/jpeek/issues/194), [#195](https://github.com/yegor256/jpeek/issues/195), [#217](https://github.com/yegor256/jpeek/issues/217), [#252](https://github.com/yegor256/jpeek/issues/252), [#253](https://github.com/yegor256/jpeek/issues/253) are still not solved; solved: [#117](https://github.com/yegor256/jpeek/issues/117), [#118](https://github.com/yegor256/jpeek/issues/118), [#119](https://github.com/yegor256/jpeek/issues/119), [#120](https://github.com/yegor256/jpeek/issues/120).

**Comment by 0pdd** [comment]
@yegor256 6 puzzles [#193](https://github.com/yegor256/jpeek/issues/193), [#194](https://github.com/yegor256/jpeek/issues/194), [#195](https://github.com/yegor256/jpeek/issues/195), [#217](https://github.com/yegor256/jpeek/issues/217), [#253](https://github.com/yegor256/jpeek/issues/253), [#356](https://github.com/yegor256/jpeek/issues/356) are still not solved; solved: [#117](https://github.com/yegor256/jpeek/issues/117), [#118](https://github.com/yegor256/jpeek/issues/118), [#119](https://github.com/yegor256/jpeek/issues/119), [#120](https://github.com/yegor256/jpeek/issues/120), [#252](https://github.com/yegor256/jpeek/issues/252).

**Comment by 0pdd** [comment]
@yegor256 6 puzzles [#193](https://github.com/yegor256/jpeek/issues/193), [#194](https://github.com/yegor256/jpeek/issues/194), [#195](https://github.com/yegor256/jpeek/issues/195), [#217](https://github.com/yegor256/jpeek/issues/217), [#252](https://github.com/yegor256/jpeek/issues/252), [#253](https://github.com/yegor256/jpeek/issues/253) are still not solved; solved: [#117](https://github.com/yegor256/jpeek/issues/117), [#118](https://github.com/yegor256/jpeek/issues/118), [#119](https://github.com/yegor256/jpeek/issues/119), [#120](https://github.com/yegor256/jpeek/issues/120), [#356](https://github.com/yegor256/jpeek/issues/356).

**Comment by 0pdd** [comment]
@yegor256 5 puzzles [#193](https://github.com/yegor256/jpeek/issues/193), [#194](https://github.com/yegor256/jpeek/issues/194), [#195](https://github.com/yegor256/jpeek/issues/195), [#217](https://github.com/yegor256/jpeek/issues/217), [#252](https://github.com/yegor256/jpeek/issues/252) are still not solved; solved: [#117](https://github.com/yegor256/jpeek/issues/117), [#118](https://github.com/yegor256/jpeek/issues/118), [#119](https://github.com/yegor256/jpeek/issues/119), [#120](https://github.com/yegor256/jpeek/issues/120), [#253](https://github.com/yegor256/jpeek/issues/253), [#356](https://github.com/yegor256/jpeek/issues/356).

**Comment by 0pdd** [comment]
@yegor256 4 puzzles [#193](https://github.com/yegor256/jpeek/issues/193), [#194](https://github.com/yegor256/jpeek/issues/194), [#217](https://github.com/yegor256/jpeek/issues/217), [#252](https://github.com/yegor256/jpeek/issues/252) are still not solved; solved: [#117](https://github.com/yegor256/jpeek/issues/117), [#118](https://github.com/yegor256/jpeek/issues/118), [#119](https://github.com/yegor256/jpeek/issues/119), [#120](https://github.com/yegor256/jpeek/issues/120), [#195](https://github.com/yegor256/jpeek/issues/195), [#253](https://github.com/yegor256/jpeek/issues/253), [#356](https://github.com/yegor256/jpeek/issues/356).
