### ISSUE TITLE
OCC via XML

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#90]
We had OCC metric implemented before in #19, but now our calculation mechanism is very different. We should re-implement OCC via XML/XSL.

**Comment by 0crat** [comment]
Job [#90](https://github.com/yegor256/jpeek/issues/90) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7240](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#90](https://github.com/yegor256/jpeek/issues/90) assigned to vmotsak. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by vmotsak** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/90#issuecomment-358442985))

@vmotsak @vmotsak[/z](http://www.0crat.com/u/vmotsak) resigned from [#90](https://github.com/yegor256/jpeek/issues/90), please stop working

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://datum.zerocracy.com/pages/policy.html#6): -15 points just awarded to @vmotsak[/z](http://www.0crat.com/u/vmotsak), total is [+15](http://www.0crat.com/u/vmotsak)

**Comment by 0crat** [comment]
The job [#90](https://github.com/yegor256/jpeek/issues/90) assigned to @driver733[/z](https://www.0crat.com/u/driver733). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
@0crat waiting. Will get back to it after other algorithms.

**Comment by 0crat** [comment]
> @0crat waiting. Will get back to it after other algorithms. ([here](https://github.com/yegor256/jpeek/issues/90#issuecomment-361804200))

@driver733 Can't understand "waiting.", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/90#issuecomment-361807383))

@driver733 The impediment for [#90](https://github.com/yegor256/jpeek/issues/90) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#90](https://github.com/yegor256/jpeek/issues/90) assigned to @gizmomogwai[/z](https://www.0crat.com/u/gizmomogwai). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The job [#90](https://github.com/yegor256/jpeek/issues/90) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/402013523). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
Currently blocked by #172

**Comment by llorllale** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/90#issuecomment-365029448))

@llorllale The impediment for [#90](https://github.com/yegor256/jpeek/issues/90) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@yegor256 OCC implemented in #168 while a puzzle was left to finish implementing test cases (#203)

Can we close this now?

**Comment by yegor256** [comment]
@llorllale thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@llorllale According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your [message](https://github.com/yegor256/jpeek/issues/90#issuecomment-365029415) by indicating an addressee in the beginning.

**Comment by llorllale** [comment]
@ypshenychka fixed message

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+285](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/90#issuecomment-366887762))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Paypal[122] java.io.IOException: Failed to pay $8.00 to george.aristy@gmail.com with memo "Payment for gh:yegor256/jpeek#90 (30 minutes): Order was finished, quality was "acceptable""
com.zerocracy.pmo.banks.Paypal[201] java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The payment can not be processed because no payment source is available]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+685](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#203](https://github.com/yegor256/jpeek/issues/203) is solved here.
