### ISSUE TITLE
MMAC via XML

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#91]
We had MMAC metric implemented before in #14, but now our calculation mechanism is very different. We should re-implement OCC via XML/XSL.

**Comment by 0crat** [comment]
Job [#91](https://github.com/yegor256/jpeek/issues/91) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7240](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#91](https://github.com/yegor256/jpeek/issues/91) assigned to vmotsak. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by vmotsak** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/91#issuecomment-358442888))

@vmotsak The impediment was registered successfully

**Comment by 0crat** [comment]
@vmotsak[/z](https://www.0crat.com/u/vmotsak) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@vmotsak I believe it's fixed, thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @vmotsak[/z](https://www.0crat.com/u/vmotsak), total is [+45](https://www.0crat.com/u/vmotsak)

**Comment by 0crat** [comment]
The job [#91](https://github.com/yegor256/jpeek/issues/91) is now out of scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.24`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24`
