### ISSUE TITLE
LCOM2/3 via XML

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#92]
We had LCOM2/3 metric implemented before in #7, but now our calculation mechanism is very different. We should re-implement OCC via XML/XSL.

**Comment by 0crat** [comment]
Job [#92](https://github.com/yegor256/jpeek/issues/92) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7255](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#92](https://github.com/yegor256/jpeek/issues/92) assigned to janczer. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@janczer[/z](https://www.0crat.com/u/janczer) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by janczer** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/92#issuecomment-359423737))

@janczer The user @janczer[/z](https://www.0crat.com/u/janczer) resigned from [#92](https://github.com/yegor256/jpeek/issues/92), please stop working

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://datum.zerocracy.com/pages/policy.html#6): -15 points just awarded to @janczer[/z](https://www.0crat.com/u/janczer), total is [-15](https://www.0crat.com/u/janczer)

**Comment by 0crat** [comment]
The job [#92](https://github.com/yegor256/jpeek/issues/92) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@yegor256 I believe we can close this now

**Comment by yegor256** [comment]
@llorllale thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+390](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#92](https://github.com/yegor256/jpeek/issues/92) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#138](https://github.com/yegor256/jpeek/issues/138), [#139](https://github.com/yegor256/jpeek/issues/139), [#228](https://github.com/yegor256/jpeek/issues/228).
