### ISSUE TITLE
skeleton.xsd should clearly mark which args are input and which is the output

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#97]
As mentioned [here](https://github.com/yegor256/jpeek/issues/93#issuecomment-359050608), there currently is no clear way to determine which of the args are input and which is output (if any). I'm not sure if the format for `method/@desc` is reliable, but even so, this is fundamental information that should ideally be represented in the schema.

Example XML produced today:
```xml
<method abstract="false"
        ctor="false"
        desc="(Ljava/lang/String;)Ljava/util/Optional;"
        name="get"
        public="true"
        static="false">
   <args>
      <arg type="Ljava/lang/String">?</arg>
      <arg type="Ljava/util/Optional">?</arg>
   </args>
</method>
```
Example XML that would give me enough info to discern input from output types:
```xml
<method abstract="false"
        ctor="false"
        desc="(Ljava/lang/String;)Ljava/util/Optional;"
        name="get"
        public="true"
        static="false">
   <args>
      <in type="Ljava/lang/String">?</in>
      <out type="Ljava/util/Optional">?</out>
   </args>
</method>
```

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+150](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7730](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@llorllale should be fine now, each `<method>` will have `<return>` element

**Comment by llorllale** [comment]
@yegor256 confirmed, thanks.

Sample XML now generated from method `public String doSomething(int id, Integer blah)` is:
```xml
<method abstract="false"
        ctor="false"
        desc="(ILjava/lang/Integer;)Ljava/lang/String;"
        name="doSomething"
        public="true"
        static="false">
   <return>Ljava/lang/String</return>
   <args>
      <arg type="I">?</arg>
      <arg type="Ljava/lang/Integer">?</arg>
   </args>
</method>
```

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7800](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#97](https://github.com/yegor256/jpeek/issues/97) is now out of scope
