### ISSUE TITLE
What means `ops` and `op`

### ISSUE THREAD

**Issue by janczer** [yegor256/jpeek#98]
```
<xs:element name="ops" minOccurs="0" maxOccurs="1">
```

What means in skeleton.xsd `ops` and `op`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@janczer it's short for "operations" and "operation"

**Comment by llorllale** [comment]
@yegor256 to be clear, are these the class attributes used by each method?

**Comment by yegor256** [comment]
@llorllale they are operations inside the method. At the moment we have only attributes-accessing operations, but can add others in the future, if necessary.

**Comment by llorllale** [comment]
@yegor256 then we need a way to differentiate ops that access attributes from the rest (LCOM5 #18).

**Comment by yegor256** [comment]
@llorllale we have `type` for that
